Repository adempiere/adempiere, pull requests merged in 2018-07, with the labels that each got.

#1806 #1805, Add helper method for PaymentExportList class, reference to
  base/src/org/compiere/util/PaymentExportList.java
Labels: (AP) Account Payable, (FIM) Financial Management, 01 enhancement

#1789 #1635, Add force parameter support to import XML loader, reference to
  base/src/org/adempiere/process/MigrationLoader.java
  base/src/org/compiere/model/MMigration.java
  base/src/org/compiere/process/MigrationFromXML.java
  utils/RUN_MigrateXML.bat
  utils/RUN_MigrateXML.sh
Labels: (MT) Migration Tools, 02 bug

#1804 #1803 Allows evaluate of default value based on the other parameter c…
  org.adempiere.asset/src/main/java/base/org/compiere/FA/process/A_Depreciation_Workfile_Build.java
  org.adempiere.asset/src/main/java/base/org/compiere/FA/process/A_Depreciation_Workfile_BuildAbstract.java
Labels: (FAM) Fixed Asset Management, 02 bug

#1802 #1801 Bug fix Error when try validate quantity vs debit or credit sig…
  base/src/org/compiere/process/ImportBudget.java
Labels: (FIM) Financial Management, (PA) Performance Analysis and General Ledger, 02 bug

#1758 #1694 Bug the payment export custom class not work https://github.com…
  client/src/org/compiere/apps/form/VPayPrint.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WPayPrint.java
Labels: (AP) Account Payable, 02 bug

#1811 #1805, fixed bug with left and right padding, reference to issue:
  base/src/org/compiere/util/PaymentExportList.java
Labels: (FIM) Financial Management, 02 bug

#1746 #1603 Bugfix when an active is generate as expense the active not is…
  org.adempiere.asset/src/main/java/base/org/compiere/FA/model/ModelValidator.java
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetAddition.java
Labels: (FAM) Fixed Asset Management, 02 bug

#1747 #1670 Bug fix for Migration Tools not support new sequence structure …
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBConnection.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBEngine.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBEngineInterface.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBEngine_Oracle.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBEngine_Postgresql.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBObject_Sequence.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBObject_Sequence_Counter.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/Parameters.java
Labels: (MT) Migration Tools, 02 bug

#1749 #1668 Enhancement update project into payroll movement https://github…
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
Labels: (HRM) Human Resource and Payroll Management, (PM) Project Management, 01 enhancement

#1751 #1564 Add Project Model Validator to Catch multiples Events https://g…
  migration/390lts-391/03605_1532_ProjectProcessorWindow.xml
  org.adempiere.project/src/main/java/org/eevolution/model/ProjectModelValidator.java
Labels: (PM) Project Management, 01 enhancement

#1753 #1674 Enhancement synchronize account dimension for Project Phase and Project Task from Project Header
  migration/390lts-391/03850_1674_SyncDimensionForPhaseAndProject.xml
Labels: (PM) Project Management, 01 enhancement

#1757 #1685 Bug when try Send Mail Text the process throw NPE, if email not…
  base/src/org/compiere/process/SendMailText.java
Labels: (RM) Request Management, (SC) System Core, 02 bug

#1759 #1595 Enable migration script for ADempiere 3.9.0.a https://github.co…
  migration/390lts-391/03200_1429_Fixed_Error_With_Process_CopyFrom.xml
Labels: (SC) System Core, 02 bug

#1760 #1695 Enhancement adding multiple parameters to Depreciation Expense …
  migration/390lts-391/03900_1695_AddParameterToDepreciationExpense.xml
Labels: (FAM) Fixed Asset Management, 01 enhancement

#1761 #1704 Enhancement new Fixed Asset Balance report and smart browser ht…
  migration/390lts-391/03910_1704_FixedAssetBalanceSmartBrowser.xml
Labels: (FAM) Fixed Asset Management, 01 enhancement

#1763 #1714 Bug when trying launch search from the report viewer https://gi…
  client/src/org/compiere/print/Viewer.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Labels: (PF) Report Engine & Print Format, 02 bug

#1765 #1715 Bug Product importer does not set Product Class , Product Class…
  base/src/org/compiere/model/MProduct.java
Labels: (MM) Material Management, 02 bug

#1767 #1745 Bugfix When a smart field is created from view the length of th…
  base/src/org/adempiere/controller/SmallViewController.java
  base/src/org/adempiere/model/MBrowseField.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug

#1775 #1773 Bugfix org.zkoss.zk.ui.WrongValueException: Too many characters…
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WStringEditor.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug

#1776 #1774 Bugfix the Order Receipt Issue for Delivery Rule does not work when is selected https://github.com/adempiere/adempiere/issues/1774
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VOrderReceiptIssue.java
  org.eevolution.manufacturing/src/main/java/ui/zk/org/eevolution/form/WOrderReceiptIssue.java
Labels: (PMM) Planning and Manufacturing Management, 02 bug

#1777 adempiere: #1667 Error in processing PrintFormatHeader for financial …
  base/src/org/compiere/report/FinReport.java
Labels: 09 Pending Peer Review, 13 Pending Acceptance

#1813 #1812, Fixed error with parameter on getBPAccount metod of
  base/src/org/compiere/util/PaymentExportList.java
Labels: (AP) Account Payable, 02 bug

#1791 Feature/#1790 quick info for fields
  base/src/org/compiere/model/GridTab.java
  base/src/org/spin/model/I_AD_ContextInfo.java
  base/src/org/spin/model/MADContextInfo.java
  base/src/org/spin/model/X_AD_ContextInfo.java
  base/src/org/spin/util/ContextInfo.java
  client/src/org/compiere/apps/APanel.java
  client/src/org/compiere/grid/GridController.java
  doc/Dynamic-StatusBar.erm
  doc/Dynamic-StatusBar.png
  migration/390lts-391/03820_1784_Add_Dynamic_StatusBar.xml
  migration/390lts-391/03830_1784_Add_Dynamic_StatusBar_Add_Data.xml
  migration/390lts-391/03840_1790_Quick_Info_for_Fields.xml
  migration/390lts-391/03840_1790_Quick_Info_for_Fields_Data.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADTabPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (SC) System Core, (UI) User Interface Improvement, 01 enhancement, 12 Feature

#1831 #1829 Assign Project for Payment Generate from Pay Selection for Payr…
  base/src/org/compiere/model/MPaySelectionCheck.java
Labels: (HRM) Human Resource and Payroll Management, (PM) Project Management, 01 enhancement

#1822 patch in ProcessUtil.startScriptProcess when error msg startsWith "@Error@"
  base/src/org/adempiere/util/ProcessUtil.java
Labels: 02 bug

#1825 ignore eclipse subproject RemoteSystemsTempFiles
  .gitignore
  RemoteSystemsTempFiles/.project
Labels: 02 bug

#1641 #1632: SQL Error when a commission is running for orders
  base/src/org/compiere/model/MCommissionRun.java
  db/ddlutils/oracle/functions/linenetamtrealorderline.sql
  db/ddlutils/postgresql/functions/linenetamtrealorderline.sql
  migration/390lts-391/03440_1465_Commission_SQLFunctionLineNetAmt.xml
Labels: (COM) Commission, 13 Pending Acceptance, 14 Waiting for User Changes

#1740 Feature/allocate inmediate enhance
  adempiere.iml
  base/src/org/compiere/model/I_C_DocType.java
  base/src/org/compiere/model/I_C_Invoice.java
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/X_C_DocType.java
  base/src/org/compiere/model/X_C_Invoice.java
  migration/390lts-391/03690_1370_InvoiceAllocateInmediate.xml
Labels: (AP) Account Payable, (AR) Account Receivable, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance, 14 Waiting for User Changes

#1673 Feature/1656 asset split document
  base/src/org/compiere/model/I_A_Asset.java
  base/src/org/compiere/model/I_A_Asset_Split.java
  base/src/org/compiere/model/X_A_Asset.java
  base/src/org/compiere/model/X_A_Asset_Split.java
  migration/390lts-391/03790_1656_FixedAssetView.xml
  migration/390lts-391/03800_1656_FixedAssetsBrowser.xml
  migration/390lts-391/03810_1656_AssetSplitWindow.xml
  migration/390lts-391/03820_1656_AssetSplitBrowser.xml
  org.adempiere.asset/src/main/java/base/org/compiere/FA/process/FixedAssetSplit.java
  org.adempiere.asset/src/main/java/base/org/compiere/FA/process/FixedAssetSplitAbstract.java
  org.adempiere.asset/src/main/java/base/org/compiere/acct/Doc_AssetSplit.java
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetChange.java
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetProduct.java
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetSplit.java
  org.adempiere.asset/src/main/java/base/org/compiere/model/MDepreciationExp.java
  org.adempiere.asset/src/main/java/base/org/compiere/model/MDepreciationWorkfile.java
Labels: (FAM) Fixed Asset Management, 01 enhancement, 09 Pending Peer Review

#1766 #1717 Bug fix when a Request has a feedback using result field and No…
  base/src/org/compiere/model/MClient.java
  base/src/org/compiere/model/MStore.java
  base/src/org/compiere/process/ServerProcessCtl.java
  client/src/org/compiere/apps/ProcessCtl.java
  serverApps/src/main/servlet/org/compiere/www/WProcessCtl.java
Labels: (RM) Request Management, 02 bug, 14 Waiting for User Changes

#1778 #1741: Deleted recent items causes NPE (only in Swing), reference to
  base/src/org/compiere/model/MRecentItem.java
  client/src/org/compiere/grid/tree/VTreePanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java
Labels: (UI) User Interface Improvement, 02 bug

#1832 #1830 Bug Notification Workflow doesn't parse context variables defin…
  base/src/org/compiere/wf/MWFActivity.java
Labels: (BPM) Workflow Engine, 02 bug

#1597 adempiere:#1560 Commission for complete payments: commissions from pa…
  db/ddlutils/oracle/functions/maxpaydate.sql
  migration/390lts-391/03740_1560_Commission_from_past_months.xml
Labels: (COM) Commission, 02 bug, 16 Conflict with Trunk

#1840 #1839, Add old compatibility to Context info for window, reference to
  base/src/org/spin/model/MADContextInfo.java
Labels: (UI) User Interface Improvement, 01 enhancement

#1601 this implements issue #1577 - a pdf viewer using icepdf
  .classpath
  base/src/org/adempiere/pdf/viewer/PDFViewerBean.java
Labels: (SC) System Core, (UI) User Interface Improvement, 01 enhancement, 14 Waiting for User Changes

#1843 Feature/#1842 add ci travis support
  .travis.yml
Labels: (CI) Code Improvement or Optimization, 01 enhancement
