Repository adempiere/adempiere, pull requests merged in 2018-09, with the labels that each got.

#1945 adempiere: #1943 ErrorgetDefault()ForKeyColumns
  base/src/org/compiere/model/GridField.java
Labels: (SC) System Core, 02 bug

#1966 #1604 Enhancement allows define the accounting by payroll from payrol…
  base/src/org/eevolution/model/I_HR_Concept_Acct.java
  base/src/org/eevolution/model/X_HR_Concept_Acct.java
  migration/390lts-391/03770_1604_AddPayrollForConceptAccount.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/DocLine_Payroll.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRConcept.java
Labels: (HRM) Human Resource and Payroll Management, (PA) Performance Analysis and General Ledger, 01 enhancement

#1974 #1451 Add additional condition to an Standard Request https://github.…
  migration/390lts-391/03420_1451_AddAdditionalConditionToStandardRequestType.xml
Labels: (PM) Project Management, 01 enhancement

#1898 Feature/adempiere1669 statement of accounts
  base/src/org/compiere/model/I_T_ReportStatement.java
  base/src/org/compiere/model/X_T_ReportStatement.java
  base/src/org/compiere/report/FinStatement.java
  base/src/org/compiere/report/FinStatementAbstract.java
  migration/390lts-391/03930_1669_StatementOfAccount.xml
Labels: (AC) Accounting, 01 enhancement, 09 Pending Peer Review

#1893 #1891 Fixed error with role access for process Role Access Update
  base/src/org/compiere/model/MRole.java
  base/src/org/compiere/process/RoleAccessUpdate.java
  base/src/org/compiere/process/RoleAccessUpdateAbstract.java
  migration/390lts-391/03935_1744_AddDashboardAccesTab.xml
Labels: (SE) Security, (UI) User Interface Improvement, 02 bug, 14 Waiting for User Changes

#2038 #2037 Correct Eclipse classpath
  .classpath
Labels: 02 bug, 08 IDE

#1629 #1237 Smart Browser Sorting and Browsing
  client/src/org/eevolution/grid/VBrowserTable.java
Labels: (SB) Smart Browser, (UI) User Interface Improvement, 02 bug, 09 Pending Peer Review

#2009 #1088 XML Script and Fix Sequence number
  migration/390lts-391/03930_1088_Add_Column_IsQuickEntry.xml
Labels: 12 Feature

#2032 #2030 Listener missing from ZK ui for Small View Controller
  base/src/org/adempiere/controller/SmallViewController.java
  client/src/org/eevolution/grid/Browser.java
Labels: (UI) User Interface Improvement, 02 bug

#1956 remove obsolete jpedal.jar - it was replaced with icepdf
  JasperReports/.classpath
  adempiere.iml
  base/.classpath
  org.adempiere.crm/.classpath
  org.adempiere.crm/.project
  org.adempiere.pos/.classpath
  org.adempiere.pos/.idea/modules/adempierePOS.iml
  org.adempiere.pos/.settings/org.eclipse.jdt.core.prefs
  org.adempiere.pos/adempierePOS.iml
  org.adempiere.webservice/.classpath
  org.eevolution.freight/.classpath
  org.eevolution.freight/.project
  tools/.classpath
  zkwebui/.classpath
Labels: 14 Waiting for User Changes
