Repository adempiere/adempiere, pull requests merged in 2018-12, with the labels that each got.

#2154 #2150, Fixes error with zoom, reference to issue:
  client/src/org/compiere/apps/APanel.java
Labels: (UI) User Interface Improvement, 02 bug

#2157 Fixed error with zoom with column SQL
  base/src/org/adempiere/model/GenericZoomProvider.java
  base/src/org/adempiere/model/ZoomMetaInfo.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug

#2166 #2165, Add new approach for Copy role process, reference to issue:
  base/src/org/compiere/process/CopyRole.java
  base/src/org/compiere/process/CopyRoleAbstract.java
  serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitor.java
Labels: (SE) Security, 02 bug

#2168 #2167, Add enhancement for allows file types, reference to issue:
  base/src/org/compiere/model/MAttachment.java
  base/src/org/compiere/util/MimeType.java
  client/src/org/compiere/apps/Attachment.java
  migration/390lts-391/04405_2167_Allows_FileTypes.xml
Labels: (SC) System Core, (SE) Security, 01 enhancement

#2170 #2169, Improve default feature for XML parser and builder, reference to
  base/src/com/akunagroup/uk/postcode/AddressLookup.java
  base/src/org/adempiere/pipo/PackIn.java
  base/src/org/adempiere/pipo/PackInHandler.java
  base/src/org/adempiere/process/rpl/XMLHelper.java
  base/src/org/compiere/model/MArchive.java
  base/src/org/compiere/model/MAttachment.java
  base/src/org/compiere/process/MigrationFromXML.java
  base/src/org/compiere/util/ImpExpUtil.java
  base/src/org/spin/util/XMLUtils.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADServiceImpl.java
  webCM/src/main/servlet/org/compiere/cm/xml/XSLTProcessor.java
Labels: (SC) System Core, (SE) Security, 01 enhancement

#2172 #2171, Remove old form of menu, reference to issue:
  client/src/org/compiere/apps/form/VSQLProcess.java
  migration/390lts-391/04407_2171_Remove_Old_Forms.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WSQLProcess.java
Labels: (SC) System Core, (SE) Security, 01 enhancement

#2160 Feature/#2159 add export surrogate key
  base/src/org/spin/process/ExportSurrogateKeyToMigration.java
  base/src/org/spin/process/ExportSurrogateKeyToMigrationAbstract.java
  migration/390lts-391/04410_ExportSurrogateKey_Process.xml
Labels: (SA) System Administrator, (SC) System Core, 01 enhancement

#2152 Bugfix/#1888 not displayed embedded tabs
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridTabRowRenderer.java
Labels: (UI) User Interface Improvement, 02 bug, 10 Reviewed by Peer, 14 Waiting for User Changes

#2116 #2109 Add initial values and metadata for App registration
  base/src/org/spin/model/I_AD_AppRegistration.java
  base/src/org/spin/model/I_AD_AppRegistration_Para.java
  base/src/org/spin/model/I_AD_AppSupport.java
  base/src/org/spin/model/MADAppRegistration.java
  base/src/org/spin/model/MADAppRegistrationPara.java
  base/src/org/spin/model/MADAppSupport.java
  base/src/org/spin/model/X_AD_AppRegistration.java
  base/src/org/spin/model/X_AD_AppRegistration_Para.java
  base/src/org/spin/model/X_AD_AppSupport.java
  base/src/org/spin/process/TestAppRegistration.java
  base/src/org/spin/process/TestAppRegistrationAbstract.java
  base/src/org/spin/util/support/AppRegistrationEvent.java
  base/src/org/spin/util/support/AppRegistrationEventListener.java
  base/src/org/spin/util/support/AppSupportHandler.java
  base/src/org/spin/util/support/IAppSupport.java
  base/src/org/spin/util/support/mq/AbstractMessageQueue.java
  base/src/org/spin/util/support/mq/ActiveMQ.java
  base/src/org/spin/util/support/mq/IMessageQueue.java
  base/src/org/spin/util/support/webdav/IWebDav.java
  base/src/org/spin/util/support/webdav/IWebDavResource.java
  doc/org.spin/App-Registration.erm
  doc/org.spin/App-Registration.png
  docs/App-Registration.png
  migration/390lts-391/04400_2109_Add_App_Registration.xml
  migration/390lts-391/04410_2109_Add_App_Registration_Data.xml
Labels: (IO) Input/Output, 01 enhancement, 09 Pending Peer Review

#2164 #2163 Errors in ProjectIssue
  org.adempiere.project/src/main/java/org/compiere/model/MProjectIssue.java
  org.adempiere.project/src/main/java/org/compiere/process/ProjectIssue.java
Labels: (PM) Project Management, 02 bug, 09 Pending Peer Review

#2174 Remove orphan records out of migration steps
  migration/390lts-391/03260_1389_AddNewColumnsProject.xml
  migration/390lts-391/03760_1615_PriceListEntries.xml
Labels: (RLS) Release

#2175 Fix statements in Migration XML scripts for Oracle support
  migration/390lts-391/03530_AddPaymentBankAccountToPaySelecectionView.xml
  migration/390lts-391/03820_1784_Add_Dynamic_StatusBar.xml
  migration/390lts-391/03840_1790_Quick_Info_for_Fields.xml
  migration/390lts-391/03930_1669_StatementOfAccount.xml
  migration/390lts-391/03962_1555_RenameRelatedPayment.xml
  migration/390lts-391/04120_1769_Add_Default_Config.xml
  migration/390lts-391/04370_1697_AddWindowFieldDefinition.xml
Labels: (RLS) Release

#2177 Remove Oracle-incompatible SQL statement for new Tree functionality
  base/src/org/compiere/model/MTree.java
Labels: (RLS) Release

#2182 #2079, Remove Duplicated XML for Dashboard Access, reference to issue:
  base/src/org/compiere/model/MRole.java
  migration/390lts-391/03935_1744_AddDashboardAccesTab.xml
  migration/390lts-391/03940_1744_AddDashboardAccesTab.xml
Labels: (SC) System Core, (SE) Security, 02 bug

#2181 #2069, Remove bad constraint for C_BPartner_Location on M_Movement,
  migration/390lts-391/04420_2069_Drop_Bad_Constraint.xml
Labels: (MM) Material Management, (SC) System Core, 02 bug

#2155 Error with reversal production
  base/src/org/compiere/model/MProduction.java
  base/src/org/compiere/model/MProductionBatch.java
Labels: (PLH) Production Light, 02 bug

#2179 Update Oracle JDBC Driver to 18.3 (ojdbc8.jar)
  tools/build.xml
  tools/lib/ojdbc6.jar
  tools/lib/oracle.jar
Labels: (RLS) Release

#2096 StackOverFlow Error in WAcctViewer
  migration/390lts-391/04380_2095_KeyColumnsAsID.xml
Labels: (SC) System Core, 02 bug, 10 Reviewed by Peer, 14 Waiting for User Changes

#2187 #2186, fix classpath for project on Eclipse IDE, reference to issue:
  .classpath
Labels: 02 bug, 08 IDE

#2190 #2189 Compiler error due to package /tools/lib/xml-apis.jar
  .classpath
  JasperReports/build.xml
  adempiere.iml
  base/ADempiere.launch
  org.adempiere.pos/.idea/modules/adempierePOS.iml
  org.adempiere.pos/adempierePOS.iml
  tomcat/conf/catalina.properties
  tools/.classpath
  tools/lib/xml-apis.jar
Labels: 02 bug, 08 IDE

#2212 #2165, change separator for support others OS, reference to issue:
  serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitor.java
Labels: (SE) Security, 02 bug

#2199 #2198, Fixed client filter for import budget, reference to issue:
  base/src/org/compiere/process/ImportBudget.java
Labels: (PA) Performance Analysis and General Ledger, 02 bug

#2203 WTrialBalance ORG_ID should not be mandatory by default
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WTrialBalance.java
Labels: (AC) Accounting, 01 enhancement

#2201 #1649, Improve PO create from Sales Orders process
  base/src/org/compiere/process/OrderPOCreate.java
  base/src/org/compiere/process/OrderPOCreateAbstract.java
Labels: (PO) Purchase Management, (SO) Sales Management, 01 enhancement

#2227 #1649, change bad relation for Order PO create, reference to issue:
  base/src/org/compiere/process/OrderPOCreate.java
Labels: (PO) Purchase Management, 02 bug

#2238 #421 Prevent unnecessary error on switch from grid to form view
  client/src/org/compiere/grid/GridController.java
Labels: (UI) User Interface Improvement, 02 bug

#2235 adempiere #2031 Field LandedCostType in LandedCost
  base/src/org/compiere/model/MInvoiceLine.java
Labels: (CM) Costing Management, 01 enhancement
