Repository adempiere/adempiere, pull requests merged in 2018-10, with the labels that each got.

#1862 #1861 Add support to direct load flag in packin import, reference to
  base/src/org/adempiere/pipo/handler/AdElementHandler.java
  base/src/org/adempiere/pipo/handler/BrowseElementHandler.java
  base/src/org/adempiere/pipo/handler/BrowseFieldElementHandler.java
  base/src/org/adempiere/pipo/handler/ColumnElementHandler.java
  base/src/org/adempiere/pipo/handler/DataElementHandler.java
  base/src/org/adempiere/pipo/handler/DynValRuleElementHandler.java
  base/src/org/adempiere/pipo/handler/EntityTypeElementHandler.java
  base/src/org/adempiere/pipo/handler/FieldElementHandler.java
  base/src/org/adempiere/pipo/handler/FieldGroupElementHandler.java
  base/src/org/adempiere/pipo/handler/FormElementHandler.java
  base/src/org/adempiere/pipo/handler/ImpFormatElementHandler.java
  base/src/org/adempiere/pipo/handler/ImpFormatRowElementHandler.java
  base/src/org/adempiere/pipo/handler/MenuElementHandler.java
  base/src/org/adempiere/pipo/handler/MessageElementHandler.java
  base/src/org/adempiere/pipo/handler/ModelValidatorElementHandler.java
  base/src/org/adempiere/pipo/handler/PreferenceElementHandler.java
  base/src/org/adempiere/pipo/handler/PrintFormatElementHandler.java
  base/src/org/adempiere/pipo/handler/PrintFormatItemElementHandler.java
  base/src/org/adempiere/pipo/handler/PrintPaperElementHandler.java
  base/src/org/adempiere/pipo/handler/ProcessElementHandler.java
  base/src/org/adempiere/pipo/handler/ProcessParaElementHandler.java
  base/src/org/adempiere/pipo/handler/ReferenceElementHandler.java
  base/src/org/adempiere/pipo/handler/ReferenceListElementHandler.java
  base/src/org/adempiere/pipo/handler/ReferenceTableElementHandler.java
  base/src/org/adempiere/pipo/handler/ReportViewColElementHandler.java
  base/src/org/adempiere/pipo/handler/ReportViewElementHandler.java
  base/src/org/adempiere/pipo/handler/RoleElementHandler.java
  base/src/org/adempiere/pipo/handler/TabElementHandler.java
  base/src/org/adempiere/pipo/handler/TableElementHandler.java
  base/src/org/adempiere/pipo/handler/TaskElementHandler.java
  base/src/org/adempiere/pipo/handler/ViewColumnElementHandler.java
  base/src/org/adempiere/pipo/handler/ViewDefinitionElementHandler.java
  base/src/org/adempiere/pipo/handler/ViewElementHandler.java
  base/src/org/adempiere/pipo/handler/WindowElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowNodeElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowNodeNextConditionElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowNodeNextElementHandler.java
Labels: (MT) Migration Tools, 02 bug, 09 Pending Peer Review

#1971 #1646 Add new window for Project Info
  migration/390lts-391/03779_1646_ProjectInfo.xml
Labels: (PM) Project Management, 01 enhancement

#1783 #1616 Add Smart Browse for collect invoice of business partner
  base/src/org/spin/process/PaymentCreateFromInvoice.java
  base/src/org/spin/process/PaymentCreateFromInvoiceAbstract.java
  migration/390lts-391/03901_1616_Add_Collect_SB_For_Sales.xml
Labels: (FIM) Financial Management, 01 enhancement

#1911 #1658 Change data access level of tables HR_ListType, HR_List, HR_ListVersion and HR_ListLine to ALL
  migration/390lts-391/04000_1658_PayrollList_DataAccessLevel_ALL.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement, 09 Pending Peer Review

#1827 #1772 New feature for dynamic tree
  base/src/org/adempiere/process/ASPGenerateLevel.java
  base/src/org/compiere/cm/WebProjectDeploy.java
  base/src/org/compiere/model/GridTab.java
  base/src/org/compiere/model/I_AD_Tree.java
  base/src/org/compiere/model/MActivity.java
  base/src/org/compiere/model/MBPartner.java
  base/src/org/compiere/model/MCampaign.java
  base/src/org/compiere/model/MClient.java
  base/src/org/compiere/model/MCommissionRun.java
  base/src/org/compiere/model/MElementValue.java
  base/src/org/compiere/model/MMenu.java
  base/src/org/compiere/model/MOrg.java
  base/src/org/compiere/model/MProduct.java
  base/src/org/compiere/model/MRole.java
  base/src/org/compiere/model/MSalesRegion.java
  base/src/org/compiere/model/MTable.java
  base/src/org/compiere/model/MTree.java
  base/src/org/compiere/model/MTree_Base.java
  base/src/org/compiere/model/MTree_Node.java
  base/src/org/compiere/model/MTree_NodeBP.java
  base/src/org/compiere/model/MTree_NodeCMC.java
  base/src/org/compiere/model/MTree_NodeCMS.java
  base/src/org/compiere/model/MTree_NodeMM.java
  base/src/org/compiere/model/MTree_NodePR.java
  base/src/org/compiere/model/MTree_NodeU1.java
  base/src/org/compiere/model/MTree_NodeU2.java
  base/src/org/compiere/model/MTree_NodeU3.java
  base/src/org/compiere/model/MTree_NodeU4.java
  base/src/org/compiere/model/MWebProject.java
  base/src/org/compiere/model/PO.java
  base/src/org/compiere/model/X_AD_Tree.java
  base/src/org/compiere/process/TreeMaintenance.java
  base/src/org/compiere/report/MReportTree.java
  base/src/org/compiere/util/Login.java
  client/src/org/compiere/apps/form/TreeMaintenance.java
  client/src/org/compiere/grid/GridController.java
  client/src/org/compiere/grid/tree/VTreePanel.java
  migration/390lts-391/03800_1772_Add_Dynamic_Tree_Contribution.xml
  org.adempiere.project/src/main/java/org/compiere/model/MProject.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADServiceImpl.java
  serverApps/src/main/servlet/org/compiere/www/WMenu.java
  webCM/src/main/servlet/org/compiere/cm/utils/TreeXML.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WTreeMaintenance.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/SimpleTreeModel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADTabPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADTreePanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/MenuPanel.java
Labels: (SC) System Core, (UI) User Interface Improvement, 01 enhancement

#2008 #2007 Avoid to set itself as tax parent
  base/src/org/compiere/model/MTax.java
Labels: (TM) Tax Management, 02 bug, 10 Reviewed by Peer

#1910 #1907 Add account dimension for Accounting Report
  migration/390lts-391/04010_1907_AddDimensionToAccountingReport.xml
Labels: (PA) Performance Analysis and General Ledger, 01 enhancement

#1914 #1912 Bug fixes for landedCost and LandedCostAllocation
  base/src/org/compiere/process/LandedCostDistribute.java
Labels: (CM) Costing Management, (PO) Purchase Management, 02 bug, 09 Pending Peer Review

#2036 #2034 Add Icon Image for any column defined as Button
  base/src/org/compiere/model/GridField.java
  base/src/org/compiere/model/GridFieldVO.java
  base/src/org/compiere/model/I_AD_Column.java
  base/src/org/compiere/model/I_AD_Field.java
  base/src/org/compiere/model/X_AD_Column.java
  base/src/org/compiere/model/X_AD_Field.java
  client/src/org/compiere/grid/ed/VEditorFactory.java
  db/ddlutils/oracle/views/AD_FIELD_V.sql
  db/ddlutils/oracle/views/AD_FIELD_VT.sql
  db/ddlutils/postgresql/views/AD_FIELD_V.sql
  db/ddlutils/postgresql/views/AD_FIELD_VT.sql
  migration/390lts-391/03920_1088_Add_Column_IsQuickEntry.xml
  migration/390lts-391/04050_2034_AddIconForAnyColumnDefinedAsButton.xml
  migration/390lts-391/04060_2034_AddIconForAnyColumnDefinedAsButton.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WebEditorFactory.java
Labels: (AD) Application Dictionary, (UI) User Interface Improvement, 01 enhancement, 09 Pending Peer Review

#2012 #1836 Generate surrogate key
  base/src/org/eevolution/process/GenerateSurrogateKeys.java
  db/ddlutils/oracle/functions/getUUID.sql
  db/ddlutils/postgresql/functions/getUUID.sql
  migration/390lts-391/04350_1836_AddSurrogateKeyFromFunction.xml
Labels: (MT) Migration Tools, 02 bug

#1973 #1869 Add report for Payroll Movement
  migration/390lts-391/03970_1869_PayrollMovementReport.xml
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement, 10 Reviewed by Peer

#1850 #1769 Restore password login
  base/src/org/compiere/Adempiere.java
  base/src/org/compiere/model/I_AD_ClientInfo.java
  base/src/org/compiere/model/MUser.java
  base/src/org/compiere/model/X_AD_ClientInfo.java
  base/src/org/spin/model/I_AD_Token.java
  base/src/org/spin/model/I_AD_TokenDefinition.java
  base/src/org/spin/model/MADToken.java
  base/src/org/spin/model/MADTokenDefinition.java
  base/src/org/spin/model/X_AD_Token.java
  base/src/org/spin/model/X_AD_TokenDefinition.java
  base/src/org/spin/util/GeneratePassword.java
  base/src/org/spin/util/ITokenGenerator.java
  base/src/org/spin/util/TokenGenerator.java
  base/src/org/spin/util/TokenGeneratorHandler.java
  client/src/org/compiere/apps/ALogin.java
  migration/390lts-391/03880_1769_Add_Table_AD_Token.xml
  migration/390lts-391/03890_1769_Add_MailTemplate.xml
  migration/390lts-391/03900_1769_Add_Message_ForgotPassword.xml
  migration/390lts-391/04120_1769_Add_Default_Config.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/NewPassPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/PassResetPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/LoginWindow.java
Labels: (SE) Security, (UI) User Interface Improvement, 01 enhancement, 09 Pending Peer Review

#2035 #1953 Add CSV as report output type
  base/src/org/compiere/model/X_AD_PInstance.java
  migration/390lts-391/4060_1953_6720_ADD_CSV_Support_To_Report_View.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Labels: (PF) Report Engine & Print Format, 01 enhancement, 12 Feature

#1981 #1562 Commission for complete payments
  migration/390lts-391/03755_1562_Commission_AllowDaysDueFromInvoices-Correction.xml
Labels: (COM) Commission, 09 Pending Peer Review

#1987 #1985 Add an action in Project Task to generate a Sales Order
  base/src/org/compiere/model/I_C_Phase.java
  base/src/org/compiere/model/I_C_ProjectLine.java
  base/src/org/compiere/model/I_C_ProjectPhase.java
  base/src/org/compiere/model/I_C_ProjectTask.java
  base/src/org/compiere/model/I_C_Task.java
  base/src/org/compiere/model/MResource.java
  base/src/org/compiere/model/X_C_Phase.java
  base/src/org/compiere/model/X_C_ProjectLine.java
  base/src/org/compiere/model/X_C_ProjectPhase.java
  base/src/org/compiere/model/X_C_ProjectTask.java
  base/src/org/compiere/model/X_C_Task.java
  base/src/org/eevolution/model/MPPOrder.java
  migration/390lts-391/03870_1676_GenerateMOFromProjectLine.xml
  migration/390lts-391/03890_1985_GenerateSalesOrderfromProject.xml
  org.adempiere.project/src/main/java/org/compiere/model/CalloutProject.java
  org.adempiere.project/src/main/java/org/compiere/model/MProjectLine.java
  org.adempiere.project/src/main/java/org/compiere/model/MProjectPhase.java
  org.adempiere.project/src/main/java/org/compiere/model/MProjectTask.java
  org.adempiere.project/src/main/java/org/compiere/process/ProjectGenOrder.java
  org.adempiere.project/src/main/java/org/compiere/process/ProjectPhaseGenOrder.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProjectGenerateManufacturingOrder.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProjectGenerateManufacturingOrderAbstract.java
Labels: (PM) Project Management, 01 enhancement, 10 Reviewed by Peer, 14 Waiting for User Changes

#1992 #1991 Pay Selection not returning getDoc_User_ID, always returns 0
  base/src/org/compiere/model/MPaySelection.java
Labels: (AP) Account Payable, (BPM) Workflow Engine, 02 bug

#2043 #1638 Import Business Partner when a contact with same email exists
  base/src/org/compiere/process/ImportBPartner.java
Labels: (AP) Account Payable, (AR) Account Receivable, 02 bug

#1964 #1955 Exception in CTabbedPane bugfix
  base/src/org/compiere/swing/CTabbedPane.java
Labels: (SC) System Core, 02 bug, 09 Pending Peer Review

#1994 #1993 Add Email Recipient Into Node for Supervisor of Owner Document …
  base/src/org/compiere/model/X_AD_WF_Node.java
  base/src/org/compiere/wf/MWFActivity.java
  migration/390lts-391/04040_1993_AddEmailRecipientIntoNodeForSupervisor.xml
Labels: (BPM) Workflow Engine, 01 enhancement, 14 Waiting for User Changes

#2018 #1990 Info windows: show newest order, invoice, ... on top
  client/src/org/compiere/apps/search/InfoInOut.java
  client/src/org/compiere/apps/search/InfoInvoice.java
  client/src/org/compiere/apps/search/InfoOrder.java
  client/src/org/compiere/apps/search/InfoPayment.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoInOutPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoInvoicePanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoOrderPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoPaymentPanel.java
Labels: (UI) User Interface Improvement, 01 enhancement, 09 Pending Peer Review, 12 Feature

#2044 #1993, Complement improvement for WF Activity EMail send for Supervisor
  base/src/org/compiere/wf/MWFActivity.java
Labels: (BPM) Workflow Engine, 01 enhancement

#1950 #1938 Changed the Default Logic in AD_MigrationStep
  migration/390lts-391/04030_1928_ErrorSettingSeqNoInAD_MigrationStep.xml
Labels: (MT) Migration Tools, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance

#2048 adempiere #2047 Change name of XML 4060 according to standard
  migration/390lts-391/04070_1953_6720_ADD_CSV_Support_To_Report_View.xml
Labels: 01 enhancement

#1902 #1699 Add automatic reconciliation
  base/src/org/compiere/impexp/OFXBankStatementHandler.java
  base/src/org/compiere/model/MBankStatementLine.java
  base/src/org/compiere/model/MBankStatementLoader.java
  base/src/org/compiere/model/MBankStatementMatcher.java
  base/src/org/compiere/process/ImportBankStatement.java
  base/src/org/compiere/process/ImportBankStatementAbstract.java
  base/src/org/spin/model/I_C_BankMatcher.java
  base/src/org/spin/model/MCBankMatcher.java
  base/src/org/spin/model/X_C_BankMatcher.java
  base/src/org/spin/util/impexp/BankStatementHandler.java
  base/src/org/spin/util/impexp/BankTransactionAbstract.java
  base/src/org/spin/util/impexp/GenericBankMatcher.java
  base/src/org/spin/util/impexp/GenericMT940BankStatementLoader.java
  base/src/org/spin/util/impexp/GenericQIFBankStatementLoader.java
  base/src/org/spin/util/impexp/GenericQIFBankTransaction.java
  base/src/org/spin/util/impexp/MT940BankTransaction.java
  base/src/org/spin/util/impexp/QIFBankTransaction.java
  base/src/org/spin/util/impexp/ReferenceNoLeftLike_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoLikeWithImport_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoLikeWithPayment_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoLike_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoRightLike_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNo_BankMatcher.java
  base/src/org/spin/util/impexp/TestMT940BankTransaction.java
  base/src/org/spin/util/impexp/TrxDataInterface.java
  client/src/org/spin/apps/form/BankStatementMatchController.java
  client/src/org/spin/apps/form/VBankStatementMatch.java
  migration/390lts-391/03980_1702_Add_Generic_BankMatcher.xml
  migration/390lts-391/03990_1699_Add_BankStatementMatch_Form.xml
  migration/390lts-391/04000_1706_Add_BankMatch_Link.xml
  zkwebui/WEB-INF/src/org/spin/apps/form/WBankStatementMatch.java
Labels: (AP) Account Payable, (AR) Account Receivable, (FIM) Financial Management, 01 enhancement, 17 Waiting for Information

#2050 #2049 Error Statement Account when sending the account parameters
  base/src/org/compiere/report/FinStatement.java
Labels: (AC) Accounting, (FIM) Financial Management, 01 enhancement

#1972 #1656 New Asset Split Document
  migration/390lts-391/03811_1656_AddingProcessedOnToA_Asset_Split.xml
Labels: (FAM) Fixed Asset Management, 01 enhancement

#2054 Fix for #2053. Add FileName parameter to MigrationLoader.
  base/src/org/adempiere/process/MigrationLoader.java
  base/src/org/compiere/process/MigrationFromXMLAbstract.java
Labels: 02 bug, 09 Pending Peer Review

#2052 #2051 ImportBPartner.java false reference to a table
  base/src/org/compiere/process/ImportBPartner.java
Labels: 02 bug

#1927 #1925 Deleted migration step 890 from 03605_1532...xml
  migration/390lts-391/03605_1532_ProjectProcessorWindow.xml
Labels: 09 Pending Peer Review, 14 Waiting for User Changes

#1951 #1937 Corrected the tool tip and translation for the Log Migration Script Message
  migration/390lts-391/04040_1937_ChangeLogMigrationToolTip.xml
Labels: (MT) Migration Tools, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance

#1947 #1944 Deal with special case where a Y/N field has been added to a populated table.
  base/src/org/compiere/model/GridTable.java
Labels: (SC) System Core, 02 bug, 10 Reviewed by Peer

#1984 #1555 BankTransfer: Voiding PaymentsBankTransfer
  base/src/org/compiere/model/I_C_Payment.java
  base/src/org/compiere/model/MPaySelectionCheck.java
  base/src/org/compiere/model/MPayment.java
  base/src/org/compiere/model/X_C_Payment.java
  base/src/org/eevolution/process/BankTransfer.java
  base/src/org/eevolution/process/BankTransferAbstract.java
  migration/390lts-391/03961_1555_DeleteIsVoidRelatedDocument.xml
  migration/390lts-391/03962_1555_RenameRelatedPayment.xml
Labels: (AP) Account Payable, (AR) Account Receivable, 01 enhancement, 09 Pending Peer Review

#1915 #1912 Landed cost allocation create cost detail, Create costdetail when completing the invoice
  base/src/org/compiere/model/MInvoice.java
Labels: (CM) Costing Management, (PO) Purchase Management, 02 bug, 09 Pending Peer Review

#1917 #1916 ReverseAccrual generates wrong seqNo in costdetail
  base/src/org/adempiere/engine/AbstractCostingMethod.java
Labels: (CM) Costing Management, 02 bug, 09 Pending Peer Review

#1920 Bugfix/invoice reverse accrual costdetail match inv
  base/src/org/adempiere/engine/AbstractCostingMethod.java
  base/src/org/adempiere/engine/AverageInvoiceCostingMethod.java
  base/src/org/compiere/model/I_M_CostDetail.java
  base/src/org/compiere/model/MCostDetail.java
  base/src/org/compiere/model/MInOut.java
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/X_M_CostDetail.java
  client/src/org/compiere/apps/form/Match.java
  migration/390lts-391/04000_1912_Table_M_CostDetail_AddColumns.xml
Labels: (CM) Costing Management, 02 bug, 09 Pending Peer Review

#2060 #2059 Process Parameters: NPE for reference type Search
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WSearchEditor.java
Labels: (SC) System Core, 02 bug, 09 Pending Peer Review

#2063 #1975 ZK Process Panel KeyListener remains active when window is not visible.
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
Labels: 02 bug, 09 Pending Peer Review

#2055 Feature/#1697 add new style field condition
  base/src/org/compiere/model/GridField.java
  base/src/org/compiere/model/GridFieldVO.java
  base/src/org/spin/model/I_AD_FieldCondition.java
  base/src/org/spin/model/I_AD_FieldDefinition.java
  base/src/org/spin/model/MADFieldCondition.java
  base/src/org/spin/model/MADFieldDefinition.java
  base/src/org/spin/model/X_AD_FieldCondition.java
  base/src/org/spin/model/X_AD_FieldDefinition.java
  base/src/org/spin/util/FieldCondition.java
  base/src/org/spin/util/FieldDefinition.java
  db/ddlutils/oracle/views/AD_FIELD_V.sql
  db/ddlutils/oracle/views/AD_FIELD_VT.sql
  db/ddlutils/postgresql/views/AD_FIELD_V.sql
  db/ddlutils/postgresql/views/AD_FIELD_VT.sql
  doc/org.spin/ChangeStyleDefinition.erm
  doc/org.spin/ChangeStyleDefinition.png
  migration/390lts-391/04360_1697_AddColumnFieldDefinition.xml
  migration/390lts-391/04370_1697_AddWindowFieldDefinition.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridTabRowRenderer.java
Labels: (UI) User Interface Improvement, 01 enhancement

#1946 #1935 Add IsDefault to AD_User_Roles.
  base/src/org/compiere/model/I_AD_User_Roles.java
  base/src/org/compiere/model/MUserRoles.java
  base/src/org/compiere/model/X_AD_User_Roles.java
  base/src/org/compiere/util/Login.java
  migration/390lts-391/04020_1935_AddDefaultFlagtoAD_User_Roles.xml
  migration/390lts-391/04021_1935_AddDefaultFlagtoAD_User_Roles.xml
Labels: (UI) User Interface Improvement, 01 enhancement, 10 Reviewed by Peer

#2065 #1671 Fixed Asset with zero period depreciation cannot be added for control
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetAddition.java
Labels: (FAM) Fixed Asset Management, 02 bug

#2080 #2079 Problem with Dashboard access when try execute role access upda…
  base/src/org/compiere/model/MRole.java
Labels: (SE) Security, 02 bug

#2076 #2074 Error launching jasper reports print format from any tab
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (PF) Report Engine & Print Format, (UI) User Interface Improvement, 02 bug, 10 Reviewed by Peer

#2084 #2083, change log level for migration apply, reference to issue:
  base/src/org/compiere/model/GridField.java
  base/src/org/compiere/process/MigrationStepApply.java
Labels: (CI) Continuous Integration, 01 enhancement

#2088 #421 Ensures embedded tabs are updated
  client/src/org/compiere/grid/GridController.java
Labels: 02 bug, 10 Reviewed by Peer

#2090 #2089 Add support to Time on Smart Browser
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
  zkwebui/WEB-INF/src/org/eevolution/grid/WBrowserListItemRenderer.java
Labels: (UI) User Interface Improvement, 02 bug, 10 Reviewed by Peer

#2066 #2062 Prevent duplicate key errors when running processes with saved parameters.
  base/src/org/compiere/apps/ProcessController.java
Labels: (CI) Code Improvement or Optimization, 02 bug, 09 Pending Peer Review

#2087 #431 Fixes the way totals are grouped in the report dataengine.
  base/src/org/compiere/print/DataEngine.java
  base/src/org/compiere/print/PrintDataColumn.java
  base/src/org/compiere/print/PrintDataGroup.java
Labels: (PF) Report Engine & Print Format, 02 bug, 09 Pending Peer Review

#2108 #2107 Validate Login User for Password reset
  base/src/org/spin/util/GeneratePassword.java
Labels: (SE) Security, 02 bug
