Repository adempiere/adempiere, pull requests merged in 2018-08, with the labels that each got.

#1841 #1552, Change Dictionary definition for posting employee, reference to
  base/src/org/eevolution/model/I_HR_Payroll.java
  base/src/org/eevolution/model/I_HR_Process.java
  base/src/org/eevolution/model/X_HR_Payroll.java
  base/src/org/eevolution/model/X_HR_Process.java
  migration/390lts-391/03630_1552_HHRR_FlagPostIndividually.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
Labels: (HRM) Human Resource and Payroll Management, (PA) Performance Analysis and General Ledger, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance

#1851 #1711 Added popup to close tabs in zk
  zkwebui/WEB-INF/src/org/adempiere/webui/part/WindowContainer.java
Labels: (UI) User Interface Improvement, 01 enhancement

#1650 adempiere: #1648 Smart Browser Create from Invoice in pay selection d…
  migration/390lts-391/03800_1648_CorrectionSBCreatePaySelectionFromInvoice.xml
Labels: (AP) Account Payable, 01 enhancement, 13 Pending Acceptance, 14 Waiting for User Changes

#1824 #1823, Add helper method for payment export list, reference to issue:
  base/src/org/compiere/util/PaymentExportList.java
Labels: (AP) Account Payable, 01 enhancement

#1855 #1354, fixed error with bad zooming from Smart Browser, reference to
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (UI) User Interface Improvement, 02 bug

#1854 #1853, Add feature for open result from process, reference to issue:
  base/src/org/compiere/apps/ProcessController.java
  base/src/org/compiere/process/ProcessInfo.java
  base/src/org/compiere/process/SvrProcess.java
  client/src/org/compiere/apps/ProcessModalDialog.java
  client/src/org/compiere/apps/ProcessPanel.java
  client/src/org/eevolution/form/VBrowser.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
  zkwebui/WEB-INF/src/org/eevolution/form/WBrowser.java
Labels: (UI) User Interface Improvement, 01 enhancement

#1653 #1113 : The ZK not work jasper report included in print format.
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/WProcessCtl.java
Labels: (SC) System Core, 02 bug

#1871 #1867 NPE when try validate Model ValidationEngine https://github.com…
  base/src/org/compiere/model/ModelValidationEngine.java
Labels: (SC) System Core, 02 bug

#1845 #1844, Fixed missing column for automatic generate column when a table
  base/src/org/compiere/model/MTable.java
Labels: (SC) System Core, 02 bug, 09 Pending Peer Review

#1884 #1883 Update Scala Test to Execute test Suite
  org.adempiere.test/build.sbt
  org.adempiere.test/src/main/scala/org/eevolution/dsl/package.scala
  org.adempiere.test/src/test/scala/org/eevolution/test/AdempiereTestCase.scala
Labels: (CI) Code Improvement or Optimization, 01 enhancement

#1881 improvement classpath from pull request:
  .classpath
Labels: 02 bug

#1887 #1856, Fix permission with dmp file, reference to issue:
  build.xml
Labels: (CI) Continuous Integration, 02 bug

#1878 #1875, Add Workflow activity translation, reference to issue:
  base/src/org/compiere/process/DocAction.java
  base/src/org/compiere/wf/MWFActivity.java
  base/src/org/compiere/wf/MWFNode.java
  migration/390lts-391/03950_1875_Add_WF_Message.xml
Labels: (SC) System Core, 01 enhancement, 09 Pending Peer Review

#1901 #1894 Converting a requisition to purchase order through a Smart Browser
  base/src/org/compiere/process/RequisitionPOCreate.java
  base/src/org/compiere/process/RequisitionPOCreateAbstract.java
  base/src/org/eevolution/process/CreatePOFromRequisitionLines.java
  base/src/org/eevolution/process/CreatePOFromRequisitionLinesAbstract.java
  migration/390lts-391/03980_1896_RequisitionBrowser.xml
  migration/390lts-391/03990_1894_CreatePOFromRequisitionLines.xml
Labels: (PO) Purchase Management, 01 enhancement

#1900 #1896 Smart Browser for Material Requisition https://github.com/ademp…
  migration/390lts-391/03980_1896_RequisitionBrowser.xml
Labels: (PO) Purchase Management, 01 enhancement

#1886 #1852 cannot RUN_MigrateXML.sh : 390lts-391 - A circular Problem. htt…
  base/src/org/compiere/process/MigrationFromXMLAbstract.java
Labels: (SA) System Administrator, (SC) System Core, 02 bug

#1885 #1672, Add new currency for Venezuela VES, reference to issue:
  migration/390lts-391/03930_1088_Add_Column_IsQuickEntry.xml
  migration/390lts-391/03940_1744_AddDashboardAccesTab.xml
  migration/390lts-391/03960_1672_Add_new_VES_Currency.xml
Labels: (AP) Account Payable, 01 enhancement, 09 Pending Peer Review, 10 Reviewed by Peer, 14 Waiting for User Changes

#1826 bugfix for #1782 Movement Date in MProduction
  base/src/org/compiere/model/MProduction.java
  base/src/org/compiere/model/MProductionBatch.java
Labels: (MM) Material Management, 02 bug, 14 Waiting for User Changes

#1905 #1904 Link a Bank with Business Partner https://github.com/adempiere/…
  base/src/org/compiere/model/I_C_Bank.java
  base/src/org/compiere/model/X_C_Bank.java
  migration/390lts-391/03995_1904_LinkBankWithBusinessPartner.xml
Labels: (AP) Account Payable, (AR) Account Receivable, 01 enhancement

#1933 #1554 Accounting: Process to close the cost/income accounts at the end of the fiscal year
  base/src/org/adempiere/process/YearEndClosing.java
  base/src/org/adempiere/process/YearEndClosingAbstract.java
  base/src/org/compiere/model/I_GL_JournalBatch.java
  base/src/org/compiere/model/MJournal.java
  base/src/org/compiere/model/X_GL_JournalBatch.java
  migration/390lts-391/03670_1554_Year-end_Closing.xml
Labels: 01 enhancement, 04 invalid

#1897 #1889, Add support for multiple bank transfer from payment selection,
  base/src/org/compiere/model/I_C_DocType.java
  base/src/org/compiere/model/I_C_PaySelectionLine.java
  base/src/org/compiere/model/MPaySelection.java
  base/src/org/compiere/model/MPaySelectionCheck.java
  base/src/org/compiere/model/X_C_DocType.java
  base/src/org/compiere/model/X_C_PaySelectionLine.java
  base/src/org/eevolution/process/BankTransfer.java
  base/src/org/eevolution/process/BankTransferAbstract.java
  migration/390lts-391/03960_1889_MultipleBankTransfer.xml
Labels: (AP) Account Payable, (FIM) Financial Management, 01 enhancement

#1940 Fix for #1926 ZK Exports migration XML files to different location th…
  base/src/org/compiere/process/MigrationToXML.java
  base/src/org/compiere/process/ProcessInfo.java
  client/src/org/compiere/apps/ProcessModalDialog.java
  migration/390lts-391/04000_1926_RemoveFileNameFromExptMigration.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
Labels: 02 bug, 09 Pending Peer Review, 10 Reviewed by Peer

#1929 #1928 Add missing jasper report libraries to the eclipse web deployme…
  .settings/org.eclipse.wst.common.component
Labels: 02 bug, 08 IDE, 10 Reviewed by Peer, 13 Pending Acceptance

#1942 #1936 Adding selection records to AD_Migration
  migration/390lts-391/04010_1936_MigrationTableLacksSelectionRecords.xml
Labels: 01 enhancement, 10 Reviewed by Peer
