Repository adempiere/adempiere, pull requests merged in 2018-03, with the labels that each got.

#1594 #1593, fixed error with month diff for helper method in
  base/src/org/compiere/util/TimeUtil.java
Labels: 02 bug

#1600 adempiere: #1598 Support Spanish El Salvador as language in class Lan…
  base/src/org/compiere/util/Language.java
Labels: (SC) System Core, 01 enhancement

#1602 #1499 Defining two Standard Request Type associated to the same table…
  org.adempiere.request/src/main/java/org/compiere/model/MStandardRequestType.java
  org.adempiere.request/src/main/java/org/compiere/model/RequestModelValidator.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WTreeMaintenance.java
  zkwebui/images/FastBack16.png
  zkwebui/images/FastBack24.bak
  zkwebui/images/FastBack24.png
  zkwebui/images/FastForward16.png
  zkwebui/images/FastForward24.png
  zkwebui/images/StepBack16.png
  zkwebui/images/StepBack24.png
  zkwebui/images/StepForward16.png
  zkwebui/images/StepForward24.png
  zkwebui/images/dark/FastBack16.png
  zkwebui/images/dark/FastBack24.png
  zkwebui/images/dark/FastForward16.png
  zkwebui/images/dark/FastForward24.png
  zkwebui/images/dark/StepBack16.png
  zkwebui/images/dark/StepBack24.png
  zkwebui/images/dark/StepForward16.png
  zkwebui/images/dark/StepForward24.png
Labels: (RM) Request Management, 01 enhancement
