Repository adempiere/adempiere, pull requests merged in 2018-06, with the labels that each got.

#1731 #1730, Fixed running as silent process with modal dialog for process
  base/src/org/compiere/apps/ProcessController.java
  client/src/org/compiere/apps/APanel.java
  client/src/org/compiere/apps/ProcessModalDialog.java
  client/src/org/compiere/apps/ProcessPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/desktop/TabbedDesktop.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug

#1739 #1738, Fixed selected by defaul ZK UI and improve performance for Swing
  client/src/org/eevolution/form/VBrowser.java
  zkwebui/WEB-INF/src/org/eevolution/form/WBrowser.java
Labels: (UI) User Interface Improvement, 02 bug

#1729 #1727, Fixed error with dialog for fill mandatory parameters from Swing
  client/src/org/compiere/apps/ProcessPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug

#1633 adempiere:#1625 Zooming of Operational Period not possible in Forecast
  migration/390lts-391/03790_1625_Zooming_of_Operational_Period_not_possible_in_Forecast_window.xml
Labels: 02 bug, 13 Pending Acceptance

#1771 #1730, fixed bug introduced with issue, reference to issue:
  base/src/org/compiere/apps/ProcessController.java
  client/src/org/compiere/apps/ProcessModalDialog.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug

#1626 Price entries
  base/src/org/adempiere/process/CreateProductEntriesInPriceList.java
  base/src/org/adempiere/process/CreateProductEntriesInPriceListAbstract.java
  migration/390lts-391/03760_1615_PriceListEntries.xml
Labels: 01 enhancement
