Repository adempiere/adempiere, pull requests merged in 2019-08, with the labels that each got.

#2687 Fixed error with travis Continuous Integration for Oracle 8 license
  .travis.yml
  build.xml
Labels: (CI) Continuous Integration, 02 bug

#2675 Add validation for field level instead column level for Bank Statement
  migration/392lts-393lts/05030_2674_Fixed_Validation_for_BankStatementMatcher.xml
Labels: (FIM) Financial Management, 02 bug

#2685 Fixed errors on accounting tree
  base/src/org/compiere/model/PO.java
  migration/392lts-393lts/04750_Add_Filter_Account_Element.xml
Labels: (SC) System Core, 02 bug

#2691 #2690 Cat not Complete Sale Order on Credit using Complete prepared …
  org.adempiere.pos/src/main/java/base/org/adempiere/pos/command/CommandCompleteDocument.java
Labels: (POS) Point Of Sales, 02 bug

#2693 #2692 When find Business Partner from POS get SQL error https://githu…
  base/src/org/compiere/model/MBPartnerInfo.java
Labels: (POS) Point Of Sales, 02 bug

#2697 #2696 Can not call a Financial Report background process and process …
  base/src/org/compiere/report/FinReport.java
Labels: (FIM) Financial Management, 02 bug

#2684 #2683 Enable Dashboard column setting proportion
  migration/392lts-393lts/05030_DashboardSettingColumnProportion.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
Labels: (UI) User Interface Improvement, 01 enhancement

#2707 - Fixed the migration sequence and version for ADempiere 3.9.3
  migration/392lts-393lts/04600_2579_PayrollProcessShouldBeNotAlwaysUpdated.xml
  migration/392lts-393lts/04660_1267_Add_Forecast_Window_Reference.xml
  migration/392lts-393lts/04671_2564_Add_Missing_UUID.xml
  migration/392lts-393lts/04672_Add_User_Info_Logo.xml
  migration/392lts-393lts/04692_Add_My_Own_Changes_Flag.xml
  migration/392lts-393lts/04715_Add_Support_to_Tree_Search_Field.xml
Labels: 01 enhancement

#2709 #2708 Translation Error for Inbound and Outbound Type into Inbound and Outbound Strategy Window
  migration/392lts-393lts/05040_2708_Fix_TranslationErrorIOBoundType.xml
Labels: (WMS) Warehouse Management System, 02 bug

#2451 #2450 Forecast Run has an issue generating the first run
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ForecastRunCreate.java
Labels: (FM) Forecast Management, 02 bug, 09 Pending Peer Review

#2718 Add parameters to Product Transaction Report
  db/ddlutils/oracle/views/RV_M_TRANSACTION.sql
  db/ddlutils/postgresql/views/RV_M_TRANSACTION.sql
  migration/392lts-393lts/05080_2717_Add_Product_Transaction_Report_Parameters.xml
Labels: (MM) Material Management, (PF) Report Engine & Print Format, 01 enhancement

#2719 Add changes for packout handler
  base/src/org/adempiere/pipo/AttributeFiller.java
  base/src/org/adempiere/pipo/IDFinder.java
  base/src/org/adempiere/pipo/PackInHandler.java
  base/src/org/adempiere/pipo/PackOut.java
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Labels: (PIO) Packin / Packout, 01 enhancement

#2716 Add Transaction Detail Parameters
  db/ddlutils/oracle/views/RV_TRANSACTION.sql
  db/ddlutils/postgresql/views/RV_TRANSACTION.sql
  migration/392lts-393lts/05070_2715_Add_Transaction_Detail_Parameters.xml
Labels: (MM) Material Management, (PF) Report Engine & Print Format, 01 enhancement

#2714 Add parameters for Storage Detail report
  db/ddlutils/oracle/views/RV_STORAGE.sql
  db/ddlutils/postgresql/views/RV_STORAGE.sql
  migration/392lts-393lts/05060_1397_Add_New_Parameters_Storage_Detail.xml
Labels: (MM) Material Management, (PF) Report Engine & Print Format, 01 enhancement

#2713 Add some parameters to order detail report
  db/ddlutils/oracle/views/RV_ORDERDETAIL.sql
  db/ddlutils/postgresql/views/RV_ORDERDETAIL.sql
  migration/392lts-393lts/05050_1442_Add_Parameters_Order_Detail_Report.xml
Labels: (PF) Report Engine & Print Format, (SO) Sales Management, 01 enhancement

#2711 Fixed error with validation for extension with attachment
  base/src/org/compiere/util/MimeType.java
Labels: (PF) Report Engine & Print Format, 02 bug

#2726 Fixed error with translation for tabs, reference to issue: #2725
  base/src/org/spin/util/ASPUtil.java
Labels: (TRL) Translation, 02 bug

#2727 fixed error with field group translation
  base/src/org/compiere/model/GridFieldVO.java
Labels: (TRL) Translation, 02 bug

#2729 Add Create From Requisition for RFQ reference to issue #2728
  base/src/org/compiere/model/I_M_RequisitionLine.java
  base/src/org/compiere/model/X_M_RequisitionLine.java
  base/src/org/spin/process/RFQCreateFromRequisition.java
  base/src/org/spin/process/RFQCreateFromRequisitionAbstract.java
  migration/392lts-393lts/05110_2728_Add_CreateFromRequisition_RFQ.xml
Labels: (PO) Purchase Management, 01 enhancement

#2706 #2705 When a financial report is executed from the background, a nest…
  base/src/org/compiere/report/FinReport.java
Labels: (FIM) Financial Management, 02 bug

#2723 Add form for outbound order
  .classpath
  migration/392lts-393lts/05090_2023_Add_Form_GenerateOutBoundOrder.xml
  org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java
  org.eevolution.warehouse/src/main/java/ui/zk/org/spin/form/WOutBoundOrder.java
Labels: (WMS) Warehouse Management System, 01 enhancement

#2678 Add support to RowNum for Standard Querys
  base/src/org/compiere/dbPort/ConvertMap_PostgreSQL.java
  base/src/org/compiere/dbPort/Convert_PostgreSQL.java
  base/src/org/compiere/dbPort/Convert_PostgreSQLTest.java
  base/src/org/compiere/dbPort/PostgresConvertTest.java
  base/src/org/compiere/model/Query.java
  base/src/org/spin/test/QueryTest.java
Labels: (SA) System Administrator, (SC) System Core, 01 enhancement

#2741 solve issue #2740 NPE when set Bank Statement Line description
  base/src/org/compiere/model/MBankStatementLine.java
Labels: 02 bug

#2744 Fixed description and description for migration script
  migration/392lts-393lts/04691_Add_Missing_UUID.xml
Labels: 01 enhancement

#2680 Fix error on generate cost detail with reversed inventory documents
  base/src/org/adempiere/engine/AverageInvoiceCostingMethod.java
  base/src/org/adempiere/engine/AveragePOCostingMethod.java
  base/src/org/adempiere/engine/IDocumentLine.java
  base/src/org/adempiere/engine/StandardCostingMethod.java
  base/src/org/compiere/model/MInOutLine.java
  base/src/org/compiere/model/MInventoryLine.java
  base/src/org/compiere/model/MLandedCostAllocation.java
  base/src/org/compiere/model/MMatchInv.java
  base/src/org/compiere/model/MMatchPO.java
  base/src/org/compiere/model/MMovementLine.java
  base/src/org/compiere/model/MOrderLine.java
  base/src/org/compiere/model/MProductionLine.java
  base/src/org/eevolution/model/MPPCostCollector.java
  org.adempiere.project/src/main/java/org/compiere/model/MProjectIssue.java
Labels: (CM) Costing Management, (SC) System Core, 02 bug

#2743 Generate receipt automatically from Express Receipt
  org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBoundLine.java
Labels: (WMS) Warehouse Management System, 01 enhancement

#2746 Change for get payment amount from Payment Object Selected
  base/src/org/compiere/process/StatementCreateFrom.java
Labels: (CI) Code Improvement or Optimization
