Repository adempiere/adempiere, pull requests merged in 2019-02, with the labels that each got.

#2321 Add Vertical Separator to the User Panel between Context and Preference
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/UserPanel.java
Labels: (UI) User Interface Improvement, 01 enhancement

#2319 Change the "Forgot Password?" lable to a link.
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
Labels: (UI) User Interface Improvement, 01 enhancement

#2283 Fixed error with Table lookup when it is referenced with key column as
  base/src/org/adempiere/util/ProcessAbstractClassGenerator.java
Labels: (AD) Application Dictionary, 02 bug

#2243 #2242, Change Length of AD_Browser_Trl table, reference to issue:
  migration/391lts-392lts/04410_Change_Browser_Name_Length.xml
Labels: (SB) Smart Browser, (SC) System Core, (TRL) Translation, 02 bug

#2246 #1467 Validate Null in Text Editor Dialog
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WTextEditorDialog.java
Labels: (UI) User Interface Improvement, 02 bug

#2267 #2266 migration Enlarge_length_for_bank_name to 120
  migration/391-392/4510_2266_Enlarge_length_for_bank_name.xml
Labels: (AP) Account Payable, (AR) Account Receivable, 01 enhancement

#2258 #2257 fix in utils/PostgreSQL/ImportAdempiere.sh
  utils/PostgreSQL/ImportAdempiere.sh
Labels: (INS) Installation, 02 bug

#2361 adempiere #2360 Quicksheet shows all fields
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
Labels: (UI) User Interface Improvement, 02 bug

#2351 #2332 Resubmit and Rest Accounting does not work properly with multi …
  base/src/org/compiere/process/FactAcctReset.java
  base/src/org/compiere/process/FactAcctResetAbstract.java
Labels: (AC) Accounting, 02 bug

#2350 Fixes #2349. Restores a needed line that was deleted accidentally.
  client/src/org/compiere/grid/tree/VTreePanel.java
Labels: (UI) User Interface Improvement, 02 bug

#2269 #2268 Payroll Create Invoice no is possible generate invoice for payr…
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/HRCreateInvoice.java
Labels: (HRM) Human Resource and Payroll Management, 02 bug

#2344 #2343 NPE from Journal Lines when a valid combination not exist https…
  base/src/org/compiere/model/MJournal.java
Labels: (AC) Accounting, 02 bug

#2275 #2274 Error of NPE when try generate accounting distribution when an …
  base/src/org/compiere/acct/Fact.java
Labels: (AC) Accounting, 02 bug

#2279 #2276 When an Asset is created from an invoice, this no use project a…
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAsset.java
Labels: (FAM) Fixed Asset Management, 02 bug

#2280 #2277 Asset Depreciation not use the project and activity from an as…
  org.adempiere.asset/src/main/java/base/org/compiere/acct/Doc_DepreciationEntry.java
Labels: (FAM) Fixed Asset Management, 02 bug

#2396 #2395 Missing .classpath Declaration
  .classpath
Labels: 02 bug, 08 IDE, 09 Pending Peer Review

#2388 #2387 Remove ampersands in Record Info dialogs
  base/src/org/adempiere/controller/RecordInfoController.java
Labels: 02 bug, 09 Pending Peer Review

#2385 #2383 Override the getPopupMenu method() in webui date / time editor.
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WDateEditor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WDatetimeEditor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WTimeEditor.java
Labels: (UI) User Interface Improvement, 02 bug, 09 Pending Peer Review

#2377 Add support to Panama variant for language
  base/src/org/compiere/util/Language.java
Labels: (LOC) Locations, 01 enhancement

#2378 #2329 Solve error with Field Movement Cursor in Single Record
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADTabPanel.java
Labels: (UI) User Interface Improvement, 02 bug

#2399 #2293 Error when completing a "Return to Vendor" Invoice (AP Credit Memo)
  base/src/org/compiere/model/MInvoice.java
Labels: (RMA) Return Material Authorization, 02 bug, 09 Pending Peer Review

#2339 Add Entity Type as parameter for Export UUID process
  base/src/org/spin/process/ExportSurrogateKeyToMigration.java
  base/src/org/spin/process/ExportSurrogateKeyToMigrationAbstract.java
  migration/391lts-392lts/04420_Add_EntityType_Generate_UUID.xml
Labels: (SA) System Administrator, 01 enhancement

#2398 #2381 Project Status Category doesn't work
  migration/391lts-392lts/04440_2381_Project_Status_Category_does_not_work.xml
Labels: (PM) Project Management, 02 bug, 09 Pending Peer Review

#2341 Turns the Doc Status Indicator text into a link and shows all fields in grid.
  migration/391lts-392lts/04440_2340_ImproveDocumentStatusIndicators.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java
Labels: (UI) User Interface Improvement, 02 bug, 14 Waiting for User Changes

#2386 #2373 Add shortcut key Shift+F2 to copy record in webui.
  zkwebui/WEB-INF/src/org/adempiere/webui/component/CWindowToolbar.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADWindowPanel.java
Labels: (UI) User Interface Improvement, 01 enhancement, 10 Reviewed by Peer
