Repository adempiere/adempiere, pull requests merged in 2019-07, with the labels that each got.

#2661 Update Libraries for Attachment NextCloud Integration
  adempiere.iml
  tools/build.xml
Labels: 01 enhancement

#2657 #2656 Adding support for interface type swing or zk https://github.co…
  client/src/org/compiere/apps/ProcessDialog.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java
Labels: (UI) User Interface Improvement, 01 enhancement

#2654 Add helper method for get days between including current day
  base/src/org/compiere/util/TimeUtil.java
Labels: 01 enhancement

#2663 Add contract for Employee information
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement

#2670 Feature/#hr add concept help
  migration/392lts-393lts/05010_Add_Help_to_HR_Concept_Catalog.xml
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement

#2672 Feature/#payroll change updateable period
  migration/392lts-393lts/05020_Change_updateable_Date_HR_Process.xml
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement
