Repository adempiere/adempiere, pull requests merged in 2019-10, with the labels that each got.

#2838 Replaced UUID function to avoid install extra PG extension https://gi…
  db/ddlutils/postgresql/functions/getUUIDWithPGCrypto.sql
  db/ddlutils/postgresql/functions/getUUIDWithUUID-OSSP.sql
  migration/392lts-393lts/05450_ReplacedUUIDFunctionToAvoidInstallPGExtension.xml
Labels: (SC) System Core, 01 enhancement

#2842 Fixed error with bank statement voided
  base/src/org/compiere/model/MBankStatement.java
Labels: (BM) Bank Management, 02 bug

#2845 #2844 Enhancement to show an exception error when trying to sell an a…
  org.adempiere.asset/src/main/java/base/org/compiere/FA/model/ModelValidator.java
Labels: (FAM) Fixed Asset Management, 01 enhancement

#2851 The document type for Freight Order show all document type
  migration/392lts-393lts/05450_2850_SetReferenceForDocumentTypeFreight.xml
Labels: (DFM) Fleet Management, 02 bug

#2852 Fixed error with Sales Order Object Date errors clogging up log files,
  base/src/org/spin/model/MADContextInfo.java
Labels: (SC) System Core, 02 bug

#2854 Set version for Reference for Document Type Freight
  migration/392lts-393lts/05450_2850_SetReferenceForDocumentTypeFreight.xml
Labels: (DFM) Fleet Management, 01 enhancement

#2861 Fixed error with Token Definition Access Level
  base/src/org/spin/model/I_AD_TokenDefinition.java
  base/src/org/spin/model/MADTokenDefinition.java
  base/src/org/spin/model/X_AD_TokenDefinition.java
  migration/392lts-393lts/05460_Change_TokenDefinition_Access_Level.xml
Labels: (SA) System Administrator, (SE) Security, 02 bug

#2863 Add parameters for Payment Allocation Report
  migration/392lts-393lts/05470_Add_Payment_Allocation_Some_Parameters.xml
Labels: (PF) Report Engine & Print Format, 01 enhancement

#2868 Add Payment Selection Detail report
  db/ddlutils/oracle/views/RV_C_PaySelectionDetail_Oracle.sql
  db/ddlutils/postgresql/views/RV_C_PaySelectionDetail.sql
  migration/392lts-393lts/05490_Add_PaymentSelectionDetail_Report.xml
Labels: (AP) Account Payable, (FIM) Financial Management, 01 enhancement

#2869 Add Document Type on Match Invoice
  base/src/org/compiere/model/I_M_MatchInv.java
  base/src/org/compiere/model/MMatchInv.java
  base/src/org/compiere/model/X_M_MatchInv.java
  migration/392lts-393lts/05470_Add_Document_Type_Match_Invoice.xml
Labels: (MM) Material Management, 01 enhancement

#2866 Add views for RV_WM_InOutBoundDetail to inventory views
  db/ddlutils/oracle/views/RV_WM_InOutBoundDetail_Oracle.sql
  db/ddlutils/postgresql/views/RV_WM_InOutBoundDetail.sql
Labels: (WMS) Warehouse Management System, 01 enhancement

#2871 #2870 Error when try accounting payroll, can not get account data
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRConcept.java
Labels: (HRM) Human Resource and Payroll Management, 02 bug

#2872 Add BP Groups:
  db/ddlutils/oracle/views/C_PAYMENT_V.sql
  db/ddlutils/oracle/views/RV_C_INVOICE.sql
  db/ddlutils/oracle/views/RV_C_INVOICELINE.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_CUSTOMERPRODQTR.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_CUSTOMERVENDQTR.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_DAY.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_MONTH.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_PRODMONTH.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_PRODUCTMONTH.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_PRODUCTQTR.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_PRODWEEK.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_VENDORMONTH.sql
  db/ddlutils/oracle/views/RV_C_INVOICE_WEEK.sql
  db/ddlutils/oracle/views/RV_OPENITEM.sql
  db/ddlutils/oracle/views/RV_OPENITEMTODATE.sql
  db/ddlutils/oracle/views/RV_ORDERDETAIL.sql
  db/ddlutils/oracle/views/RV_PAYMENT.sql
  db/ddlutils/postgresql/views/C_PAYMENT_V.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE.sql
  db/ddlutils/postgresql/views/RV_C_INVOICELINE.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_CUSTOMERPRODQTR.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_CUSTOMERVENDQTR.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_DAY.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_MONTH.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_PRODMONTH.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_PRODUCTMONTH.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_PRODUCTQTR.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_PRODWEEK.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_VENDORMONTH.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE_WEEK.sql
  db/ddlutils/postgresql/views/RV_OPENITEM.sql
  db/ddlutils/postgresql/views/RV_OPENITEMTODATE.sql
  db/ddlutils/postgresql/views/RV_ORDERDETAIL.sql
  db/ddlutils/postgresql/views/RV_PAYMENT.sql
  migration/392lts-393lts/05490_Add_BP_Groups.xml
Labels: (SC) System Core, (SO) Sales Management, 01 enhancement

#2862 WMS bug fixed
  base/src/org/eevolution/model/MDDOrder.java
  migration/392lts-393lts/05460_BugFixedTheOutboundOrderFunctionality.xml
  org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_DDOrder.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/engine/warehouse/WMRuleFIFO.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBoundLine.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/process/GenerateInOutBound.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/process/GenerateShipmentOutBound.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/process/ReleaseInOutBound.java
Labels: (WMS) Warehouse Management System, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance

#2874 Add Exclude of total calculation attribute for print format item
  base/src/org/compiere/model/I_AD_PrintFormatItem.java
  base/src/org/compiere/model/X_AD_PrintFormatItem.java
  base/src/org/compiere/print/DataEngine.java
  base/src/org/compiere/print/MPrintFormatItem.java
  base/src/org/compiere/print/PrintDataColumn.java
  migration/392lts-393lts/05500_Add_exclude_of_Total_Calculation_PrintFormat.xml
Labels: (PF) Report Engine & Print Format, 01 enhancement

#2875 Fix on Accounting Reset Process
  base/src/org/compiere/process/FactAcctReset.java
Labels: (AC) Accounting, 02 bug

#2878 Apply round mode for identity payment with a existing payment
  base/src/org/spin/process/PaymentIdentify.java
Labels: (AP) Account Payable, 01 enhancement
