Repository adempiere/adempiere, pull requests merged in 2019-03, with the labels that each got.

#2334 #2324 Improve the functionality of the Favorites (User) panel.
  migration/391lts-392lts/04430_2324_ImproveFuncDPUserFavorites.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/component/ADTreeFavoriteOnDropListener.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/SimpleFavoriteTreeModel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DPUserFavorites.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/MenuPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WStringEditorDialog.java
  zkwebui/images/dark/FolderAdd16.png
  zkwebui/images/dark/FolderPlain16.png
Labels: (UI) User Interface Improvement, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance

#2406 #2375 Error on process Generating PO from Requisition
  base/src/org/compiere/process/RequisitionPOCreate.java
Labels: (PO) Purchase Management, 02 bug, 09 Pending Peer Review

#2420 Feature/language
  base/src/org/compiere/util/Language.java
Labels: (TRL) Translation, 02 bug

#2412 Print and Release Manufacturing Order not change the doc status to complete
  org.adempiere.test/build.sbt
  org.adempiere.test/project/plugins.sbt
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/CompletePrintOrder.java
  project/build.properties
  project/plugins.sbt
Labels: (PMM) Planning and Manufacturing Management, 02 bug

#2423 Add minor change: folder from 391lts-392 to 391lts-392lts
  migration/391lts-392lts/4510_2266_Enlarge_length_for_bank_name.xml
Labels: (MNC) Minor Change

#2401 Add currency and currency conversion for Payroll process, this change
  base/src/org/eevolution/model/I_HR_Process.java
  base/src/org/eevolution/model/X_HR_Process.java
  migration/391lts-392lts/04430_Add_HR_Process_Currency.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (AC) Accounting, (HRM) Human Resource and Payroll Management, 01 enhancement, 09 Pending Peer Review

#2376 Remove old approach for socket and local printing from POS
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WCollect.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOS.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/test/SideServer.java
Labels: (CI) Code Improvement or Optimization, (POS) Point Of Sales, 01 enhancement, 09 Pending Peer Review

#2259 #2250, Fixed error with supported version for postgreSQL, reference to
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBEngine_Postgresql.java
Labels: (MT) Migration Tools, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance

#2248 #2247, Fixed error with getUUID function
  base/src/org/compiere/db/CConnection.java
  base/src/org/compiere/model/PO.java
  base/src/org/compiere/util/DB.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
Labels: (SC) System Core, 02 bug, 05 question, 17 Waiting for Information

#2353 Add Documentation Generator from ADempiere
  base/src/org/spin/process/GenerateDocsFromMenu.java
  base/src/org/spin/process/GenerateDocsFromMenuAbstract.java
  base/src/org/spin/util/docs/AbstractDocumentationSource.java
  base/src/org/spin/util/docs/AbstractTextConverter.java
  base/src/org/spin/util/docs/FunctionalDocsForForm.java
  base/src/org/spin/util/docs/FunctionalDocsForMenu.java
  base/src/org/spin/util/docs/FunctionalDocsForProcess.java
  base/src/org/spin/util/docs/FunctionalDocsForSmartBrowse.java
  base/src/org/spin/util/docs/FunctionalDocsForWindow.java
  base/src/org/spin/util/docs/IIndex.java
  base/src/org/spin/util/docs/MarkdownConverter.java
  base/src/org/spin/util/docs/ReStructuredTextConverter.java
  base/src/org/spin/util/docs/TableTextConverter.java
  migration/391lts-392lts/04420_1934_Process_Generate_Docs.xml
Labels: (AD) Application Dictionary, (DOC) Documentation

#2403 Add conversion for bank statement helper method
  base/src/org/compiere/model/MBankStatement.java
  base/src/org/compiere/model/MBankStatementLine.java
  base/src/org/compiere/process/StatementCreateFrom.java
Labels: (AP) Account Payable, (AR) Account Receivable, 02 bug, 09 Pending Peer Review

#2397 #2382 Project Status: Next Status not Filtered by Project Status Category
  migration/391lts-392lts/04430_2382_Project_Next_Status_not_Filtered_by_Category.xml
Labels: (PM) Project Management, 02 bug, 09 Pending Peer Review

#2432 #2431 Failed to get the internal id of a account element when multipl…
  base/src/org/compiere/process/ImportBudget.java
Labels: (PA) Performance Analysis and General Ledger, 02 bug

#2402 #2380 How to Re-Open a closed Project ?
  migration/391lts-392lts/04450_2380_How_to_Re-Open_a_closed_Project.xml
  org.adempiere.project/src/main/java/org/compiere/process/ProjectClose.java
Labels: (PM) Project Management, 01 enhancement, 09 Pending Peer Review

#2422 Add Smart Browse for Create process from window and tab on Role
  base/src/org/spin/process/RoleCreateFromWindowProcess.java
  base/src/org/spin/process/RoleCreateFromWindowProcessAbstract.java
  migration/391lts-392lts/04450_Add_Role_Process_Create_From_Window.xml
Labels: (SE) Security, 01 enhancement, 10 Reviewed by Peer

#2433 Fixed error with UUID for Migration from model
  base/src/org/compiere/model/MSession.java
  base/src/org/compiere/model/PO.java
Labels: (MT) Migration Tools, (SC) System Core, 02 bug

#2421 Add dependences for Smart Browse and process on packout
  base/src/org/adempiere/pipo/PackIn.java
  base/src/org/adempiere/pipo/PackInHandler.java
  base/src/org/adempiere/pipo/PackOut.java
  base/src/org/adempiere/pipo/PackOutAbstract.java
  base/src/org/adempiere/pipo/PoFiller.java
  base/src/org/adempiere/pipo/handler/AdElementHandler.java
  base/src/org/adempiere/pipo/handler/BrowseElementHandler.java
  base/src/org/adempiere/pipo/handler/CommonTranslationHandler.java
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
  base/src/org/adempiere/pipo/handler/ProcessElementHandler.java
  base/src/org/adempiere/pipo/handler/ReferenceElementHandler.java
  base/src/org/adempiere/pipo/handler/ReferenceListElementHandler.java
  base/src/org/adempiere/pipo/handler/ReferenceTableElementHandler.java
  base/src/org/adempiere/pipo/handler/TableElementHandler.java
  base/src/org/adempiere/pipo/handler/WindowElementHandler.java
Labels: (PIO) Packin / Packout, 01 enhancement, 10 Reviewed by Peer

#2441 #2324 Improve the functionality of the Favorites (User) panel
  migration/391lts-392lts/04430_2324_ImproveFuncDPUserFavorites.xml
Labels: 02 bug, 09 Pending Peer Review
