Repository adempiere/adempiere, pull requests merged in 2019-04, with the labels that each got.

#2456 Translation it
  data/it_IT/AD_Browse_Field_Trl_it_IT.xml
  data/it_IT/AD_Browse_Trl_it_IT.xml
  data/it_IT/AD_Desktop_Trl_it_IT.xml
  data/it_IT/AD_Element_Trl_it_IT.xml
  data/it_IT/AD_FieldGroup_Trl_it_IT.xml
  data/it_IT/AD_Field_Trl_it_IT.xml
  data/it_IT/AD_Form_Trl_it_IT.xml
  data/it_IT/AD_InfoColumn_Trl_it_IT.xml
  data/it_IT/AD_InfoWindow_Trl_it_IT.xml
  data/it_IT/AD_Menu_Trl_it_IT.xml
  data/it_IT/AD_Message_Trl_it_IT.xml
  data/it_IT/AD_PrintFormatItem_Trl_it_IT.xml
  data/it_IT/AD_PrintLabelLine_Trl_it_IT.xml
  data/it_IT/AD_Process_Para_Trl_it_IT.xml
  data/it_IT/AD_Process_Trl_it_IT.xml
  data/it_IT/AD_Ref_List_Trl_it_IT.xml
  data/it_IT/AD_Reference_Trl_it_IT.xml
  data/it_IT/AD_ReportView_Trl_it_IT.xml
  data/it_IT/AD_Tab_Trl_it_IT.xml
  data/it_IT/AD_Table_Trl_it_IT.xml
  data/it_IT/AD_Task_Trl_it_IT.xml
  data/it_IT/AD_View_Column_Trl_it_IT.xml
  data/it_IT/AD_View_Trl_it_IT.xml
  data/it_IT/AD_WF_Node_Trl_it_IT.xml
  data/it_IT/AD_Window_Trl_it_IT.xml
  data/it_IT/AD_Workbench_Trl_it_IT.xml
  data/it_IT/AD_Workflow_Trl_it_IT.xml
  data/it_IT/CM_CStage_Element_Trl_it_IT.xml
  data/it_IT/CM_CStage_Trl_it_IT.xml
  data/it_IT/CM_Container_Element_Trl_it_IT.xml
  data/it_IT/CM_Container_Trl_it_IT.xml
  data/it_IT/COO_FaoZone_Trl_it_IT.xml
  data/it_IT/COO_ReportLabel_Trl_it_IT.xml
  data/it_IT/C_Charge_Trl_it_IT.xml
  data/it_IT/C_Country_Trl_it_IT.xml
  data/it_IT/C_Currency_Trl_it_IT.xml
  data/it_IT/C_DocType_Trl_it_IT.xml
  data/it_IT/C_DunningLevel_Trl_it_IT.xml
  data/it_IT/C_ElementValue_Trl_it_IT.xml
  data/it_IT/C_Greeting_Trl_it_IT.xml
  data/it_IT/C_PaymentTerm_Trl_it_IT.xml
  data/it_IT/C_TaxCategory_Trl_it_IT.xml
  data/it_IT/C_Tax_Trl_it_IT.xml
  data/it_IT/C_UOM_Trl_it_IT.xml
  data/it_IT/M_Product_Trl_it_IT.xml
  data/it_IT/PA_DashboardContent_Trl_it_IT.xml
  data/it_IT/PP_Order_BOMLine_Trl_it_IT.xml
  data/it_IT/PP_Order_BOM_Trl_it_IT.xml
  data/it_IT/PP_Order_Node_Trl_it_IT.xml
  data/it_IT/PP_Order_Workflow_Trl_it_IT.xml
  data/it_IT/PP_Product_BOMLine_Trl_it_IT.xml
  data/it_IT/PP_Product_BOM_Trl_it_IT.xml
  data/it_IT/R_MailText_Trl_it_IT.xml
  data/it_IT/W_MailMsg_Trl_it_IT.xml
  data/it_IT/W_Store_Trl_it_IT.xml
Labels: (TRL) Translation, 01 enhancement, 12 Feature

#2448 #2445 Make the ZK process panel message draggable in size.
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessPanel.java
Labels: 01 enhancement, 09 Pending Peer Review

#2454 #2453 Prevent duplication of process logs in dialogs
  base/src/org/compiere/process/ProcessInfoUtil.java
Labels: 02 bug, 09 Pending Peer Review

#2390 #2389 Adds a specific icon for smart browsers and updates Recent Items look and feel
  base/src/org/compiere/model/MTreeNode.java
  migration/391lts-392lts/04520_2443_UpdateLAFofRecentItems.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/AEnv.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/SimpleFavoriteTreeModel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DPRecentItems.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/MenuPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/theme/ITheme.java
  zkwebui/images/dark/mBrowse.png
Labels: (UI) User Interface Improvement, 09 Pending Peer Review

#2452 #2434 Tax.java
  base/src/org/compiere/model/Tax.java
Labels: 02 bug, 09 Pending Peer Review

#2462 Fixing value_to in search window
  zkwebui/WEB-INF/src/org/adempiere/webui/window/FindWindow.java
Labels: 02 bug

#2461 #2424 try+catch in VTabbedPane to fix the problem
  client/src/org/compiere/grid/VTabbedPane.java
Labels: (UI) User Interface Improvement, 02 bug

#2463 Import process hangs
  base/src/org/compiere/process/ImportBankStatement.java
Labels: 02 bug

#2418 Fix/#2347 w payment query error
  base/src/org/adempiere/controller/PaymentFormController.java
  base/src/org/adempiere/controller/ed/CAbstractEditorController.java
  base/src/org/adempiere/controller/ed/CEditorController.java
  base/src/org/adempiere/controller/ed/CPaymentEditor.java
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/MPayment.java
  base/src/org/compiere/model/MPaymentValidate.java
  client/src/org/compiere/grid/VPayment.java
  migration/391lts-392lts/04450_2347_FixWVPaymentReduceDupCode.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WPayment.java
Labels: 01 enhancement, 02 bug, 14 Waiting for User Changes

#2465 Revert "#2434 Tax.java"
  base/src/org/compiere/model/Tax.java
Labels: (SO) Sales Management, 02 bug

#2460 Default values from SQL of process parameter not worked
  base/src/org/adempiere/controller/SmallViewController.java
  zkwebui/WEB-INF/src/org/eevolution/form/WBrowser.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug

#2470 #2427 Error When Creating Translations
  migration/391lts-392lts/4520_2427_Error_When_Creating_Translations.xml
Labels: (MNC) Minor Change, (TRL) Translation, 02 bug, 09 Pending Peer Review

#2466 Improve Import Bankk Statement
  base/src/org/compiere/impexp/BankStatementLoaderInterface.java
  base/src/org/compiere/impexp/OFXBankStatementHandler.java
  base/src/org/compiere/impexp/OFXFileBankStatementLoader.java
  base/src/org/compiere/model/MBankStatementLoader.java
  base/src/org/compiere/process/ImportBankStatement.java
  base/src/org/spin/util/impexp/BankStatementHandler.java
Labels: (FIM) Financial Management, 01 enhancement

#2446 #2444, Fixed error with commitment for Sales Orders and Purchase,
  base/src/org/compiere/acct/Doc_InOut.java
  base/src/org/compiere/acct/Doc_Order.java
Labels: (MM) Material Management, 02 bug

#2440 Fixed error with Gain/Loss Report for Multi-Language
  base/src/org/compiere/model/MQuery.java
  db/ddlutils/oracle/views/T_INVOICEGL_V.sql
  db/ddlutils/oracle/views/T_INVOICEGL_VT.sql
  db/ddlutils/postgresql/views/T_INVOICEGL_V.sql
  db/ddlutils/postgresql/views/T_INVOICEGL_VT.sql
  migration/391lts-392lts/04520_Fixed_MultiLanguage_Gain_Loss_Report.xml
Labels: (AC) Accounting, (PA) Performance Analysis and General Ledger, 02 bug

#2486 Add subject for request
  migration/391lts-392lts/04540_Request_Subject.xml
Labels: (RM) Request Management, 01 enhancement

#2415 adempiere #2414 Replenishplan:CalculateReplenishPlan not creates ReLines
  org.adempiere.production/src/main/java/base/org/adempiere/process/CalculateReplenishPlan.java
  org.adempiere.production/src/main/java/base/org/compiere/process/ReplenishReportProduction.java
Labels: (MM) Material Management, 02 bug, 09 Pending Peer Review, 14 Waiting for User Changes

#2476 #2472 When you generate the invoice history for the forecast, the sal…
  base/src/org/eevolution/model/I_C_SalesHistory.java
  base/src/org/eevolution/model/X_C_SalesHistory.java
  migration/391lts-392lts/04530_2472_AddSalesRepToGenerateInvoiceHistory.xml
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/GenerateSalesHistory.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/GenerateSalesHistoryAbstract.java
Labels: (FM) Forecast Management, 01 enhancement

#2478 #2467 Error in Smart Browsers when "Value" or "DocumentNo" are query fields
  client/src/org/eevolution/form/VBrowser.java
  client/src/org/eevolution/grid/Browser.java
Labels: (SB) Smart Browser, 02 bug

#2497 #2306 Add the missing operator to Postgres.
  migration/391lts-392lts/04550_2306_CorrectMissingOperatorPostgres.xml
Labels: 02 bug

#2496 #2493 Error casting when execute a Model Adempiere Service web servic…
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ModelADServiceImpl.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/Process.java
Labels: (SC) System Core, 02 bug

#2498 Add changes for class for import from packout
  base/src/org/adempiere/pipo/PackInHandler.java
  base/src/org/adempiere/pipo/PoFiller.java
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Labels: (PIO) Packin / Packout, 02 bug

#2503 #1983 cumulative changes for add iban col to c_bp_bankaccount + validator
  base/src/org/compiere/model/I_C_BP_BankAccount.java
  base/src/org/compiere/model/MBPBankAccount.java
  base/src/org/compiere/model/MBankAccount.java
  base/src/org/compiere/model/X_C_BP_BankAccount.java
  migration/391lts-392lts/04520_1983_Add_iban_to_c_bp_bankaccount.xml
  migration/391lts-392lts/04530_1983_Add_iban_to_bp_window.xml
  tools/build.xml
  tools/lib/commons-validator-1.6.jar
  tools/lib/testing/commons-validator-1.6-sources.jar
Labels: (FIM) Financial Management, 01 enhancement

#2502 #2501 Launches a Report that shows one or multiple records according …
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/IADTabPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/WSortTab.java
Labels: (UI) User Interface Improvement, 01 enhancement

#2491 Add support to request mail template for event type
  migration/391lts-392lts/04530_Mail_Template_for_Event.xml
  org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
  org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
  org.adempiere.request/src/main/java/org/spin/model/I_R_NoticeTemplate.java
  org.adempiere.request/src/main/java/org/spin/model/I_R_NoticeTemplateEvent.java
  org.adempiere.request/src/main/java/org/spin/model/MRNoticeTemplate.java
  org.adempiere.request/src/main/java/org/spin/model/MRNoticeTemplateEvent.java
  org.adempiere.request/src/main/java/org/spin/model/X_R_NoticeTemplate.java
  org.adempiere.request/src/main/java/org/spin/model/X_R_NoticeTemplateEvent.java
  serverRoot/src/main/server/org/compiere/server/RequestProcessor.java
Labels: (RM) Request Management, 01 enhancement

#2509 Improve mail text formatter for may PO values
  org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
Labels: (RM) Request Management, 01 enhancement

#2508 Add parameter for validate session on lookup
  base/src/org/compiere/model/MLookupFactory.java
Labels: (MNC) Minor Change

#2513 #2512 Problem with ADempiere web service when execute process for jasper report or Adempiere Report Engine
  client/src/org/compiere/apps/ProcessCtl.java
  client/src/org/compiere/print/ReportCtl.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ModelADServiceImpl.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/Process.java
Labels: (SC) System Core, 02 bug

#2511 #2510 Change the method for printing standard for a batch mode witho…
  client/src/org/compiere/apps/ProcessCtl.java
  client/src/org/compiere/print/ReportCtl.java
Labels: (PF) Report Engine & Print Format, 01 enhancement

#2506 #2354 Calculate for Not Realized Gain / Loss for Account Element Mult…
  base/src/org/adempiere/process/GenerateNotRealizedGainLoss.java
  base/src/org/adempiere/process/GenerateNotRealizedGainLossAbstract.java
  base/src/org/compiere/model/I_T_InvoiceGL.java
  base/src/org/compiere/model/X_T_InvoiceGL.java
  base/src/org/compiere/process/InvoiceNGL.java
  db/ddlutils/oracle/views/T_INVOICEGL_V.sql
  db/ddlutils/oracle/views/T_INVOICEGL_VT.sql
  db/ddlutils/postgresql/views/T_INVOICEGL_V.sql
  db/ddlutils/postgresql/views/T_INVOICEGL_VT.sql
  migration/391lts-392lts/04425_2354_CalculateForNotRealizedGainLossforAccount.xml
Labels: (AC) Accounting, 01 enhancement
