Repository adempiere/adempiere, pull requests merged in 2019-05, with the labels that each got.

#2517 Revert "#2306 Add the missing operator to Postgres. "
  migration/391lts-392lts/04550_2306_CorrectMissingOperatorPostgres.xml
Labels: 02 bug

#2516 #2467 Error in Smart Browsers when "Value" or "DocumentNo" are query fields.
  client/src/org/eevolution/grid/Browser.java
Labels: (SB) Smart Browser, 02 bug

#2522 #2521 Setup ADempiere 392 release https://github.com/adempiere/adempi…
  migration/391lts-392lts/04424_Fixed_MultiLanguage_Gain_Loss_Report.xml
  migration/391lts-392lts/04523_2427_Error_When_Creating_Translations.xml
  migration/391lts-392lts/04525_1983_Add_iban_to_c_bp_bankaccount.xml
  migration/391lts-392lts/04533_2472_AddSalesRepToGenerateInvoiceHistory.xml
  migration/391lts-392lts/04535_Mail_Template_for_Event.xml
  migration/391lts-392lts/04543_Request_Subject.xml
  migration/391lts-392lts/04555_2483_AddRelationRequestUpdateRequestAction.xml
Labels: 01 enhancement

#2520 #2467 Error in Smart Browsers when "Value" or "DocumentNo" are query …
  client/src/org/eevolution/grid/Browser.java
Labels: (SB) Smart Browser, 02 bug

#2523 #2521 Setup ADempiere 392 release https://github.com/adempiere/adempi…
  migration/391lts-392lts/04425_2354_CalculateForNotRealizedGainLossforAccount.xml
  migration/391lts-392lts/04430_2324_ImproveFuncDPUserFavorites.xml
Labels: (SC) System Core, 01 enhancement

#2492 BOM Drop form improvments.
  base/src/org/adempiere/controller/form/BOMDropController.java
  base/src/org/adempiere/controller/form/BOMDropForm.java
  base/src/org/compiere/swing/CRadioButton.java
  client/src/org/compiere/apps/form/VBOMDrop.java
  client/src/org/compiere/grid/ed/VRadioButton.java
  migration/391lts-392lts/04530_2435_BOMDrop.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WBOMDrop.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/Radio.java
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WRadioEditor.java
Labels: 01 enhancement, 09 Pending Peer Review

#2547 #2546 The client id and report type are not set from the process inst…
  base/src/org/eevolution/service/dsl/ProcessBuilder.java
Labels: (SC) System Core, 02 bug

#2550 #2549 Add validation for Process Info create Adempiere Exception when…
  base/src/org/compiere/process/ProcessInfo.java
Labels: (SC) System Core, 02 bug

#2553 #2550 Add validation for Process Info create Adempiere Exception when…
  base/src/org/compiere/process/ProcessInfo.java
Labels: (SC) System Core, 01 enhancement

#2548 Change classpath
  .classpath
Labels: 01 enhancement, 08 IDE

#2552 #2551 Change orElse by orElseGet evaluations by lazy evaluation to im…
  base/src/org/adempiere/process/CreateProductEntriesInPriceList.java
  base/src/org/adempiere/process/GenerateNotRealizedGainLoss.java
  base/src/org/compiere/acct/Doc_Invoice.java
  base/src/org/compiere/model/MAllocationHdr.java
  base/src/org/compiere/model/MInOut.java
  base/src/org/compiere/model/MInventory.java
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/MJournal.java
  base/src/org/compiere/model/MMovement.java
  base/src/org/compiere/model/MPayment.java
  base/src/org/compiere/model/MProduction.java
  base/src/org/compiere/process/InvoiceCreateFrom.java
  base/src/org/eevolution/model/MDDOrder.java
  base/src/org/eevolution/model/MDDOrderLine.java
  com.kkalice.adempiere.migrate/src/com/kkalice/adempiere/migrate/DBObject_Sequence_Counter.java
  org.adempiere.pos/src/main/java/base/org/adempiere/pos/service/CPOS.java
  org.adempiere.pos/src/main/java/ui/swing/org/adempiere/pos/POSActionMenu.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSActionMenu.java
  org.adempiere.project/src/main/java/org/compiere/model/MProjectLine.java
  org.adempiere.request/src/main/java/org/compiere/process/RequestInvoice.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/HRPaySelectionCreateCheck.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/HRPaySelectionCreateFrom.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/ImportEmployeeAttributes.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProjectGenerateManufacturingOrder.java
Labels: (SC) System Core, 01 enhancement

#2554 Feature/#process add export format process
  base/src/org/compiere/print/ServerReportCtl.java
  base/src/org/compiere/process/ProcessInfo.java
  base/src/org/eevolution/service/dsl/ProcessBuilder.java
  base/src/org/spin/util/ReportExportHandler.java
Labels: (SC) System Core, 01 enhancement

#2556 #2555 Printing Orders with Jasper Reports do not work anymore https:/…
  base/src/org/compiere/print/ServerReportCtl.java
Labels: (PF) Report Engine & Print Format, 02 bug

#2384 Fix/fix for #197 delete cost detailsfor inactive cost elements
  base/src/org/compiere/model/MCost.java
  base/src/org/compiere/model/MCostElement.java
  base/src/org/eevolution/process/GenerateCostDetail.java
  migration/391lts-392/04390_0197_DeleteInactiveCostElements.xml
Labels: (CM) Costing Management, 02 bug, 13 Pending Acceptance

#2559 Fixed error missing translation on Custom Tree when the table is not translated
  base/src/org/compiere/model/MTable.java
  base/src/org/compiere/model/MTree.java
Labels: (TRL) Translation, 02 bug

#2563 Fixed error with BaseTable_ID from context
  base/src/org/compiere/model/GridWindowVO.java
Labels: (UI) User Interface Improvement, 02 bug

#2573 Bugfix/#process builder user not found
  base/src/org/eevolution/service/dsl/ProcessBuilder.java
Labels: (SC) System Core, 02 bug

#2544 #2540 Add validation for when a result is reported in the request and…
  org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
Labels: (RM) Request Management, 01 enhancement

#2571 #2567 Add fields as para parameters payroll movement https://github.c…
  base/src/org/eevolution/model/I_HR_Movement.java
  base/src/org/eevolution/model/X_HR_Movement.java
  migration/392lts-393lts/04590_2567_2568_AddFieldsAsParametersPayrollMovement.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement

#2572 #2570 The payroll process should be not always updated in payroll mov…
  migration/392lts-393lts/04600_2579_PayrollProcessShouldBeNotAlwaysUpdated.xml
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement

#2575 #2574 The Tax get helper method have not transaction name https://git…
  base/src/org/compiere/model/CalloutInvoice.java
  base/src/org/compiere/model/CalloutInvoiceBatch.java
  base/src/org/compiere/model/CalloutOrder.java
  base/src/org/compiere/model/MOrderLine.java
  base/src/org/compiere/model/Tax.java
Labels: 01 enhancement

#2545 #2537 The current process to generate invoice from a request does not…
  org.adempiere.request/src/main/java/org/compiere/process/RequestInvoice.java
Labels: (RM) Request Management, 01 enhancement, 14 Waiting for User Changes

#2543 #2541 Allow to delete draft invoices generated from a request update.…
  org.adempiere.request/src/main/java/org/compiere/model/RequestModelValidator.java
Labels: (AR) Account Receivable, (RM) Request Management, 01 enhancement

#2588 Bugfix/#1267 add window reference forecast
  migration/392lts-393lts/04650_536_Add_Keyboard_Validation_POS.xml
  migration/392lts-393lts/04660_1267_Add_Forecast_Window_Reference.xml
Labels: 02 bug

#2587 Add POS keyboard validation
  migration/392lts-393lts/04650_536_Add_Keyboard_Validation_POS.xml
Labels: (POS) Point Of Sales, 02 bug

#2586 Add Validation for Sales price list
  migration/392lts-393lts/04640_535_Add_Validation_Sales_Price_List_POS.xml
Labels: (POS) Point Of Sales, 02 bug

#2585 Add Display Logic for Quantity column
  migration/392lts-393lts/04630_527_Add_Display_Logic_Quantity_KeyLayout.xml
Labels: (POS) Point Of Sales, 02 bug

#2584 Add Display logic for product POS key layout
  base/src/org/compiere/model/MPOSKey.java
  migration/392lts-393lts/04620_525_Add_DisplayLogic_POS_KeyLayout.xml
Labels: (POS) Point Of Sales, 02 bug

#2583 Bufix NPE for field from ASP
  base/src/org/spin/util/ASPUtil.java
Labels: 02 bug

#2582 Add Session reference to process instance
  base/src/org/compiere/model/I_AD_PInstance.java
  base/src/org/compiere/model/MPInstance.java
  base/src/org/compiere/model/X_AD_PInstance.java
  migration/392lts-393lts/04610_Add_Session_Process_Instance.xml
Labels: (SA) System Administrator, (SC) System Core, 01 enhancement

#2580 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: (MNC) Minor Change

#2578 Add saveEx for custom browse
  base/src/org/compiere/model/MBrowseCustom.java
Labels: (SC) System Core, 02 bug

#2595 #2594 When using a custom class for freight calculation the system ca…
  org.eevolution.freight/src/main/java/base/org/eevolution/engine/freight/FreightEngine.java
Labels: (MM) Material Management, 02 bug

#2589 Add support to parameter on export surrogate key for missing UUID
  base/src/org/spin/process/ExportSurrogateKeyToMigration.java
  base/src/org/spin/process/ExportSurrogateKeyToMigrationAbstract.java
  migration/392lts-393lts/04670_2564_Add_Parameter_Export_Surrogate_Key.xml
Labels: (SA) System Administrator, 01 enhancement

#2590 Add missing UUID's for dictionary meta-data
  migration/392lts-393lts/04671_2564_Add_Missing_UUID.xml
Labels: (AD) Application Dictionary, 02 bug

#2591 Fixes error with NPE for Operational Calendar when year is null
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/model/MPPPeriodDefinition.java
Labels: 02 bug

#2592 Add support to create login user for initial setup
  base/src/org/compiere/model/MSetup.java
Labels: (SE) Security, 02 bug

#2596 Add User info Logo
  base/src/org/compiere/model/I_AD_User.java
  base/src/org/compiere/model/X_AD_User.java
  migration/392lts-393lts/04670_Add_User_Info_Logo.xml
Labels: 01 enhancement

#2597 Add social media infor for user contact
  base/src/org/spin/model/I_AD_UserSocialMedia.java
  base/src/org/spin/model/MADUserSocialMedia.java
  base/src/org/spin/model/X_AD_UserSocialMedia.java
  base/src/org/spin/util/support/GenericAppSupport.java
  migration/392lts-393lts/04680_Add_Social_Media_Info.xml
Labels: 01 enhancement

#2576 Fixed error with alias for generated SQL for Smart browser
  base/src/org/adempiere/model/MView.java
Labels: (SC) System Core, 02 bug

#2602 #2601 The calculate Freight only is activate when change the Order Li…
  org.eevolution.freight/src/main/java/base/org/eevolution/model/FreightModelValidator.java
Labels: (SO) Sales Management, 02 bug
