Repository adempiere/adempiere, pull requests merged in 2019-06, with the labels that each got.

#2609 #2606 POS ProductLookup does not work! https://github.com/adempiere/a…
  org.adempiere.pos/src/main/java/base/org/adempiere/pos/service/CPOS.java
Labels: (POS) Point Of Sales, 02 bug

#2611 #2610 Allows to capture a line break even when no amount is entered, …
  zkwebui/WEB-INF/src/org/eevolution/form/WScanBarUI.java
Labels: (POS) Point Of Sales, 01 enhancement

#2613 #2612 Solve error for Reference Validation Type Table
  base/src/org/adempiere/pipo/handler/ReferenceElementHandler.java
Labels: (PIO) Packin / Packout, 02 bug

#2604 Add support to SQL values on Workflow node condition
  base/src/org/compiere/wf/MWFNextCondition.java
  migration/392lts-393lts/04710_Increase_WF_Condition_Column_Size.xml
Labels: (BPM) Workflow Engine, 01 enhancement

#2614 Fixed error with export UUID for multy-Keys
  base/src/org/spin/process/ExportSurrogateKeyToMigration.java
  migration/392lts-393lts/04691_Add_Missing_UUID.xml
Labels: (SA) System Administrator, 02 bug

#2615 Add support to multy-key tables
  base/src/org/adempiere/pipo/PoFiller.java
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Labels: (PIO) Packin / Packout, 02 bug

#2621 #2620 Serious error when validating the price limit in the sales orde…
  base/src/org/compiere/model/CalloutInvoice.java
  base/src/org/compiere/model/CalloutOrder.java
  base/src/org/compiere/model/MPriceList.java
Labels: (AR) Account Receivable, (SO) Sales Management, 02 bug

#2628 Fixed some error with pacjout and packin
  base/src/org/adempiere/pipo/AbstractElementHandler.java
  base/src/org/adempiere/pipo/AttributeFiller.java
  base/src/org/adempiere/pipo/IDFinder.java
  base/src/org/adempiere/pipo/PackInHandler.java
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
  base/src/org/adempiere/pipo/handler/MenuElementHandler.java
  base/src/org/adempiere/pipo/handler/ReportViewElementHandler.java
  base/src/org/adempiere/pipo/handler/TableElementHandler.java
  base/src/org/adempiere/pipo/handler/WindowElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowNodeElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowNodeNextConditionElementHandler.java
  base/src/org/adempiere/pipo/handler/WorkflowNodeNextElementHandler.java
  base/src/org/compiere/model/PO.java
Labels: (PIO) Packin / Packout, 02 bug

#2617 Add feature for include changes to notify for myself
  base/src/org/compiere/model/I_AD_User.java
  base/src/org/compiere/model/X_AD_User.java
  migration/392lts-393lts/04690_Add_My_Own_Changes_Flag.xml
  org.adempiere.project/src/main/java/org/compiere/util/ProjectProcessorUtils.java
  org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
Labels: (PM) Project Management, (RM) Request Management, 01 enhancement

#2605 Add support to payroll account for payment selection from payroll
  base/src/org/compiere/model/MPaySelectionCheck.java
Labels: (FIM) Financial Management, (HRM) Human Resource and Payroll Management, 01 enhancement

#2593 Add support to commission type
  base/src/org/adempiere/model/MViewColumn.java
  base/src/org/compiere/model/I_C_Commission.java
  base/src/org/compiere/model/I_C_CommissionType.java
  base/src/org/compiere/model/MCommissionRun.java
  base/src/org/compiere/model/MCommissionType.java
  base/src/org/compiere/model/X_C_Commission.java
  base/src/org/compiere/model/X_C_CommissionRun.java
  base/src/org/compiere/model/X_C_CommissionType.java
  migration/392lts-393lts/04661_2173_Add_Dynamic_Commission.xml
Labels: (COM) Commission, 01 enhancement

#2635 Fixed error with Mail text for values
  org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
Labels: (RM) Request Management, 02 bug

#2636 Fixed error with overwrite Smart Browser for Where clause
  client/src/org/compiere/apps/APanel.java
  client/src/org/eevolution/form/VBrowser.java
  org.adempiere.pos/src/main/java/ui/swing/org/adempiere/pos/POSActionMenu.java
  zkwebui/WEB-INF/src/org/eevolution/form/WBrowser.java
Labels: (SB) Smart Browser, 02 bug

#2637 Fixed Error with parent UUID reference for packout
  base/src/org/adempiere/pipo/AbstractElementHandler.java
  base/src/org/adempiere/pipo/IDFinder.java
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Labels: (PIO) Packin / Packout, 02 bug

#2630 Fixed ASP error for fields
  base/src/org/compiere/model/MTab.java
Labels: 02 bug

#2634 #2555 Printing Orders with Jasper Reports do not work anymore https:…
  base/src/org/compiere/print/ServerReportCtl.java
Labels: (PF) Report Engine & Print Format, 02 bug

#2599 #2598 The accounting information screen does not show the accounting …
  base/src/org/compiere/report/core/RColumn.java
  client/src/org/compiere/acct/AcctViewerData.java
  zkwebui/WEB-INF/src/org/adempiere/webui/acct/WAcctViewerData.java
Labels: (AC) Accounting, (PA) Performance Analysis and General Ledger, 02 bug

#2640 Fixed problem with new value as null, this bug was introduced by myself
  base/src/org/compiere/model/PO.java
Labels: 02 bug

#2643 Add support to parent column and order column for tree window
  base/src/org/compiere/model/I_AD_Tree.java
  base/src/org/compiere/model/MTree.java
  base/src/org/compiere/model/PO.java
  base/src/org/compiere/model/X_AD_Tree.java
  base/src/org/compiere/process/TreeMaintenance.java
  client/src/org/compiere/grid/GridController.java
  client/src/org/compiere/grid/tree/AdempiereTreeModel.java
  client/src/org/compiere/grid/tree/VTreePanel.java
  migration/392lts-393lts/04720_Add_Support_to_Tree_Search_Field.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/component/ADTreeOnDropListener.java
Labels: 01 enhancement, 14 Waiting for User Changes

#2650 Add support to multi-reference for Mail text
  org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
Labels: 01 enhancement

#2649 Fixed error with Smart Browse for ASP on ZK UI
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (SB) Smart Browser, 02 bug

#2648 Fixed error with date for Browse row from ZK
  zkwebui/WEB-INF/src/org/eevolution/grid/WBrowserListItemRenderer.java
Labels: (SB) Smart Browser, 02 bug

#2647 Add support to browser translation menu
  base/src/org/compiere/process/SynchronizeTerminology.java
Labels: (SB) Smart Browser, 02 bug

#2644 Add table to Smart Browser export
  base/src/org/adempiere/pipo/handler/ViewElementHandler.java
Labels: (PIO) Packin / Packout, 02 bug

#2632 Add Custom Exporter functionality
  base/src/org/adempiere/pipo/PackOut.java
  base/src/org/compiere/model/I_AD_Package_Exp_Detail.java
  base/src/org/compiere/model/X_AD_Package_Exp_Detail.java
  base/src/org/spin/model/I_AD_Package_Exp_Custom.java
  base/src/org/spin/model/MADPackageExpCustom.java
  base/src/org/spin/model/X_AD_Package_Exp_Custom.java
  base/src/org/spin/util/impexp/TestPackoutExporter.java
  migration/392lts-393lts/04720_Add_Custom_Exporter.xml
  migration/392lts-393lts/04730_Add_Custom_Exporter_Test_Data.xml
Labels: (PIO) Packin / Packout, 01 enhancement

#2638 Fixed error with timestamp values
  base/src/org/adempiere/pipo/PoFiller.java
Labels: (PIO) Packin / Packout, 02 bug

#2641 Add support to updated values for overwrite local changes
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Labels: (PIO) Packin / Packout, 02 bug

#2642 Add displaycolumn value for Lookup Info
  base/src/org/compiere/model/MLookupFactory.java
Labels: 02 bug

#2652 fixed error with translation overwrite for process
  base/src/org/compiere/model/MPInstance.java
Labels: (SC) System Core, 02 bug

#2653 #2631 The Credit Used does not update when receiving payment! https:/…
  base/src/org/compiere/model/MAllocationHdr.java
  base/src/org/compiere/model/MBPartner.java
  base/src/org/compiere/model/MCommissionRun.java
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/MPayment.java
  db/ddlutils/mysql/functions/C_Invoice_Open.sql
  db/ddlutils/mysql/functions/C_Invoice_OpenToDate.sql
  db/ddlutils/mysql/functions/C_Invoice_Paid.sql
  db/ddlutils/mysql/functions/C_Invoice_PaidToDate.sql
  db/ddlutils/mysql/functions/C_Payment_Allocated.sql
  db/ddlutils/mysql/functions/C_Payment_Available.sql
  sqlj/src/org/compiere/sqlj/Invoice.java
  sqlj/src/org/compiere/sqlj/Payment.java
Labels: (AR) Account Receivable, 01 enhancement, 02 bug

#2619 Feature/#attachment nextcloud integration
  .classpath
  base/build.xml
  base/src/org/compiere/model/I_AD_ClientInfo.java
  base/src/org/compiere/model/MArchive.java
  base/src/org/compiere/model/MAttachment.java
  base/src/org/compiere/model/MImage.java
  base/src/org/compiere/model/X_AD_ClientInfo.java
  base/src/org/spin/model/I_AD_AttachmentReference.java
  base/src/org/spin/model/MADAppRegistration.java
  base/src/org/spin/model/MADAttachmentReference.java
  base/src/org/spin/model/X_AD_AttachmentReference.java
  base/src/org/spin/process/SetupFileStorageSystem.java
  base/src/org/spin/process/SetupFileStorageSystemAbstract.java
  base/src/org/spin/util/AttachmentUtil.java
  base/src/org/spin/util/support/webdav/SardineAPI.java
  base/src/org/spin/util/support/webdav/SardineResource.java
  migration/392lts-393lts/04721_Add_Nextcloud_Integration_For_attachment.xml
  migration/392lts-393lts/04722_Add_Nextcloud_Data_For_GardenWorld.xml
  tools/build.xml
  tools/lib/commons-codec-1.10.jar
  tools/lib/commons-codec-1.6.jar
  tools/lib/fluent-hc-4.5.6.jar
  tools/lib/httpclient-4.5.6.jar
  tools/lib/httpclient-cache-4.5.6.jar
  tools/lib/httpclient-win-4.5.6.jar
  tools/lib/httpcore-4.4.10.jar
  tools/lib/httpmime-4.5.6.jar
  tools/lib/jna-4.4.0.jar
  tools/lib/jna-platform-4.4.0.jar
  tools/lib/sardine-5.9-SNAPSHOT.jar
Labels: (SC) System Core, 01 enhancement
