Repository adempiere/adempiere, pull requests merged in 2019-09, with the labels that each got.

#2753 Add Vehicle Group Window
  migration/392lts-393lts/05160_Add_Vehicle_Group_Window.xml
Labels: (DFM) Fleet Management, 01 enhancement

#2752 Add filter by Product Category on Generate Cost Process
  base/src/org/eevolution/process/GenerateCostDetail.java
  base/src/org/eevolution/process/GenerateCostDetailAbstract.java
  migration/392lts-393lts/05120_Add_ProductCategoryFilter_on_GenerateCost_Process.xml
Labels: (CM) Costing Management

#2761 Fixed error with NPE for search from report
  client/src/org/compiere/print/Viewer.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Labels: (UI) User Interface Improvement, 02 bug

#2760 Add text for process report footer, reference to issue: #2665
  base/src/org/spin/model/I_HR_ProcessReportTemplate.java
  base/src/org/spin/model/X_HR_ProcessReportTemplate.java
  migration/392lts-393lts/05030_Add_Payroll_Process_Template_Message.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/process/PayrollProcessReport.java
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement

#2757 Fixed error with uom for outbound order frolm form for generate outbound
  org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java
  org.eevolution.warehouse/src/main/java/ui/zk/org/spin/form/WOutBoundOrder.java
Labels: 02 bug

#2750 Feature/#2747 generate freight order from outbound
  base/src/org/eevolution/model/X_DD_FreightLine.java
  migration/392lts-393lts/05120_2747_Add_Generate_Freight_Order_from_Outbound_Order.xml
  org.eevolution.fleet/src/main/java/base/org/eevolution/model/MDDFreightLine.java
  org.eevolution.fleet/src/main/java/base/org/spin/process/GenerateFreightOrderFromOutbound.java
  org.eevolution.fleet/src/main/java/base/org/spin/process/GenerateFreightOrderFromOutboundAbstract.java
  org.eevolution.freight/src/main/java/base/org/compiere/model/MFreight.java
Labels: (DFM) Fleet Management, (WMS) Warehouse Management System, 01 enhancement

#2762 Fixed error with missing column for Freight Orders
  migration/392lts-393lts/05190_Column_Processing_Does_Not_Exists.xml
Labels: (WMS) Warehouse Management System, 02 bug

#2765 Add Report for Outbound order detail
  migration/392lts-393lts/05220_Add_Outbound_Detail.xml
Labels: (WMS) Warehouse Management System, 01 enhancement

#2767 Add Columns for search by Sales Representative Name and Price List Name
  base/src/org/compiere/process/ImportInvoice.java
  migration/392lts-393lts/05170_Add_Columms_To_Import_Invoice.xml
Labels: (CI) Code Improvement or Optimization, (MNC) Minor Change

#2764 NPE when execute financial report using Print Format Header #2759
  base/src/org/compiere/print/MPrintFormat.java
  base/src/org/compiere/print/layout/LayoutEngine.java
  base/src/org/compiere/report/FinReport.java
Labels: (FIM) Financial Management, (PF) Report Engine & Print Format, 02 bug

#2766 #2631 The Credit Used does not update when receiving payment!
  base/src/org/compiere/model/MAllocationHdr.java
  base/src/org/compiere/model/MInvoice.java
Labels: (AP) Account Payable, (AR) Account Receivable

#2771 Replace Report view where clause and fix missing reference
  migration/392lts-393lts/05220_Add_Outbound_Detail.xml
Labels: (DFM) Fleet Management, (WMS) Warehouse Management System, 01 enhancement

#2770 Remove missing column XML
  migration/392lts-393lts/05120_2747_Add_Generate_Freight_Order_from_Outbound_Order.xml
Labels: (DFM) Fleet Management, (WMS) Warehouse Management System, 01 enhancement

#2777 Add report View for Storage Detail:
  migration/392lts-393lts/05250_Add_Report_View_Storage_Detail.xml
Labels: (MM) Material Management, (PF) Report Engine & Print Format, 01 enhancement

#2774 Add support to BOM for Production Batch Order and production for one
  base/src/org/compiere/model/I_M_Production.java
  base/src/org/compiere/model/I_M_ProductionBatch.java
  base/src/org/compiere/model/MProduction.java
  base/src/org/compiere/model/X_M_Production.java
  base/src/org/compiere/model/X_M_ProductionBatch.java
  migration/392lts-393lts/05230_Add_BOM_ProductionBatch.xml
Labels: (MM) Material Management, (PLH) Production Light, 01 enhancement

#2778 Bugfix/#2437 next line with shift intro
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADWindowPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (UI) User Interface Improvement, 02 bug

#2776 Add Reactivate It support to Outbound
  org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
Labels: (WMS) Warehouse Management System, 01 enhancement

#2779 Add Print format for Production Batch
  migration/392lts-393lts/05260_Add_Production_Batch_PrintFormat.xml
Labels: (MM) Material Management, (PLH) Production Light, 01 enhancement

#2784 Fixed error with reload for movements on action notice
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/service/HRActionNotice.java
  org.eevolution.hr_and_payroll/src/main/java/ui/swing/org/eevolution/form/VHRActionNotice.java
  org.eevolution.hr_and_payroll/src/main/java/ui/zk/org/eevolution/form/WHRActionNotice.java
Labels: (HRM) Human Resource and Payroll Management, 02 bug

#2780 Add Parameters for reporte Shipment Details
  migration/392lts-393lts/05270_Add_Parameters_Shipment_Details_Report.xml
Labels: (MM) Material Management, (PF) Report Engine & Print Format, 01 enhancement

#2754 Feature/#sc add print document from process
  base/src/org/compiere/model/PO.java
  base/src/org/compiere/process/IPrintDocument.java
  base/src/org/compiere/process/SvrProcess.java
  migration/392lts-393lts/05140_Add_Print_Dcoument_Message.xml
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VPrintDocument.java
  zkwebui/WEB-INF/src/org/eevolution/form/WPrintDocument.java
Labels: (CI) Code Improvement or Optimization, (SC) System Core, 01 enhancement

#2793 Add Print format to payment selection
  migration/392lts-393lts/05280_Add_PaymentSelection_PrintFormat.xml
Labels: (AP) Account Payable, 01 enhancement

#2795 Fixed error with payment selection bad for account of bpartner
  base/src/org/compiere/model/MPaySelection.java
Labels: (AP) Account Payable, 02 bug, 10 Reviewed by Peer

#2801 Add process for reverse payments from Payment Selection
  base/src/org/spin/process/PaySelectionReversePayment.java
  base/src/org/spin/process/PaySelectionReversePaymentAbstract.java
  migration/392lts-393lts/05290_Add_Reverse_Payment_PaySelection.xml
Labels: (AP) Account Payable, 01 enhancement

#2803 Set document no for payment from payment selection
  base/src/org/compiere/model/MPaySelectionCheck.java
Labels: (AP) Account Payable, 02 bug

#2789 Add support to print invoices automatically
  org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java
Labels: (WMS) Warehouse Management System, 01 enhancement

#2805 Fixed error with exporter when a print format is changed
  client/src/org/compiere/print/Viewer.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewer.java
Labels: (PF) Report Engine & Print Format, 02 bug

#2806 Add document actions for freight order
  org.eevolution.fleet/src/main/java/base/org/eevolution/model/MDDFreight.java
Labels: (DM) Distribution Management, 01 enhancement

#2810 Add process for send remittance mail
  base/src/org/spin/process/PaySelectionSendRemittance.java
  base/src/org/spin/process/PaySelectionSendRemittanceAbstract.java
  migration/392lts-393lts/05380_2809_Add_Remittance_Send_Mail.xml
Labels: (AP) Account Payable, 01 enhancement

#2808 fixed error with void action for production in progress
  base/src/org/compiere/model/MProduction.java
Labels: (MM) Material Management, (PLH) Production Light, 02 bug, 10 Reviewed by Peer

#2813 Fixed error with Menu field length
  migration/392lts-393lts/05370_2812_Fixed_Synchronize_Terminology.xml
Labels: (AD) Application Dictionary, (TRL) Translation, 02 bug, 10 Reviewed by Peer

#2814 Feature/#2798 add payment export class
  base/src/org/compiere/model/I_C_BankAccount.java
  base/src/org/compiere/model/I_C_DocType.java
  base/src/org/compiere/model/X_C_BankAccount.java
  base/src/org/compiere/model/X_C_DocType.java
  client/src/org/compiere/apps/form/PayPrint.java
  migration/392lts-393lts/05280_Add_Pyment_Export_class_for_Payroll.xml
Labels: (AP) Account Payable, (HRM) Human Resource and Payroll Management, 01 enhancement, 10 Reviewed by Peer

#2817 Fixed error with duplicate reference from bank statement match to
  client/src/org/spin/apps/form/BankStatementMatchController.java
Labels: (BM) Bank Management, 02 bug

#2818 Add support to create payment from Bank Statement
  base/src/org/compiere/model/I_AD_OrgInfo.java
  base/src/org/compiere/model/I_C_Payment.java
  base/src/org/compiere/model/X_AD_OrgInfo.java
  base/src/org/compiere/model/X_C_Payment.java
  base/src/org/compiere/process/BankStatementPayment.java
  base/src/org/compiere/process/BankStatementPaymentAbstract.java
  migration/392lts-393lts/05390_Add_BankStatement_Create_Payment_SB.xml
Labels: (AP) Account Payable, (BM) Bank Management, 01 enhancement, 10 Reviewed by Peer

#2821 adempiere #2797 [Bug Report] Error Trial Balance
  client/src/org/compiere/apps/form/TrialBalanceDrill.java
Labels: (PA) Performance Analysis and General Ledger, 02 bug

#2756 Fixed error with import bpartner
  base/src/org/compiere/process/ImportBPartner.java
Labels: 02 bug, 09 Pending Peer Review, 10 Reviewed by Peer

#2758 Resolve problem with printing margin for iReport
  JasperReports/src/org/compiere/report/ReportStarter.java
Labels: (PF) Report Engine & Print Format, 02 bug

#2826 Add validation for Collect when it alreasy exist for deposit
  base/src/org/compiere/model/MPayment.java
  migration/392lts-393lts/05410_Add_Reverse_Collect_Validation.xml
Labels: (AP) Account Payable, (AR) Account Receivable, 02 bug

#2822 Add support to unidentified payments for Bank
  base/src/org/compiere/acct/Doc.java
  base/src/org/compiere/acct/Doc_AllocationHdr.java
  base/src/org/compiere/acct/Doc_Payment.java
  base/src/org/compiere/model/I_AD_OrgInfo.java
  base/src/org/compiere/model/MOrgInfo.java
  base/src/org/compiere/model/MPayment.java
  base/src/org/compiere/model/X_AD_OrgInfo.java
  base/src/org/compiere/model/X_C_Payment.java
  base/src/org/compiere/process/BankStatementPayment.java
  base/src/org/compiere/process/LoadBankStatement.java
  base/src/org/compiere/process/LoadBankStatementAbstract.java
  base/src/org/spin/process/PaymentIdentify.java
  base/src/org/spin/process/PaymentIdentifyAbstract.java
  db/ddlutils/oracle/views/RV_PAYMENT.sql
  db/ddlutils/postgresql/views/RV_PAYMENT.sql
  migration/392lts-393lts/05400_Add_Unidentified_Payment_Support.xml
Labels: (AP) Account Payable, (AR) Account Receivable, (FIM) Financial Management, 01 enhancement, 09 Pending Peer Review

#2827 Add document type for withdrawal and deposit from cash
  base/src/org/spin/process/DepositFromCash.java
  base/src/org/spin/process/DepositFromCashAbstract.java
  migration/392lts-393lts/05410_Add_DocumentType_Deposit_From_Cash.xml
Labels: (AP) Account Payable, 01 enhancement

#2832 Fix XML Script to Release 3.9.3
  migration/392lts-393lts/05032_Add_Payroll_Process_Template_Message.xml
  migration/392lts-393lts/05121_Add_ProductCategoryFilter_on_GenerateCost_Process.xml
  migration/392lts-393lts/05130_Add_SB_Generate_Invoice_From_Outbound_Order.xml
  migration/392lts-393lts/05170_Add_Columms_To_Import_Invoice.xml
  migration/392lts-393lts/05281_Add_Pyment_Export_class_for_Payroll.xml
  migration/392lts-393lts/05282_Add_Reverse_Payment_PaySelection.xml
Labels: (SC) System Core, 01 enhancement

#2829 Fixed error with transit quantity when a Outbound order is delivered
  org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java
  org.eevolution.warehouse/src/main/java/ui/zk/org/spin/form/WOutBoundOrder.java
Labels: (WMS) Warehouse Management System, 02 bug

#2835 adempiere #2834 [Bug Report] Trial Balance error in line 333
  client/src/org/compiere/apps/form/TrialBalanceDrill.java
Labels: 02 bug

#2824 adempiere #2823 POS Order when using configuration "Cash_As_Payment"
  base/src/org/compiere/model/MBankAccount.java
  base/src/org/compiere/model/MInvoice.java
  migration/392lts-393lts/05400_Msg_BankAccountNotFound.xml
Labels: (POS) Point Of Sales, (SO) Sales Management, 09 Pending Peer Review, 12 Feature

#2820 #2819 WPOS PosKeylayout small adjustments
  org.adempiere.pos/src/main/java/base/org/adempiere/pos/service/CPOS.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOS.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSKeyPanel.java
Labels: 12 Feature
