Repository adempiere/adempiere, pull requests merged in 2020-06, with the labels that each got.

#3130 Get Resource from Attachment reference
  base/src/org/spin/util/AttachmentUtil.java
Labels: 01 enhancement

#3094 Fix Landed Costs Accounting, when Vendor invoice is in another currency
  base/src/org/adempiere/engine/CostEngine.java
  base/src/org/compiere/acct/Doc_Invoice.java
  base/src/org/compiere/model/MLandedCostAllocation.java
Labels: (AP) Account Payable, (CM) Costing Management, 02 bug

#3133 Add support to File Size for Attachment reference
  base/src/org/compiere/model/MAttachment.java
  base/src/org/compiere/model/MImage.java
  base/src/org/spin/model/I_AD_AttachmentReference.java
  base/src/org/spin/model/X_AD_AttachmentReference.java
  base/src/org/spin/util/AttachmentUtil.java
  migration/393lts-394lts/05820_Add_File_Size_to_Attachment_Reference.xml
Labels: (UI) User Interface Improvement, 01 enhancement

#3135 Add Amazon s3 storage support
  .classpath
  base/build.xml
  base/src/org/spin/util/support/aws3/AmazonWS3.java
  base/src/org/spin/util/support/aws3/AmazonWS3Resource.java
  migration/393lts-394lts/05830_Add_AmazonS3_API_Support.xml
  tools/lib/aws-java-sdk-core-1.11.795.jar
  tools/lib/aws-java-sdk-kms-1.11.795.jar
  tools/lib/aws-java-sdk-s3-1.11.795.jar
Labels: (SA) System Administrator, 01 enhancement

#3137 Fixed error with price list conversion when it does not exist on map
  base/src/org/compiere/process/M_PriceList_Create.java
Labels: 02 bug

#3139 This change allows return report as file for get this on any UI
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/process/PayrollProcessReport.java
Labels: (HRM) Human Resource and Payroll Management, (UI) User Interface Improvement

#3140 Fixed error with bad index for whole word on column names for query and
  base/src/org/compiere/model/MRole.java
Labels: (SC) System Core, (SE) Security, 02 bug

#3142 Error when Generate Shipment and Invoice and selection multiples rows
  base/src/org/compiere/process/ProcessInfoUtil.java
  client/src/org/compiere/apps/form/InOutGen.java
  client/src/org/compiere/apps/form/InvoiceGen.java
Labels: (AR) Account Receivable, 02 bug

#3145 Fixed error with create customization from Menu when a menu is not
  base/src/org/adempiere/process/CreateCustomizationFromASP.java
Labels: 02 bug

#3147 Fixed error with duplicated key for ServerProcessCtl
  base/src/org/compiere/process/ProcessInfo.java
  base/src/org/compiere/process/ServerProcessCtl.java
  base/src/org/eevolution/service/dsl/ProcessBuilder.java
  client/src/org/compiere/apps/ProcessCtl.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/OrderDistribution.java
Labels: (SC) System Core, 02 bug

#3148 Add process for copy custom fields from other custom tab
  base/src/org/compiere/model/MFieldCustom.java
  base/src/org/spin/process/ASPCopyFromTab.java
  base/src/org/spin/process/ASPCopyFromTabAbstract.java
  migration/393lts-394lts/05840_Add_ASP_Copy_from_Customized_Tab.xml
Labels: (SA) System Administrator, 01 enhancement, 12 Feature

#3150 Fixed error with Smart Browser for Create Role Process from Window
  migration/393lts-394lts/05850_Fixed_error_with_Role_Create_From_Window.xml
Labels: (SC) System Core, 02 bug

#3152 Fixed print preview for reports
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/process/PayrollProcessReport.java
Labels: (HRM) Human Resource and Payroll Management, 02 bug
