Repository adempiere/adempiere, pull requests merged in 2020-03, with the labels that each got.

#3035 Fixed error with event indicator for pending documents
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusIndicator.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WDocumentStatusPanel.java
Labels: (UI) User Interface Improvement, 02 bug, 10 Reviewed by Peer

#3041 Add document Flag by default
  migration/393lts-394lts/05610_Fixed_document_flag_for_tables.xml
Labels: (SC) System Core, 02 bug, 10 Reviewed by Peer, 14 Waiting for User Changes

#3015 Fixed error with wrong reference for export menu from application or
  base/src/org/adempiere/pipo/handler/MenuElementHandler.java
Labels: (PIO) Packin / Packout, 02 bug, 10 Reviewed by Peer

#3028 Add support to import attribute set instance for import inventory
  base/src/org/compiere/model/I_I_Inventory.java
  base/src/org/compiere/model/X_I_Inventory.java
  base/src/org/compiere/process/ImportInventory.java
  migration/392lts-393lts/05580_Add_Attribute_set_instance_search_for_import_inventory.xml
  migration/393lts-394lts/05580_Add_Attribute_set_instance_search_for_import_inventory.xml
Labels: (MM) Material Management, 01 enhancement, 10 Reviewed by Peer, 14 Waiting for User Changes

#2394 adempiere #1662 ValuationEffectiveDate only for costing level warehouse
  base/src/org/eevolution/process/ValuationEffectiveDate.java
Labels: (CM) Costing Management, 02 bug, 13 Pending Acceptance

#3043 Fixed error with overwrite parameters for process when they are changed
  base/src/org/compiere/process/SvrProcess.java
Labels: (SA) System Administrator, 02 bug

#3060 Fixed error with not displayed browse key
  base/src/org/spin/util/ASPUtil.java
  migration/393lts-394lts/05600_Fixed_error_with_browse_key.xml
Labels: (AD) Application Dictionary, 02 bug

#3063 Fixed error with StackOverFlow for MColumn
  base/src/org/compiere/model/MColumn.java
Labels: (AD) Application Dictionary, 02 bug

#3066 Fixed error with default value when a field is Date instead Date + Time
  base/src/org/compiere/model/GridField.java
Labels: (SC) System Core, 02 bug

#3042 Add Invoice Order support
  base/src/org/compiere/model/I_C_DocType.java
  base/src/org/compiere/model/MOrder.java
  base/src/org/compiere/model/X_C_DocType.java
  migration/393lts-394lts/05620_Add_Invoice_Order.xml
  migration/393lts-394lts/05630_Add_Invoice_Order_Example_Data_for_Garden_World.xml
Labels: (POS) Point Of Sales, (SO) Sales Management, 01 enhancement, 10 Reviewed by Peer

#3049 Fixed error with AND condition for replenish report
  base/src/org/compiere/process/ReplenishReport.java
Labels: (MM) Material Management, 02 bug

#3062 Fixed error with commission group for commission run
  base/src/org/compiere/model/MCommissionGroup.java
  base/src/org/compiere/model/MCommissionRun.java
Labels: (COM) Commission, 02 bug

#3077 Fixed error with axis column for Smart Browser
  client/src/org/eevolution/grid/Browser.java
Labels: (SC) System Core, 02 bug

#3079 #3045 NPE when try create fields for a GridTabVO https://github.com/…
  base/src/org/compiere/model/GridTabVO.java
Labels: (SC) System Core, 02 bug

#3065 Add Product Group, Product Class and Product Classification for Price
  base/src/org/compiere/model/I_M_DiscountSchemaLine.java
  base/src/org/compiere/model/X_M_DiscountSchemaLine.java
  base/src/org/compiere/process/M_PriceList_Create.java
  base/src/org/compiere/process/M_PriceList_CreateAbstract.java
  migration/393lts-394lts/05760_Add_Product_Class_and_Classification_for_Price_List_Calc.xml
Labels: (MM) Material Management, (SO) Sales Management, 01 enhancement

#3075 Remove old implementation for save and selection
  base/src/org/compiere/process/InvoiceGenerate.java
  base/src/org/compiere/process/InvoiceGenerateAbstract.java
Labels: (CI) Code Improvement or Optimization, (MNC) Minor Change

#3069 Add Process for Open POS cash
  base/src/org/eevolution/process/BankTransfer.java
  base/src/org/eevolution/process/BankTransferAbstract.java
  migration/393lts-394lts/05650_Add_POS_Open_process.xml
Labels: (POS) Point Of Sales, 01 enhancement

#3072 Allows more tender types for payments
  migration/393lts-394lts/05730_Add_Tender_Types_for_Payments.xml
Labels: (AR) Account Receivable, (POS) Point Of Sales, 01 enhancement, 10 Reviewed by Peer, 14 Waiting for User Changes

#3074 remove old implementation for Generate InOut process
  base/src/org/compiere/process/InOutGenerate.java
  base/src/org/compiere/process/InOutGenerateAbstract.java
  client/src/org/compiere/apps/form/InOutGen.java
  client/src/org/compiere/apps/form/InvoiceGen.java
Labels: (CI) Code Improvement or Optimization, (MNC) Minor Change, 10 Reviewed by Peer

#3078 fixed error with conversion rate for bank statement from payment
  base/src/org/compiere/model/MBankStatementLine.java
Labels: (BM) Bank Management, 02 bug, 10 Reviewed by Peer, 17 Waiting for Information

#3064 Allows export Packout from ZK web UI
  base/src/org/adempiere/pipo/PackOut.java
Labels: (PIO) Packin / Packout, 01 enhancement, 10 Reviewed by Peer

#3068 Allows a payment reference with payment amount as Zero
  base/src/org/compiere/model/MBankStatementLine.java
Labels: (BM) Bank Management, 02 bug

#3071 Allows multy-currency for POS Withdrawal
  migration/393lts-394lts/05770_Add_C_ConversionType_C_POS.xml
  migration/393lts-394lts/05780_Add_supportto_currency_for_Withdrawal.xml
  org.adempiere.pos/src/main/java/base/org/adempiere/pos/process/GenerateWithdrawal.java
Labels: (POS) Point Of Sales, 01 enhancement

#3082 Add cash closing correct values
  migration/393lts-394lts/05790_Fixes_error_with_POS_Cash_Closing.xml
Labels: (POS) Point Of Sales, 02 bug

#3084 Remove old implementation for save method
  org.adempiere.asset/src/main/java/base/org/compiere/FA/model/ModelValidator.java
Labels: (CI) Code Improvement or Optimization

#3083 Add support to FileName or path for Migration Loader and change log
  base/src/org/adempiere/process/ApplyMigrationScripts.java
  base/src/org/adempiere/process/MigrationLoader.java
  base/src/org/compiere/process/MigrationFromXML.java
  utils/RUN_MigrateXML.bat
  utils/RUN_MigrateXML.sh
Labels: (MT) Migration Tools, 01 enhancement

#3087 Add support to Deliver Asset Browser
  base/src/org/compiere/model/I_A_Asset_Delivery.java
  base/src/org/compiere/model/X_A_Asset_Delivery.java
  migration/393lts-394lts/05780_3085_Add_Delivery_Asset_Browser.xml
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetDelivery.java
  org.adempiere.asset/src/main/java/base/org/compiere/process/AssetDelivery.java
  org.adempiere.asset/src/main/java/base/org/compiere/process/AssetDeliveryAbstract.java
Labels: (FAM) Fixed Asset Management, 01 enhancement, 10 Reviewed by Peer
