Repository adempiere/adempiere, pull requests merged in 2020-09, with the labels that each got.

#3216 #3215 [Bug Report] Critical error with Never ending process https://g…
  base/src/org/compiere/wf/MWFActivity.java
Labels: (BPM) Workflow Engine, 02 bug

#3224 Fixed error with setup file when it is getted from external storage
  base/src/org/spin/process/SetupFileStorageSystem.java
Labels: 02 bug

#3225 Bug fix of possible error in SQL conversion from Oracle to Any DB
  base/src/org/compiere/dbPort/Convert.java
  base/src/org/compiere/dbPort/Convert_MariaDB.java
  base/src/org/compiere/dbPort/Convert_MySQL.java
  base/src/org/compiere/dbPort/Convert_PostgreSQL.java
  base/src/org/compiere/dbPort/Convert_PostgreSQLTest.java
Labels: (SC) System Core, 02 bug

#3227 Add Grand Total of Order for POS Cash Closing
  migration/393lts-394lts/06510_Add_Grand_Total_for_Cash_Closing.xml
Labels: (POS) Point Of Sales, 01 enhancement

#3226 Add Date Acct to Financial Batch
  base/src/org/spin/model/I_FM_Batch.java
  base/src/org/spin/model/X_FM_Batch.java
  migration/393lts-394lts/06510_Add_Accounting_Date_to_FM_Batch.xml
  org.spin.finance_management/src/main/java/base/org/compiere/acct/Doc_FMBatch.java
Labels: (FIM) Financial Management, 02 bug
