Repository adempiere/adempiere, pull requests merged in 2020-02, with the labels that each got.

#2971 #2968 Enable Sign Change for Calculated Lines in Financial Reports
  migration/393lts-394lts/05560_2968_ShowOppositeSignForALineCalculated.xml
Labels: (FIM) Financial Management, 02 bug

#2946 #2945 Freight Engine does not use the Shipper the Outbound Order to c…
  org.eevolution.freight/src/main/java/base/org/eevolution/engine/freight/FreightRule.java
  org.eevolution.freight/src/main/java/base/org/eevolution/model/FreightModelValidator.java
Labels: (WMS) Warehouse Management System, 02 bug

#2078 #213 Add ability to automatically synchronize table and column changes with the database.
  base/src/org/adempiere/process/SynchronizeAllTablesAndColumns.java
  base/src/org/adempiere/process/SynchronizeAllTablesAndColumnsAbstract.java
  base/src/org/compiere/model/I_AD_Column.java
  base/src/org/compiere/model/I_AD_Table.java
  base/src/org/compiere/model/MColumn.java
  base/src/org/compiere/model/MTable.java
  base/src/org/compiere/model/M_Element.java
  base/src/org/compiere/model/POInfo.java
  base/src/org/compiere/model/X_AD_Column.java
  base/src/org/compiere/model/X_AD_Table.java
  base/src/org/compiere/util/DB.java
  base/src/org/compiere/util/DisplayType.java
  migration/393lts-release/05550_0213_AutomaticAndProcessSync.xml
Labels: (AD) Application Dictionary, 01 enhancement, 09 Pending Peer Review, 13 Pending Acceptance

#2970 #2969 Blanks for line, It is important to have the possibility that a…
  base/src/org/compiere/print/DataEngine.java
Labels: (PF) Report Engine & Print Format, 02 bug

#2935 Fixed error with duplicate key for inventory import
  base/src/org/compiere/process/ImportInventory.java
  base/src/org/compiere/process/ImportInventoryAbstract.java
Labels: (MM) Material Management, 02 bug

#2978 Fixed error with date for commission run
  base/src/org/compiere/model/MCommissionRun.java
Labels: (COM) Commission, 02 bug

#2982 Fixed error with validation for production batch when exists productions
  base/src/org/compiere/model/MProductionBatch.java
Labels: (PLH) Production Light, 02 bug

#2980 Fixed error with validation for dates on Create Leave Manual
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/LeaveCreditManual.java
Labels: (HRM) Human Resource and Payroll Management, 02 bug

#3003 adempiere #3002 bugfix NPE in MRequest save
  org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
Labels: 02 bug

#2781 fix bug in ExportFormatXML
  base/src/org/spin/util/ExportFormatXML.java
Labels: 02 bug, 10 Reviewed by Peer, 17 Waiting for Information, 19 Not reproducible

#3017 Fixed error with ambiguous reference for zoom across
  base/src/org/adempiere/model/GenericZoomProvider.java
Labels: (AD) Application Dictionary, 02 bug

#3018 Fixed error with overwrite parameters for process and smart browsers
  base/src/org/spin/util/ASPUtil.java
Labels: (UI) User Interface Improvement, 02 bug

#2994 adempiere #2993 Doc_Production: M_Locator_ID is not updated correctly
  base/src/org/compiere/acct/Doc_Production.java
Labels: 02 bug

#2981 Add source folder for TNA
  .classpath
Labels: 02 bug, 08 IDE

#2881 adempiere #2880 [Bug Report]2880 Not defined process
  migration/392lts-393lts/05510_DeactivateUnusedMenu.xml
Labels: (AD) Application Dictionary, 02 bug, 09 Pending Peer Review

#2979 Add support to duration based on week
  base/src/org/compiere/util/TimeUtil.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/util/TNAUtil.java
Labels: (SC) System Core, 02 bug

#3001 Support for LandedCostDistribution
  base/src/org/compiere/model/MInvoiceLine.java
Labels: (CM) Costing Management, 01 enhancement

#3025 Process StatementCreateFrom, amount in different currency is calculcated with an error
  base/src/org/compiere/process/StatementCreateFrom.java
Labels: (BM) Bank Management, 02 bug

#2976 #2975, Fixed error with round for AP / AR documents and Orders,
  base/src/org/compiere/model/CalloutInvoice.java
  base/src/org/compiere/model/CalloutOrder.java
  base/src/org/compiere/model/MInvoiceLine.java
  base/src/org/compiere/model/MOrderLine.java
Labels: (AP) Account Payable, (AR) Account Receivable, (PO) Purchase Management, (SO) Sales Management, 02 bug

#2951 Fix ambiguous column and optimize previous balance query in Financial Statement Report
  base/src/org/compiere/report/FinStatement.java
Labels: (FIM) Financial Management, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance

#3012 Fixed error with reference for table for packin
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Labels: (PIO) Packin / Packout, 02 bug

#2963 Add support to import Business Partner Bank Account
  base/src/org/compiere/model/I_I_BPartner.java
  base/src/org/compiere/model/MBPBankAccount.java
  base/src/org/compiere/model/MBPartnerLocation.java
  base/src/org/compiere/model/X_I_BPartner.java
  base/src/org/compiere/process/ImportBPartner.java
  migration/393lts-394lts/05570_Add_Support_to_Import_Business_Partner_Bank_Account.xml
Labels: (IO) Input/Output, (MNC) Minor Change, 10 Reviewed by Peer, 12 Feature

#3029 Bugfix/#requisition document action
  base/src/org/compiere/model/MRequisition.java
  base/src/org/compiere/process/DocumentEngine.java
Labels: (PO) Purchase Management, 02 bug

#3030 Fixed error with last month day for commission totally paid
  base/src/org/compiere/model/MCommissionRun.java
Labels: (COM) Commission, 02 bug

#3032 Generate abstract class for process generate in out
  base/src/org/compiere/process/InOutGenerate.java
  base/src/org/compiere/process/InOutGenerateAbstract.java
Labels: (CI) Code Improvement or Optimization, 01 enhancement

#3031 Add support to Sales region for Sales Order and Invoice
  base/src/org/compiere/model/CalloutOrder.java
  base/src/org/compiere/model/I_C_Invoice.java
  base/src/org/compiere/model/I_C_Order.java
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/MOrder.java
  base/src/org/compiere/model/X_C_Invoice.java
  base/src/org/compiere/model/X_C_Order.java
  migration/393lts-394lts/05590_1455_Add_Sales_Region_to_Order_and_Invoice.xml
Labels: (SO) Sales Management, 01 enhancement

#3011 Add clean definition for delete entities
  base/src/org/spin/model/I_AD_CleanDefinition.java
  base/src/org/spin/model/I_AD_CleanDefinitionTable.java
  base/src/org/spin/model/X_AD_CleanDefinition.java
  base/src/org/spin/model/X_AD_CleanDefinitionTable.java
  client/src/org/compiere/apps/form/DeleteEntityControler.java
  client/src/org/compiere/apps/form/VDeleteEntity.java
  migration/393lts-394lts/05570_Add_Clean_Definition_for_Client.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WDeleteEntity.java
Labels: (AD) Application Dictionary, 01 enhancement, 10 Reviewed by Peer

#2996 adempiere Payselection for Bank Transfers. Charge is not copied. PayAmt>Open Amount for invoices
  base/src/org/compiere/model/MPaySelectionCheck.java
Labels: (BM) Bank Management, 02 bug, 14 Waiting for User Changes

#3033 Add support to Sales representative based on sales region
  base/src/org/compiere/model/CalloutOrder.java
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/MOrder.java
  base/src/org/compiere/model/MSalesRegion.java
Labels: (SO) Sales Management, 01 enhancement

#3034 Fixed error with NPE for request when sender not have mail
  org.adempiere.request/src/main/java/org/compiere/model/MRequest.java
Labels: (RM) Request Management, 02 bug

#3036 Reset cache for App registration when a value is changed
  base/src/org/spin/model/MADAppRegistration.java
  base/src/org/spin/model/MADAppRegistrationPara.java
Labels: 02 bug

#3037 Fixed error with reload registration ID
  base/src/org/spin/util/support/AppSupportHandler.java
Labels: 02 bug
