Repository adempiere/adempiere, pull requests merged in 2020-11, with the labels that each got.

#3241 Add Sales Representative reference to payment
  base/src/org/compiere/model/I_C_Payment.java
  base/src/org/compiere/model/X_C_Payment.java
  db/ddlutils/oracle/views/C_PAYMENT_V.sql
  db/ddlutils/oracle/views/RV_PAYMENT.sql
  db/ddlutils/postgresql/views/C_PAYMENT_V.sql
  db/ddlutils/postgresql/views/RV_PAYMENT.sql
  migration/393lts-394lts/06550_Add_Collecting_Agent_Reference_to_Payment.xml
Labels: (AR) Account Receivable, (SC) System Core, 01 enhancement

#3235 Increase Business Partner Name and Name2 to 255
  migration/393lts-394lts/06490_Increase_Business_Partner_Name_and_Name_2.xml
Labels: (SC) System Core, 01 enhancement

#3233 Just add support to documents on replication strategy test process
  base/src/org/spin/process/rpl/exp/TestReplicationStrategy.java
Labels: (RPL) Replication Engine, 01 enhancement

#3242 Add Report View for show Cash waiting for Deposit
  migration/393lts-394lts/06560_Add_Report_View_for_Cash_waiting_for_Deposit.xml
Labels: (AR) Account Receivable, 01 enhancement

#3230 Add some fields for reference of Returns orders on Return Material
  migration/393lts-394lts/06520_Add_Fields_reference_to_Return_orders.xml
Labels: (RMA) Return Material Authorization, 01 enhancement

#3214 Add support to Days Due 8-14 ~ 15-30 and Past Due 8-14 ~ 15-30
  base/src/org/compiere/model/I_T_Aging.java
  base/src/org/compiere/model/MAging.java
  base/src/org/compiere/model/X_T_Aging.java
  base/src/org/compiere/process/Aging.java
  base/src/org/compiere/process/AgingAbstract.java
  migration/393lts-394lts/06490_Add_some_columns_for_Aging_report.xml
Labels: (SO) Sales Management, 01 enhancement

#3219 Add support to sales region for Open Item
  db/ddlutils/oracle/views/RV_OPENITEM.sql
  db/ddlutils/postgresql/views/RV_OPENITEM.sql
  migration/393lts-394lts/06490_Add_Parameter_Sales_Region_Open_Item.xml
Labels: 01 enhancement

#3220 Add columns to Open Item to date
  base/src/org/spin/report/OpenItemToDate.java
  base/src/org/spin/report/OpenItemToDateAbstract.java
  migration/393lts-394lts/06500_Add_Parameter_SalesRegion_Open_Item_To_Date.xml
Labels: 01 enhancement

#3243 Rename table for implementations of W_Catalog
  org.spin.store/src/main/java/org/spin/process/ExportCatalog.java
Labels: 02 bug

#3222 Fixed error with Sales Orders with cash as payment rule
  base/src/org/compiere/model/MInvoice.java
Labels: (AR) Account Receivable, (SO) Sales Management, 10 Reviewed by Peer

#3244 Add support to Return Order for Cash Closing
  migration/393lts-394lts/06640_Add_support_to_RMA_to_POS_Cash_Close.xml
Labels: (POS) Point Of Sales, 02 bug

#3221 #3217 MAttributeSet method excludeEntry() is misused https://github.…
  client/src/org/compiere/grid/ed/VPAttribute.java
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WPAttributeEditor.java
Labels: (MM) Material Management, 02 bug

#3237 Fixed error with transaction for Workflow approval
  base/src/org/compiere/wf/MWFActivity.java
Labels: (BPM) Workflow Engine, 02 bug

#3229 #3228 [Feature Request] Enhanced the product information to show the …
  client/src/org/compiere/apps/search/InfoProduct.java
  client/src/org/compiere/apps/search/InvoiceHistory.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InvoiceHistory.java
Labels: (MM) Material Management, 01 enhancement

#3246 remove outdated iText libs
  .classpath
  JasperReports/build.xml
  adempiere.iml
  base/ADempiere.launch
  base/src/org/adempiere/pdf/Document.java
  base/src/org/adempiere/pdf/IText7Document.java
  base/src/org/adempiere/pdf/ITextDocument.java
  base/src/org/adempiere/pdf/SmjPdfReport.java
  client/src/org/compiere/grid/VPanel.java
  org.adempiere.pos/adempierePOS.iml
  org.adempiere.pos/buildPOSClient.xml
  tools/build.xml
  tools/lib/iText-2.1.7.jar
  tools/lib/itext-pdfa-5.5.2.jar
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/AEnv.java
Labels: (PF) Report Engine & Print Format

#3249 Remove ID for Reference of Element created automatically
  base/src/org/compiere/model/MTable.java
Labels: (AD) Application Dictionary, 01 enhancement

#3248 Add standard values for iReport
  JasperReports/src/org/compiere/report/ReportStarter.java
Labels: (PF) Report Engine & Print Format, 01 enhancement

#3255 Minor change: Allows get ids of query as list instead array
  base/src/org/compiere/model/Query.java
Labels: (SC) System Core, 01 enhancement

#3256 Improve speed for test replication strategy
  base/src/org/spin/process/rpl/exp/TestReplicationStrategy.java
Labels: (RPL) Replication Engine, 01 enhancement

#3254 Add support to Corporate Branding Image for Organization Info
  base/src/org/compiere/model/I_AD_Org.java
  base/src/org/compiere/model/I_AD_OrgInfo.java
  base/src/org/compiere/model/X_AD_Org.java
  base/src/org/compiere/model/X_AD_OrgInfo.java
  migration/393lts-394lts/06900_Add_Price_Checking_Image_for_Organization.xml
Labels: (POS) Point Of Sales, 01 enhancement

#3247 Add support to account dimensions for movements based on employee, job
  base/src/org/eevolution/model/I_HR_Department.java
  base/src/org/eevolution/model/I_HR_Employee.java
  base/src/org/eevolution/model/I_HR_Job.java
  base/src/org/eevolution/model/X_HR_Department.java
  base/src/org/eevolution/model/X_HR_Employee.java
  base/src/org/eevolution/model/X_HR_Job.java
  migration/393lts-394lts/06580_Add_Account_Dimension_payroll_support.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
Labels: (HRM) Human Resource and Payroll Management, (PA) Performance Analysis and General Ledger, 01 enhancement

#3245 Bugfix/#fm transaction is closed
  .settings/org.eclipse.wst.common.component
  base/src/org/spin/model/I_FM_FunctionalApplicability.java
  base/src/org/spin/model/I_FM_Product.java
  base/src/org/spin/model/X_FM_FunctionalApplicability.java
  base/src/org/spin/model/X_FM_Product.java
  migration/393lts-394lts/06710_Add_some_reference_columns_to_FM_Transaction.xml
  migration/393lts-394lts/06730_Add_references_to_Financial_Management.xml
  migration/393lts-394lts/06780_Add_Freight_reference_to_Financial_Transaction.xml
  migration/393lts-394lts/06810_Add_Optional_Reversal_to_Functional_Setting_Applicability.xml
  org.spin.finance_management/src/main/java/base/org/spin/model/MFMAccount.java
  org.spin.finance_management/src/main/java/base/org/spin/model/MFMBatch.java
  org.spin.finance_management/src/main/java/base/org/spin/model/MFMProduct.java
  org.spin.finance_management/src/main/java/base/org/spin/model/MFMProductCategory.java
  org.spin.finance_management/src/main/java/base/org/spin/util/AbstractFunctionalSetting.java
  org.spin.finance_management/src/main/java/base/org/spin/util/FinancialSetting.java
  org.spin.loan_management/src/main/java/base/org/spin/model/LoanManagementModelValidator.java
  org.spin.loan_management/src/main/java/base/org/spin/model/MFMAmortization.java
  org.spin.loan_management/src/main/java/base/org/spin/process/GenerateInvoiceFromLoan.java
  org.spin.loan_management/src/main/java/base/org/spin/process/GeneratePaySelectionFromLoan.java
  org.spin.loan_management/src/main/java/base/org/spin/util/CreateBatchFromInvoice.java
  org.spin.loan_management/src/main/java/base/org/spin/util/FrenchLoanAmortization.java
  org.spin.loan_management/src/main/java/base/org/spin/util/FrenchLoanMethodSimulator.java
  org.spin.loan_management/src/main/java/base/org/spin/util/LoanUtil.java
  org.spin.loan_management/src/main/java/ui/swing/org/spin/form/LoanSimulator.java
  org.spin.loan_management/src/main/java/ui/zk/org/spin/form/WLoanSimulator.java
Labels: (FIM) Financial Management

#3259 Add support to tender type for bank transfer
  base/src/org/eevolution/process/BankTransfer.java
  base/src/org/eevolution/process/BankTransferAbstract.java
  base/src/org/spin/process/DepositFromCash.java
  base/src/org/spin/process/DepositFromCashAbstract.java
  migration/393lts-394lts/06950_Add_Tender_Type_for_Bank_Transfer.xml
Labels: (AP) Account Payable, (FIM) Financial Management, 01 enhancement

#3260 Fixed error with conversion rate based on is active value
  base/src/org/compiere/model/MConversionRate.java
Labels: (AC) Accounting, (AP) Account Payable, (AR) Account Receivable, (FIM) Financial Management, (PA) Performance Analysis and General Ledger, (SC) System Core, 02 bug

#3264 Just generate token based on random UUID
  base/src/org/spin/util/ThirdPartyAccess.java
Labels: (SE) Security
