Repository adempiere/adempiere, pull requests merged in 2020-01, with the labels that each got.

#2933 Fixed error with long time for commission when is called from payroll
  base/src/org/compiere/model/MCommission.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (COM) Commission, 02 bug

#2934 Fixed error with syntax error for commission paid when list details is flagged
  base/src/org/compiere/model/MCommissionRun.java
Labels: (COM) Commission, 02 bug

#2937 Fixed error with Null Pointer Exception when a payment is created from
  base/src/org/compiere/process/BankStatementPayment.java
Labels: (BM) Bank Management, 02 bug

#2938 Fixed error with open amount for receipt created directly on payment / Colect
  base/src/org/compiere/model/MPaySelectionCheck.java
Labels: (AR) Account Receivable, 02 bug

#2939 Set reconcile a generate payment from Identify process
  base/src/org/spin/process/PaymentIdentify.java
Labels: (AP) Account Payable, (AR) Account Receivable, (BM) Bank Management, 02 bug

#2913 #2912 - Speed up the rollback of a migration
  base/src/org/compiere/model/MMigration.java
Labels: (MT) Migration Tools, 01 enhancement, 09 Pending Peer Review

#2910 adempiere #2909 ClearAccounting does not work for Project Issues
  base/src/org/adempiere/engine/CostEngine.java
Labels: 02 bug

#2918 #2917 Add support to the WMS to support multiple exit strategy defini…
  org.eevolution.warehouse/src/main/java/base/org/eevolution/engine/warehouse/WMRuleEngine.java
Labels: (WMS) Warehouse Management System, 01 enhancement

#2924 #2923 Release Outbound Order algorithm does not consider the instance…
  .idea/workspace.xml
  org.eevolution.warehouse/src/main/java/base/org/eevolution/process/ReleaseInOutBound.java
Labels: (WMS) Warehouse Management System, 02 bug

#2927 #2926 Add a silent mode to the RUN_ImportAdempiere scripts.
  utils/RUN_ImportAdempiere.bat
  utils/RUN_ImportAdempiere.sh
Labels: (MNC) Minor Change, 01 enhancement, 09 Pending Peer Review

#2941 Add support to commit warning for Tab ASP
  base/src/org/spin/util/ASPUtil.java
Labels: (UI) User Interface Improvement, 02 bug

#2931 Changing from double to BigDecimal for major precision on Matching
  client/src/org/compiere/apps/form/Match.java
  client/src/org/compiere/apps/form/VMatch.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WMatch.java
Labels: (AP) Account Payable, (MNC) Minor Change, 01 enhancement

#2915 #2914 - During rollback of a Migration Step, force delete of an entity type.
  base/src/org/compiere/model/MMigrationStep.java
Labels: (MT) Migration Tools, 01 enhancement, 09 Pending Peer Review

#2907 Add binary for 3.9.3 ADempiere
  .travis.yml
Labels: (CI) Continuous Integration, 01 enhancement

#2944 The incorrect price when an invoice is generated from Generate Invoice From Outbound #2942
  migration/393lts-394lts/05550_2943_FixTheFilterDocTypeAndParaTargetDocType.xml
  org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java
Labels: (AR) Account Receivable, (WMS) Warehouse Management System, 02 bug

#2949 #2948 The accounting distribution does not work until after loading t…
  base/src/org/compiere/model/MDistribution.java
Labels: (AC) Accounting, 02 bug

#2932 Add Sales Order line reference on create Receipt from Invoice
  base/src/org/compiere/process/InOutCreateFrom.java
Labels: (MM) Material Management, (MNC) Minor Change

#2966 #2953 Navigating through tabs 392 y 393 https://github.com/adempiere/…
  zkwebui/WEB-INF/src/org/adempiere/webui/WSearch.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (UI) User Interface Improvement, 02 bug

#2964 Use Cache for get Client on Cost Engine
  base/src/org/adempiere/engine/CostEngine.java
Labels: (CM) Costing Management, (MNC) Minor Change
