Repository adempiere/adempiere, pull requests merged in 2020-08, with the labels that each got.

#3178 Add support validate error from replication strategy
  base/src/org/adempiere/model/ExportModelValidator.java
  base/src/org/compiere/model/I_AD_ReplicationStrategy.java
  base/src/org/compiere/model/X_AD_ReplicationStrategy.java
  migration/393lts-394lts/05980_Add_Flag_for_Validate_Error_Replication.xml
Labels: (RPL) Replication Engine, 01 enhancement

#3196 Add support to new attribute for packing import without synchronize
  base/src/org/adempiere/pipo/PackIn.java
  base/src/org/adempiere/pipo/PackInHandler.java
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
  base/src/org/compiere/model/I_AD_Package_Imp_Proc.java
  base/src/org/compiere/model/X_AD_Package_Imp_Proc.java
  base/src/org/compiere/util/ImpExpUtil.java
  migration/393lts-394lts/06410_Add_Attribute_for_synchronize_columns_from_Packout.xml
Labels: (AD) Application Dictionary, 01 enhancement

#3193 Add support to model validator window for client definition
  base/src/org/compiere/model/ModelValidationEngine.java
  migration/393lts-394lts/06300_Add_Model_Validator_for_Client.xml
Labels: (SA) System Administrator, 01 enhancement

#3190 Fixed error with deposit from cash when exist collects with
  base/src/org/spin/process/DepositFromCash.java
Labels: (BM) Bank Management, 02 bug

#3192 Fixed error with process infom for selection keys:
  base/src/org/compiere/process/ProcessInfo.java
Labels: (SC) System Core, 02 bug

#3200 Freight Management functionality
  base/src/org/compiere/model/MPackage.java
  base/src/org/compiere/process/PackageCreate.java
  migration/393lts-394lts/06400_FreightManagement.xml
  org.eevolution.freight/src/main/java/base/org/eevolution/engine/freight/FreightRuleInterface.java
  org.eevolution.freight/src/main/java/base/org/eevolution/model/FreightModelValidator.java
  org.eevolution.freight/src/main/java/base/org/spin/process/CreateFreightOrderFromPackage.java
  org.eevolution.freight/src/main/java/base/org/spin/process/CreateFreightOrderFromPackageAbstract.java
  org.eevolution.freight/src/main/java/base/org/spin/process/GenerateAPInvoiceFromFreightOrder.java
  org.eevolution.freight/src/main/java/base/org/spin/process/GenerateAPInvoiceFromFreightOrderAbstract.java
  org.eevolution.freight/src/main/java/base/org/spin/process/GenerateFreightOrderFromOutbound.java
  org.eevolution.freight/src/main/java/base/org/spin/process/GenerateFreightOrderFromOutboundAbstract.java
  org.eevolution.freight/src/main/java/base/org/spin/process/GenerateSalesInvoiceFromFreightOrder.java
  org.eevolution.freight/src/main/java/base/org/spin/process/GenerateSalesInvoiceFromFreightOrderAbstract.java
Labels: (FRM) Freight Management, 01 enhancement

#3136 Removing JBoss Wildfly 19 obstacles
  zkwebui/WEB-INF/tld/web/core.dsp.tld
  zkwebui/WEB-INF/tld/zk/core.dsp.tld
  zkwebui/WEB-INF/tld/zul/core.dsp.tld
Labels: 01 enhancement

#3201 Just change file of migration to correct folder
  migration/393lts-394lts/05550_0213_AutomaticAndProcessSync.xml
Labels: (MNC) Minor Change, 01 enhancement

#3195 Fixed errors on tree maintenance
  base/src/org/compiere/model/MElement.java
  base/src/org/compiere/model/MTree.java
  base/src/org/compiere/model/PO.java
  base/src/org/compiere/process/TreeMaintenance.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/ADTreeOnDropListener.java
Labels: (AD) Application Dictionary, 02 bug

#3197 Add Support to Parent Column on Sort Tab
  base/src/org/adempiere/controller/SortTabController.java
  base/src/org/compiere/model/GridTab.java
  client/src/org/compiere/apps/APanel.java
  client/src/org/compiere/grid/VSortTab.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/WSortTab.java
Labels: (AD) Application Dictionary, (SA) System Administrator, 12 Feature

#3203 Fixed error with Replenish Warehouse when a product not have storage
  db/ddlutils/oracle/views/RV_M_Replenish.sql
  db/ddlutils/postgresql/views/RV_M_Replenish.sql
  migration/393lts-394lts/06450_Fixed_Error_with_Replenish_Browser.xml
Labels: (MM) Material Management, 02 bug

#3198 Fixed error with dependences when a column is changed
  db/ddlutils/postgresql/functions/altercolumn.sql
  db/ddlutils/postgresql/functions/get_all_views.sql
  migration/393lts-394lts/06420_Fixed_Error_with_Dependences_Alter_Column.xml
Labels: (AD) Application Dictionary, 02 bug

#3194 Enlarge Size of Name column for C_BPartner_Location Table to 255
  migration/393lts-394lts/06400_Enlarge_Size_of_Name_for_Business_Partner_Location.xml
Labels: (SC) System Core, 01 enhancement

#3185 Feature/#rpl add wrapper for replication
  base/src/org/adempiere/process/rpl/IExportProcessor.java
  base/src/org/adempiere/process/rpl/IExportProcessorAsWrapper.java
  base/src/org/adempiere/process/rpl/IExportProcessorDefinition.java
  base/src/org/adempiere/process/rpl/ITestImportProcessor.java
  base/src/org/adempiere/process/rpl/exp/ExportHelper.java
  base/src/org/adempiere/process/rpl/exp/WrapperUtil.java
  base/src/org/adempiere/util/rpl/EntityWrapper.java
  base/src/org/adempiere/util/rpl/EntityWrapperFactory.java
  base/src/org/compiere/model/MEXPFormat.java
  base/src/org/compiere/model/MEXPProcessor.java
  base/src/org/compiere/model/MEXPProcessorType.java
  base/src/org/compiere/model/MIMPProcessor.java
  base/src/org/compiere/model/MIMPProcessorParameter.java
  base/src/org/compiere/model/MIMPProcessorType.java
  base/src/org/compiere/model/MReplicationStrategy.java
  base/src/org/compiere/model/MReplicationTable.java
  base/src/org/spin/process/rpl/exp/TestReplicationStrategy.java
  base/src/org/spin/process/rpl/exp/TestReplicationStrategyAbstract.java
  base/src/org/spin/process/rpl/imp/TestImportProcessor.java
  base/src/org/spin/process/rpl/imp/TestImportProcessorAbstract.java
  migration/393lts-394lts/05990_Add_Test_for_Import_Processor.xml
  migration/393lts-394lts/06000_Add_Test_for_Replication_Strategy.xml
Labels: (CI) Code Improvement or Optimization, (RPL) Replication Engine

#3205 Allows send mail to employee from bank account email and user
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/SendPayrollReceiptByEmail.java
Labels: 01 enhancement

#3129 #3124 - bug in VPanel.getMnemonic resolved
  client/src/org/compiere/grid/VPanel.java
Labels: (UI) User Interface Improvement

#3206 #3046 Process to Create Invoice from Payment online
  base/src/org/eevolution/process/GenerateInvoiceFromPayment.java
Labels: (AP) Account Payable, 01 enhancement

#3213 Fixed error with for requery necessary for getLines Method
  base/src/org/compiere/model/MOrder.java
Labels: (POS) Point Of Sales, (SO) Sales Management, 02 bug

#3211 Add new Smart Browser for generate invoice from sales order
  base/src/org/spin/process/GenerateInvoiceFromSalesOrders.java
  base/src/org/spin/process/GenerateInvoiceFromSalesOrdersAbstract.java
  migration/393lts-394lts/06480_Add_Smart_Browse_for_Generate_Invoice_from_Order.xml
Labels: (SO) Sales Management, 01 enhancement
