Repository adempiere/adempiere, pull requests merged in 2020-07, with the labels that each got.

#3153 Add method for get all parameters for application registration
  base/src/org/spin/model/MADAppRegistration.java
Labels: (MNC) Minor Change

#3155 Add new Smart Browser for Copy Window from Role
  base/src/org/spin/process/CopyWindowFromRole.java
  base/src/org/spin/process/CopyWindowFromRoleAbstract.java
  migration/393lts-394lts/05860_Add_Role_Copy_From_Window.xml
Labels: (SE) Security, 01 enhancement

#3159 Fixed error with return material for Shipment Details report
  db/ddlutils/oracle/views/RV_INOUTDETAILS.sql
  db/ddlutils/postgresql/views/RV_INOUTDETAILS.sql
  migration/393lts-394lts/05920_Fixed_Return_Quantity_for_Shipment_Details_report.xml
Labels: (MM) Material Management, (PF) Report Engine & Print Format, 02 bug

#3158 Add some parameters for Invoice summary and detail
  db/ddlutils/oracle/views/RV_C_INVOICE.sql
  db/ddlutils/oracle/views/RV_C_INVOICELINE.sql
  db/ddlutils/postgresql/views/RV_C_INVOICE.sql
  db/ddlutils/postgresql/views/RV_C_INVOICELINE.sql
  migration/393lts-394lts/05910_Add_Document_Base_Type_Invoice_View.xml
Labels: (PF) Report Engine & Print Format, 01 enhancement

#3162 Fixed error with default values for scheduler parameters
  base/src/org/eevolution/service/dsl/ProcessBuilder.java
  serverRoot/src/main/server/org/compiere/server/Scheduler.java
Labels: (SC) System Core, (SS) Scheduler, 02 bug

#3163 Feature/#role add copy from form
  base/src/org/spin/process/CopyFormFromRole.java
  base/src/org/spin/process/CopyFormFromRoleAbstract.java
  migration/393lts-394lts/05880_Add_Role_Copy_From_Form.xml
Labels: (SE) Security, 01 enhancement

#3154 Fixed error with export element from Smart Browser
  base/src/org/adempiere/pipo/handler/GenericPOHandler.java
Labels: (SA) System Administrator, 02 bug

#3156 Add support to copy role from other for Browser
  base/src/org/spin/process/CopyBrowserFromRole.java
  base/src/org/spin/process/CopyBrowserFromRoleAbstract.java
  migration/393lts-394lts/05870_Add_Role_Copy_From_Browser.xml
Labels: (SE) Security, 01 enhancement

#3164 This change allows define a dynamic column of smart browser based on any
  base/src/org/adempiere/model/MBrowseField.java
  client/src/org/eevolution/grid/Browser.java
Labels: (SA) System Administrator, (UI) User Interface Improvement, 01 enhancement

#3165 Add new Smart Browser for add document Actions to Role easy
  base/src/org/spin/grid/BrowseAxisColumnSelection.java
  base/src/org/spin/process/CreateRoleFromDocumentAction.java
  base/src/org/spin/process/CreateRoleFromDocumentActionAbstract.java
  migration/393lts-394lts/05890_Add_Document_Actions_to_Role.xml
Labels: (SA) System Administrator, (SE) Security, 01 enhancement

#3166 Add Conversion message for dictionary
  base/src/org/compiere/model/MInvoice.java
  migration/393lts-394lts/05930_Add_Conversion_Rate_Message.xml
Labels: (SC) System Core, (TRL) Translation, 01 enhancement

#3168 Feature for allows copy process from other ASP
  base/src/org/compiere/model/MProcessCustom.java
  base/src/org/compiere/model/MProcessParaCustom.java
  base/src/org/spin/process/ASPCopyProcessFrom.java
  base/src/org/spin/process/ASPCopyProcessFromAbstract.java
  migration/393lts-394lts/05940_Add_Copy_Process_From_ASP.xml
Labels: (SA) System Administrator, 01 enhancement

#3169 This feature allows copy a browser from other ASP Level
  base/src/org/compiere/model/MBrowseCustom.java
  base/src/org/compiere/model/MBrowseFieldCustom.java
  base/src/org/spin/process/ASPCopyBrowserFrom.java
  base/src/org/spin/process/ASPCopyBrowserFromAbstract.java
  migration/393lts-394lts/05950_Add_Copy_Browser_From_ASP.xml
Labels: (SA) System Administrator, 01 enhancement

#3172 Add Smart Browser for copy window from ASP
  base/src/org/compiere/model/MTabCustom.java
  base/src/org/compiere/model/MWindowCustom.java
  base/src/org/spin/process/ASPCopyWindowFrom.java
  base/src/org/spin/process/ASPCopyWindowFromAbstract.java
  migration/393lts-394lts/05960_Add_Copy_Window_From_ASP.xml
Labels: (SA) System Administrator, 01 enhancement

#3157 #3094 Fix Landed Costs Accounting, when Vendor invoice is in another …
  base/src/org/adempiere/engine/CostEngine.java
  base/src/org/compiere/acct/Doc_Invoice.java
  base/src/org/compiere/model/MLandedCostAllocation.java
Labels: (AP) Account Payable, (CM) Costing Management

#3176 Fix bug on save attachment file
  base/src/org/compiere/model/MAttachment.java
Labels: 02 bug

#3174 Close Expired Session
  base/src/org/compiere/model/MSession.java
  base/src/org/compiere/model/PO.java
  base/src/org/spin/process/CloseExpiredSessions.java
  base/src/org/spin/process/CloseExpiredSessionsAbstract.java
  migration/393lts-394lts/05960_Close_Expired_Session_Process.xml
Labels: (SE) Security, 01 enhancement

#3175 Add process for delete temporary tables
  base/src/org/spin/process/DeleteTemporaryTables.java
  base/src/org/spin/process/DeleteTemporaryTablesAbstract.java
  migration/393lts-394lts/05970_Delete_Temporary_Table_Process.xml
Labels: (SA) System Administrator, 01 enhancement

#3177 After chage done on #3174 is possible that can exists a recursive call
  base/src/org/compiere/model/PO.java
Labels: (SE) Security, 02 bug

#3161 [Bug Report] Error when try create a Purchase Order from Project Line #3160
  org.adempiere.project/src/main/java/org/compiere/model/MProjectLine.java
Labels: (PM) Project Management, 02 bug

#3171 Bug Report The workflow engine is not correctly handling transactions when processing documents
  base/src/org/adempiere/util/ProcessUtil.java
  base/src/org/compiere/wf/DocWorkflowManager.java
  base/src/org/compiere/wf/MWFActivity.java
  base/src/org/compiere/wf/MWFProcess.java
  base/src/org/compiere/wf/MWorkflow.java
  base/src/org/compiere/wf/WFActivityManage.java
  base/src/org/compiere/wf/WFActivityManageAbstract.java
  base/src/org/compiere/wf/WFProcessManage.java
  base/src/org/compiere/wf/WFProcessManageAbstract.java
  extend/src/test/functional/WorkflowTest.java
Labels: (BPM) Workflow Engine, 02 bug

#3179 Fixed error with constraint for column name of sequence no
  migration/393lts-394lts/05910_Add_Document_Base_Type_Invoice_View.xml
Labels: 02 bug

#3132 #3131 Error calculating parent tax on sales order with warehouse docu…
  base/src/org/compiere/model/MInvoice.java
  base/src/org/compiere/model/MInvoiceLine.java
  base/src/org/compiere/model/MOrder.java
  base/src/org/compiere/model/MOrderLine.java
Labels: (SO) Sales Management, (TM) Tax Management, 02 bug

#3127 Error when an Invoice is generated from Outbound line based on movement quantity
  org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java
Labels: (WMS) Warehouse Management System, 02 bug

#3182 #3180 Remove fields from Purchase Order.
  migration/393lts-394lts/05990_3180_Remove_Fields_From_PO.xml
Labels: (PO) Purchase Management, 02 bug

#3181 Fixed error with transaction open and never closed for Trx.run method
  base/src/org/compiere/util/Trx.java
Labels: (SC) System Core, 02 bug

#3184 Fixed error when a po is save using saveReplica instead save
  base/src/org/compiere/model/PO.java
Labels: (RPL) Replication Engine, 02 bug
