Repository adempiere/adempiere, pull requests merged in 2020-04, with the labels that each got.

#3093 Fixed error with Save from PO when a error is created from a model
  base/src/org/compiere/model/PO.java
Labels: (SC) System Core, 02 bug

#3091 Add Smart Browser for Create Export Format Lines from Table selected on
  base/src/org/spin/process/ExportFormatCreateFromTable.java
  base/src/org/spin/process/ExportFormatCreateFromTableAbstract.java
  migration/393lts-394lts/05780_Add_SB_Create_From_Table_Export_Format_Replication.xml
Labels: 01 enhancement

#3102 Fixed error with Copy values for UUID
  base/src/org/compiere/model/M_Element.java
  base/src/org/compiere/model/PO.java
Labels: (SC) System Core, 02 bug

#3098 #3046 Process to Create Invoice from Payment online https://github.c…
  base/src/org/eevolution/process/GenerateInvoiceFromPayment.java
  base/src/org/eevolution/process/GenerateInvoiceFromPaymentAbstract.java
  migration/393lts-394lts/05700_3046_ProcessToCreateInvoiceFromPaymentOnline.xml
Labels: (AR) Account Receivable, 01 enhancement

#3106 #3103 Event Template (Mail Text) Bug Report https://github.com/adempi…
  migration/393lts-394lts/05800_Event_Template_Mail_Text.xml
Labels: (AD) Application Dictionary, 02 bug
