Repository adempiere/adempiere, pull requests merged in 2020-12, with the labels that each got.

#3271 Add parameters for create price list
  base/src/org/compiere/process/M_PriceList_Create.java
  base/src/org/compiere/process/M_PriceList_CreateAbstract.java
  migration/393lts-394lts/07050_Add_Filter_values_for_Price_List_Create.xml
Labels: (SO) Sales Management, 01 enhancement

#3268 Add autoreconcile support for deposit from cash
  base/src/org/spin/process/DepositFromCash.java
  base/src/org/spin/process/DepositFromCashAbstract.java
  migration/393lts-394lts/07080_Add_Is_Auto_Reconcile_flag_for_deposit_from_cash.xml
Labels: (FIM) Financial Management

#3263 Prevent NPE for barcode report
  base/src/org/compiere/print/layout/BarcodeElement.java
Labels: (PF) Report Engine & Print Format, 02 bug

#3272 Remove unnecessary validation of cash tender type for Cash window
  migration/393lts-394lts/07110_Remove_Cash_Validation.xml
Labels: (AP) Account Payable, 01 enhancement

#3269 Fixed error with duplicated lines for bank statement
  base/src/org/compiere/model/MBankStatement.java
  base/src/org/compiere/model/MPayment.java
Labels: (FIM) Financial Management

#3265 Fixed error with reference id when a export format is referenced
  base/src/org/adempiere/util/rpl/EntityWrapperFactory.java
Labels: (RPL) Replication Engine, 02 bug

#3279 #3278 [Bug Report] Can not delete Orders when the flag Records deleta…
  migration/393lts-394lts/07220_3278_FixedIsDropBOMTranslationFlagC_Order.xml
Labels: (PO) Purchase Management, (SO) Sales Management

#3277 #3276 [Bug Report] Define a table as is Document not allow Records de…
  base/src/org/compiere/model/MTable.java
Labels: (AD) Application Dictionary, 02 bug
