Repository adempiere/adempiere, pull requests merged in 2021-06, with the labels that each got.

#3464 #3462 [Bug Report] Total matched invoice qty https://github.com/ademp…
  base/src/org/compiere/process/InvoiceCreateFrom.java
  client/src/org/compiere/apps/form/Match.java
Labels: (MM) Material Management, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance, 23 reproduced

#3468 #3467 [Bug Report] Generate Receipt from Invoice process is not valid…
  base/src/org/compiere/model/MInvoiceLine.java
  base/src/org/compiere/model/MMatchPO.java
  base/src/org/compiere/process/InvoiceCreateInOut.java
  base/src/org/compiere/process/InvoiceCreateInOutAbstract.java
Labels: (AP) Account Payable, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance, 23 reproduced

#3470 #3469 [Bug Report] In the process Generate an Invoice from the Receip…
  base/src/org/compiere/process/InOutCreateInvoice.java
  base/src/org/compiere/process/InOutCreateInvoiceAbstract.java
Labels: (AP) Account Payable, (MM) Material Management, 10 Reviewed by Peer, 13 Pending Acceptance

#3449 Fixed error when a Purchase order is voided
  base/src/org/compiere/model/MOrder.java
Labels: (MM) Material Management, (PO) Purchase Management, 02 bug, 10 Reviewed by Peer

#3484 Remove deprecated methods for Order
  base/src/org/compiere/model/MOrder.java
Labels: (CI) Code Improvement or Optimization, (MNC) Minor Change, 10 Reviewed by Peer

#3480 Fixed error with Dependent Entities for Record Access
  base/src/org/compiere/model/MRole.java
  base/src/org/compiere/util/DependentRecordAccess.java
Labels: (SE) Security, 02 bug, 09 Pending Peer Review

#3475 Fixed error with missing parameter for Requisition PO Create
  base/src/org/eevolution/process/CreatePOFromRequisitionLines.java
Labels: (PO) Purchase Management, 02 bug, 10 Reviewed by Peer

#3472 Error in calculating quantity ordered or reserved for manufacturing order and distribution order
  base/src/org/compiere/model/MInOut.java
  base/src/org/compiere/model/MOrder.java
  base/src/org/compiere/model/MOrderLine.java
Labels: (SO) Sales Management, 01 enhancement, 10 Reviewed by Peer

#3458 Add the database function to get the daily salary
  db/ddlutils/oracle/functions/DailySalaryToDateByHrProcess.sql
  db/ddlutils/postgresql/functions/DailySalaryToDateByHrProcess.sql
  migration/393lts-394lts/07680_Add_Function_Daily_Salary_by_HRProcress.xml
Labels: (HRM) Human Resource and Payroll Management, 04 invalid, 10 Reviewed by Peer, 12 Feature, 13 Pending Acceptance, 14 Waiting for User Changes

#3474 Adding the Weight and Volume field into Sales Order and Purchase Order Feature/3473
  migration/393lts-394lts/07840_3473_AdddingFieldToWeightAndVolume.xml
Labels: (PO) Purchase Management, (SO) Sales Management, 01 enhancement, 10 Reviewed by Peer

#3483 Fixed error with File Storage for process
  base/src/org/spin/process/SetupFileStorageSystem.java
  base/src/org/spin/util/AttachmentUtil.java
Labels: 02 bug

#3485 Minor change imports
  base/src/org/spin/util/TokenGeneratorHandler.java
  base/src/org/spin/util/support/AppSupportHandler.java
Labels: (CI) Code Improvement or Optimization, (MNC) Minor Change, 01 enhancement

#3487 Add specific values for Social Media
  migration/393lts-394lts/07830_Add_Specific_Social_Media_Support.xml
  migration/393lts-394lts/07900_Add_Specific_Social_Media_Support.xml
Labels: 01 enhancement

#3493 fix: BP Group getSQlWhere in Forecast Run Create.
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/model/MPPForecastDefinitionLine.java
Labels: 02 bug, 13 Pending Acceptance

#3488 Fixed error with Standard Request Type Model Validator
  org.adempiere.request/src/main/java/org/compiere/model/MStandardRequestType.java
  org.adempiere.request/src/main/java/org/compiere/model/RequestModelValidator.java
Labels: (RM) Request Management, 02 bug

#3491 Fixed error with Crosstab for Smart Browser
  client/src/org/eevolution/grid/Browser.java
  migration/393lts-394lts/07860_Fixed_error_with_string_value_for_axis_browser.xml
Labels: (AD) Application Dictionary, 02 bug

#3481 Bad reference for price list create process
  base/src/org/compiere/process/M_PriceList_Create.java
Labels: (MM) Material Management, (SO) Sales Management
