Repository adempiere/adempiere, pull requests merged in 2021-04, with the labels that each got.

#3364 fix #3363: Field length with 0 value.
  base/src/org/compiere/model/MColumn.java
  base/src/org/compiere/util/DisplayType.java
Labels: (AD) Application Dictionary, 02 bug

#3422 Adempiere B#3421 Fin Report, Parameter Userelement2_ID not assigned
  base/src/org/compiere/report/FinReport.java
Labels: (AC) Accounting, 02 bug

#3191 Improve performance for running payroll process:
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (CI) Code Improvement or Optimization, (HRM) Human Resource and Payroll Management, 10 Reviewed by Peer, 13 Pending Acceptance

#3360 Remove unnecessary exception before save order line
  base/src/org/compiere/model/MOrderLine.java
Labels: (SO) Sales Management, 01 enhancement

#3381 Add role access to document status indicator
  base/src/org/adempiere/model/MDocumentStatus.java
Labels: (PA) Performance Analysis and General Ledger, 02 bug

#3404 #3401 Error in precondition applicable for process action when displa…
  base/src/org/adempiere/apps/toolbar/AProcessActionModel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (SC) System Core, (UI) User Interface Improvement, 02 bug, 10 Reviewed by Peer

#3414 Fix distribution by organization dimension
  base/src/org/compiere/model/MDistribution.java
Labels: (AC) Accounting, 02 bug, 10 Reviewed by Peer

#3373 Fix/#3361 npe when no dashboard content
  .classpath
  org.adempiere.test/src/test/resource/mockito-extensions/org.mockito.plugins.MockMaker
  tools/lib/junit/mockito-inline-3.6.0-javadoc.jar
  tools/lib/junit/mockito-inline-3.6.0-sources.jar
  tools/lib/junit/mockito-inline-3.6.0.jar
  zkwebui/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
  zkwebui/WEB-INF/test/src/org/adempiere/webui/desktop/DefaultDesktop_Test.java
Labels: 02 bug

#3402 Add support to axis column based on Value instead id for where clause
  client/src/org/eevolution/grid/Browser.java
Labels: (AD) Application Dictionary, 01 enhancement, 14 Waiting for User Changes

#3417 Fixed error with wrong validation for production
  base/src/org/compiere/model/MProduction.java
Labels: (PLH) Production Light, 02 bug, 23 reproduced

#3431 #3430 [Bug Report] Transaction blocking error when creating account distribution and immediate posting
  base/src/org/compiere/model/MDistributionLine.java
Labels: (AP) Account Payable, 02 bug, 10 Reviewed by Peer, 23 reproduced

#3240 Adding a clear method to empty the previous context in the MMailText
  org.adempiere.request/src/main/java/org/compiere/model/MMailText.java
  org.adempiere.request/src/main/java/org/spin/model/MRNoticeTemplate.java
Labels: 01 enhancement, 14 Waiting for User Changes

#3343 #3266 Error in calculating quantity ordered or reserved for order manufacturing
  base/src/org/adempiere/engine/StorageEngine.java
  base/src/org/compiere/model/MOrder.java
  base/src/org/compiere/model/MOrderLine.java
  base/src/org/eevolution/model/MDDOrder.java
  base/src/org/eevolution/model/MDDOrderLine.java
  base/src/org/eevolution/model/MPPCostCollector.java
  base/src/org/eevolution/model/MPPOrder.java
  base/src/org/eevolution/model/MPPOrderBOMLine.java
Labels: (MM) Material Management, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance

#3426 #3425 [Bug Report] Define as parent link for HR_Process_ID in HR_Move…
  migration/393lts-394lts/07670_3425_DefineAsParentLinkForHR_Process_ID.xml
Labels: (HRM) Human Resource and Payroll Management, 02 bug

#3440 #3439 [Bug Report] Transaction blocking error when complete an alloca…
  base/src/org/compiere/acct/Fact.java
Labels: (AC) Accounting, 02 bug, 09 Pending Peer Review, 23 reproduced

#3435 #3429 [Bug Report] Transaction blocking error when creating payment f…
  base/src/org/compiere/process/BankStatementPayment.java
Labels: (AP) Account Payable, 02 bug, 09 Pending Peer Review

#3436 Feature/#ad add grid sequence window custom
  base/src/org/compiere/model/I_AD_FieldCustom.java
  base/src/org/compiere/model/MFieldCustom.java
  base/src/org/compiere/model/X_AD_FieldCustom.java
  base/src/org/spin/util/ASPUtil.java
  migration/393lts-394lts/07670_Add_grid_Sequence_for_field_customization.xml
Labels: (AD) Application Dictionary, 01 enhancement, 09 Pending Peer Review

#3438 Create Purchase Order from Requisition have a error
  base/src/org/compiere/process/RequisitionPOCreate.java
Labels: (PO) Purchase Management, 02 bug, 10 Reviewed by Peer, 23 reproduced

#3437 Fixed error with inconsistency of payment
  base/src/org/compiere/model/MPayment.java
Labels: (SC) System Core, 02 bug, 10 Reviewed by Peer, 23 reproduced

#3441 Issue #3309 - Refactoring part 1: Move a utility function to TimeUtil
  base/src/org/compiere/util/TimeUtil.java
  base/test/src/org/compiere/util/TimeUtilTest.java
Labels: (CI) Code Improvement or Optimization, 09 Pending Peer Review

#3442 Issue #3309 - Refactoring part 2: Move knowledge of the Doc classes to the Doc Classes
  base/src/org/compiere/acct/Doc.java
  base/src/org/compiere/acct/Doc_BankStatement.java
  base/src/org/compiere/acct/Doc_Inventory.java
  base/src/org/compiere/acct/Doc_Movement.java
  base/src/org/compiere/acct/Doc_Production.java
  base/src/org/compiere/acct/Doc_ProductionBatch.java
  base/src/org/compiere/acct/Doc_ProjectIssue.java
  base/src/org/compiere/acct/Doc_Requisition.java
  org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_DDOrder.java
  org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_PPCostCollector.java
  org.eevolution.manufacturing/src/main/java/base/org/compiere/acct/Doc_PPOrder.java
  org.eevolution.manufacturing/src/test/java/base/org/compiere/acct/TestDoc.java
Labels: (CI) Code Improvement or Optimization, 10 Reviewed by Peer, 23 reproduced

#3394 Remove Hard Code for C_Location in Replication Data
  base/src/org/adempiere/util/rpl/EntityWrapperFactory.java
Labels: (CI) Code Improvement or Optimization, (RPL) Replication Engine, 17 Waiting for Information

#3443 Issue #3309 - Refactoring part 3: Add methods to MPeriod to find min and max dates in calendar.
  base/src/org/compiere/model/MPeriod.java
  base/test/src/org/compiere/model/IT_MPeriod.java
  org.adempiere.test/src/test/java/org/adempiere/test/CommonSystemSetup.java
Labels: (CI) Code Improvement or Optimization, 10 Reviewed by Peer

#3445 Change file name for migration
  migration/393lts-394lts/07260_Add_validation_for_Agreement_on_Documents.xml
Labels: (AD) Application Dictionary, (MNC) Minor Change

#3446 Set default value for centrally maintained menu
  base/src/org/compiere/model/MMenu.java
  migration/393lts-394lts/07670_Add_default_false_for_summary_level_menu.xml
Labels: (TRL) Translation, 02 bug, 10 Reviewed by Peer

#3447 Fixed error with tender type for create payment selection from payment
  base/src/org/compiere/model/MPaySelectionCheck.java
Labels: (AP) Account Payable, 02 bug

#3342 #3267 Validate Ordered and Reserved Quantities Inventory
  base/src/org/eevolution/process/ValidateOrderedAndReservedQuantity.java
  base/src/org/eevolution/process/ValidateOrderedAndReservedQuantityAbstract.java
  migration/393lts-394lts/06430_ValidateOrderedAndReservedQuantity.xml
Labels: (MM) Material Management, 01 enhancement, 13 Pending Acceptance

#3428 Fix RoleAccessUpdate to enable update for all clients and all roles.
  base/src/org/compiere/process/RoleAccessUpdate.java
  base/src/org/compiere/process/RoleAccessUpdateAbstract.java
  base/test/src/org/compiere/process/RoleAccessUpdate_IT.java
  base/test/src/org/compiere/process/RoleAccessUpdate_Test.java
Labels: (SE) Security, 01 enhancement, 10 Reviewed by Peer, 23 reproduced

#3450 Minor change for classpath
  .classpath
Labels: (MNC) Minor Change, 10 Reviewed by Peer, 23 reproduced
