Repository adempiere/adempiere, pull requests merged in 2021-02, with the labels that each got.

#3350 Update release.yml
  .github/workflows/release.yml
Labels: (CI) Continuous Integration, 01 enhancement

#3352 Fixed error with Generate Token for System Administrator role
  base/src/org/spin/util/ThirdPartyAccess.java
Labels: (SE) Security, 02 bug

#3355 Enable customizable test properties which don't affect the test.properties file.
  .gitignore
  utils_dev/properties.xml
  utils_dev/test.properties
Labels: 21 Testing

#3356 Update build files that reference the ant version.
  tools/RUN_build.bat
  tools/RUN_build.sh
  utils_dev/RUN_build.bat
  utils_dev/RUN_build.sh
  utils_dev/RUN_build2.bat
  utils_dev/RUN_build2.sh
Labels: (SC) System Core, 02 bug

#3359 Add Order reference to financial transaction
  base/src/org/spin/model/I_FM_Transaction.java
  base/src/org/spin/model/X_FM_Batch.java
  base/src/org/spin/model/X_FM_Transaction.java
  migration/393lts-394lts/07650_Add_Order_Line_Reference_for_Financial_Transaction.xml
Labels: (ILM) Investment and Loan Management

#3357 Update Currency for Venezuela Country
  migration/393lts-394lts/07640_Update_Currency_for_Venezuela.xml
Labels: 01 enhancement

#3354 Fixed error with search for leave
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/util/TNAUtil.java
Labels: (HRM) Human Resource and Payroll Management

#3370 Update RUN_build.sh
  tools/RUN_build.sh
  utils_dev/RUN_build.sh
  utils_dev/RUN_build2.sh
Labels: (SC) System Core, 02 bug

#3376 Fixed error with ASP for Overwrite definition
  base/src/org/spin/util/ASPUtil.java
Labels: (UI) User Interface Improvement

#3375 Change Access Level for Generate Token
  migration/393lts-394lts/07660_Change_Access_Level_for_Generate_Token_Process.xml
Labels: (SE) Security, 01 enhancement

#3374 Fixed error with tax calculation for Sales Order
  base/src/org/compiere/model/MOrder.java
Labels: (POS) Point Of Sales, (SC) System Core, (SO) Sales Management, 02 bug
