Repository adempiere/adempiere, pull requests merged in 2021-01, with the labels that each got.

#3250 Add support to Setup for feature
  base/src/org/spin/model/I_AD_SetupDefinition.java
  base/src/org/spin/model/I_AD_SetupLog.java
  base/src/org/spin/model/MADSetupDefinition.java
  base/src/org/spin/model/MADSetupLog.java
  base/src/org/spin/model/X_AD_SetupDefinition.java
  base/src/org/spin/model/X_AD_SetupLog.java
  base/src/org/spin/process/FunctionalitySetupProcess.java
  base/src/org/spin/process/FunctionalitySetupProcessAbstract.java
  base/src/org/spin/setup/SpinContributionTestSetup.java
  base/src/org/spin/util/ISetupDefinition.java
  base/src/org/spin/util/SetupUtil.java
  migration/393lts-394lts/06630_Add_Setup_Definition_for_client.xml
  migration/393lts-394lts/06640_Add_Test_data_for_Functionality_Setup.xml
Labels: (AD) Application Dictionary, 01 enhancement

#3274 #3273 [Feature Request] Add to 24 columns , essential when you want t…
  migration/393lts-394lts/07120_FinancialReport_Add_To_24_Columns.xml
Labels: (FIM) Financial Management, 01 enhancement

#3252 Fixed Memmory Consumption for HTML reports
  base/src/org/spin/util/ExportFormatHTML.java
Labels: (PF) Report Engine & Print Format, 01 enhancement, 09 Pending Peer Review

#3253 Just resize image for reduce memory consumption
  base/src/org/compiere/print/layout/ImageElement.java
Labels: (PF) Report Engine & Print Format, 01 enhancement

#3288 Just add transaction name for query based on POInfoColumn
  base/src/org/compiere/model/POInfo.java
  base/src/org/compiere/model/POInfoColumn.java
Labels: (AD) Application Dictionary, 02 bug

#3297 Change the order of steps to avoid an error when the views are added before the fields they require.
  migration/393lts-394lts/06550_Add_Collecting_Agent_Reference_to_Payment.xml
Labels: 01 enhancement

#3284 Prevent unseteable value for Ref_Payment_ID
  base/src/org/compiere/model/MPayment.java
  base/src/org/spin/process/DepositFromCash.java
  migration/393lts-394lts/07240_Change_Deposit_from_Cash_References.xml
Labels: (AP) Account Payable, 01 enhancement, 14 Waiting for User Changes

#3306 Fixed error with payment selection for Over Under Payment
  migration/393lts-394lts/07230_Fixed_error_with_Over_Under_Amount_for_Payment_Selection.xml
Labels: (AP) Account Payable, 02 bug, 10 Reviewed by Peer

#3295 Add functionality setup for based on testing class
  base/src/org/spin/model/I_AD_SetupDefinition.java
  base/src/org/spin/model/I_AD_SetupLog.java
  base/src/org/spin/model/MADSetupDefinition.java
  base/src/org/spin/model/MADSetupLog.java
  base/src/org/spin/model/X_AD_SetupDefinition.java
  base/src/org/spin/model/X_AD_SetupLog.java
  base/src/org/spin/process/FunctionalitySetupProcess.java
  base/src/org/spin/process/FunctionalitySetupProcessAbstract.java
  base/src/org/spin/setup/SpinContributionTestSetup.java
  base/src/org/spin/util/ISetupDefinition.java
  base/src/org/spin/util/SetupUtil.java
  migration/393lts-394lts/07230_Add_Setup_Definition_for_client.xml
  migration/393lts-394lts/07240_Add_Test_data_for_Functionality_Setup.xml
Labels: (AD) Application Dictionary, 01 enhancement, 10 Reviewed by Peer

#3305 Cleaning Landed Cost Allocation when don't have landed cost definition
  base/src/org/compiere/model/MInvoiceLine.java
Labels: (AP) Account Payable, (CM) Costing Management, 02 bug, 10 Reviewed by Peer

#3282 Add support to multi-currency to Payment Selection Create From:
  base/src/org/compiere/model/MPaySelectionLine.java
  base/src/org/compiere/process/PSCreateFromHRMovement.java
  migration/393lts-394lts/07170_Add_Multi_Currency_support_to_Payment_Selection.xml
Labels: (AP) Account Payable, 01 enhancement, 10 Reviewed by Peer

#3304 Add support to functionality Allow Negative Posting from Accounting
  base/src/org/compiere/acct/Doc.java
  base/src/org/compiere/acct/FactLine.java
Labels: (AC) Accounting

#3310 Add tab for Social Media to Business Partner
  migration/393lts-394lts/07240_Add_Tab_for_Social_Media_to_Business_Partner.xml
Labels: 01 enhancement

#2847 Fixed error on Accounting of Shipment/Receipt
  base/src/org/compiere/acct/Doc_InOut.java
Labels: (AC) Accounting, (MM) Material Management, 02 bug, 10 Reviewed by Peer

#3312 Prevent NPE for Create From on Payment Selection
  base/src/org/compiere/model/MPaySelectionLine.java
  base/src/org/compiere/process/PSCreateFromHRMovement.java
Labels: (AP) Account Payable, 02 bug

#3067 Allows generate allocation from payment and credit memo from a payment
  base/src/org/compiere/model/MPayment.java
Labels: (AP) Account Payable, 02 bug, 17 Waiting for Information

#3289 Just Implement Cache for get Table ID based on table name
  base/src/org/compiere/model/MTable.java
Labels: (AD) Application Dictionary, 01 enhancement, 17 Waiting for Information

#3317 Fixed error with ZK panel when a window have too many record
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: (SC) System Core, 02 bug

#3315 Fixed error with conversion rate for isActive search and decimal
  base/src/org/compiere/model/MConversionRate.java
Labels: (AP) Account Payable, (SC) System Core, 02 bug

#3316 Add helper method for Social Media Model Class
  base/src/org/spin/model/I_AD_UserSocialMedia.java
  base/src/org/spin/model/MADUserSocialMedia.java
  base/src/org/spin/model/X_AD_UserSocialMedia.java
Labels: 01 enhancement

#3314 Fixed error for IsDiscountPrinted attribute from business partner
  base/src/org/compiere/model/MOrder.java
Labels: (POS) Point Of Sales, (SO) Sales Management, 02 bug

#3320 Fixed duplicate posting using document type flag with reversal with original accounting
  base/src/org/compiere/acct/Doc.java
Labels: (AC) Accounting, 02 bug

#3322 Change the internal reference in the ProcessBuilder from a static field to a non-static field.
  base/src/org/eevolution/service/dsl/ProcessBuilder.java
Labels: (SC) System Core, 02 bug

#3325 Reorder step sequence for XML
  migration/393lts-394lts/06870_Add_Third_Party_Access_Token_Generator.xml
Labels: 02 bug

#3324 Fixed error with wrong reference for validation rule
  migration/393lts-394lts/06730_Add_references_to_Financial_Management.xml
Labels: (FIM) Financial Management, 02 bug

#3326 Minor change fixed error with summary translation
  migration/393lts-394lts/07250_Fixed_translation_for_summary_menu.xml
Labels: 02 bug

#3327 Feature/#GitHub actions support
  .github/workflows/main.yml
  .github/workflows/release.yml
  .travis.yml
Labels: (CI) Continuous Integration

#3323 Set client from role for third party access token
  base/src/org/spin/model/MADToken.java
Labels: (SE) Security

#3285 Fixed error with Reversed document when it is copied from window
  base/src/org/compiere/model/M_Element.java
  migration/393lts-394lts/07230_Fixed_error_with_Reversal_ID_and_ReversalLine_ID.xml
Labels: (SC) System Core, 02 bug

#3262 Add ID for M_Storage Table
  base/src/org/compiere/model/MStorage.java
  migration/393lts-394lts/07010_Add_ID_for_Storage.xml
Labels: (MM) Material Management, 01 enhancement, 10 Reviewed by Peer, 17 Waiting for Information

#3261 Add ID for Product Price
  base/src/org/compiere/model/I_M_ProductPrice.java
  base/src/org/compiere/model/MProductPrice.java
  base/src/org/compiere/model/X_M_ProductPrice.java
  migration/393lts-394lts/07000_Add_ID_for_Product_Price.xml
Labels: (MM) Material Management, (SO) Sales Management, 10 Reviewed by Peer, 17 Waiting for Information

#3337 Add Validation for Business Partner to Agreement on document
  migration/393lts-394lts/07260_Add validation for Agreement on Documents.xml
Labels: (FIM) Financial Management, 02 bug

#3210 #3209 credit card and iban validator update to version 1.7
  .classpath
  adempiere.iml
  base/ADempiere.launch
  base/src/org/compiere/model/MBPBankAccount.java
  tools/.classpath
  tools/build.xml
  tools/lib/commons-validator-1.6.jar
  tools/lib/commons-validator-1.7.jar
  tools/lib/testing/commons-validator-1.6-sources.jar
  tools/lib/testing/commons-validator-1.7-sources.jar
Labels: (BM) Bank Management, 01 enhancement, 10 Reviewed by Peer, 14 Waiting for User Changes

#3287 Scheduler Add support to frequency type:
  base/src/org/compiere/model/I_AD_Scheduler.java
  base/src/org/compiere/model/X_AD_Scheduler.java
  migration/393lts-394lts/07380_Add_Support_to_Run_one_time_for_Schedule.xml
  serverRoot/src/main/server/org/compiere/server/AdempiereServer.java
  serverRoot/src/main/server/org/compiere/server/AdempiereServerMgr.java
Labels: (AD) Application Dictionary, 01 enhancement, 12 Feature, 14 Waiting for User Changes

#3286 Add backward compatibility for iReport parameters
  JasperReports/src/org/compiere/report/ReportStarter.java
Labels: (PF) Report Engine & Print Format, 02 bug, 17 Waiting for Information

#3339 #3333 Inbound/Outbound Definition Window priority is show incorrect …
  migration/393lts-394lts/07290_3333_Inbound_OutboundDefinitionWindowPriority.xml
Labels: (WMS) Warehouse Management System, 02 bug, 10 Reviewed by Peer

#3340 Add Financial Transaction Detail Report
  migration/393lts-394lts/07390_Add_Financial_Transaction_Detail_Report.xml
Labels: (FIM) Financial Management, 01 enhancement

#3344 Add support to generate UUID from source
  base/src/org/compiere/util/DB.java
Labels: 01 enhancement

#3346 Allows create fields automatically when a custom tab is created
  base/src/org/compiere/model/MTabCustom.java
  base/src/org/compiere/model/MWindowCustom.java
Labels: (AD) Application Dictionary

#3341 Remove hardcode for production process
  base/src/org/compiere/model/MProduction.java
  base/src/org/compiere/model/MProductionLine.java
Labels: (CI) Code Improvement or Optimization, 01 enhancement, 10 Reviewed by Peer, 17 Waiting for Information

#3311 Fix error on quantities when exist multiple organizations
  db/ddlutils/oracle/views/RV_M_Replenish.sql
  db/ddlutils/postgresql/views/RV_M_Replenish.sql
  migration/393lts-394lts/07130_UpdateReplenishView.xml
Labels: (MM) Material Management, 02 bug, 10 Reviewed by Peer
