Repository adempiere/adempiere, pull requests merged in 2021-07, with the labels that each got.

#3454 Fix NPE when production voided
  base/src/org/compiere/model/MProductionLine.java
Labels: (PLH) Production Light, 02 bug, 09 Pending Peer Review

#3005 MHRProcess periodNo is set to context with name period
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (HRM) Human Resource and Payroll Management, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance

#3503 Update main.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: (CI) Continuous Integration, 02 bug

#3509 Add support to group, class and classification names
  base/src/org/compiere/model/I_I_Product.java
  base/src/org/compiere/model/X_I_Product.java
  base/src/org/compiere/process/ImportProduct.java
  migration/393lts-394lts/07930_Add_support_to_Class_Group_and_classification.xml
Labels: (MM) Material Management, 01 enhancement

#3482 Fixed error with Role Access Update for System Administrator Role
  base/src/org/compiere/process/RoleAccessUpdate.java
  base/test/src/org/compiere/process/RoleAccessUpdate_Test.java
Labels: (SE) Security, 02 bug, 10 Reviewed by Peer

#3146 #3143 fixes bug in (swing) VLocator grid table editor
  client/src/org/compiere/grid/ed/VLocator.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WLocatorDialog.java
Labels: (MM) Material Management, 02 bug, 10 Reviewed by Peer, 14 Waiting for User Changes

#3501 Feature/#3392 aging report enhance the table t aging more columns
  base/src/org/compiere/model/I_T_Aging.java
  base/src/org/compiere/model/MAging.java
  base/src/org/compiere/model/X_T_Aging.java
  migration/393lts-394lts/07910_T_Aging_EnhanceColumns.xml
Labels: (AR) Account Receivable, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance

#3508 [Bug Fixed] Display rule does not work correctly between records when browsing in grid mode for #3506
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridTabRowRenderer.java
Labels: (UI) User Interface Improvement, 02 bug, 10 Reviewed by Peer, 23 reproduced

#3524 Remove test that trxName be not null from DocumentEngine.postImmediate
  base/src/org/compiere/process/DocumentEngine.java
  serverRoot/src/test/server/org/compiere/acct/IT_DocumentPosting.java
Labels: (SC) System Core, 02 bug, 10 Reviewed by Peer

#3527 Fixed missing JasperReport library on build
  JasperReports/build.xml
Labels: (PF) Report Engine & Print Format, 02 bug

#3528 Fixed error with SQLException for Migration
  base/src/org/compiere/model/MColumn.java
  base/src/org/compiere/model/MMigration.java
Labels: (MT) Migration Tools

#3529 Fixed error with mandatory columns for Freight improvement
  migration/393lts-394lts/06380_Improvements_for_Fleet_Management.xml
Labels: (FRM) Freight Management, 02 bug

#3511 Create Index on Migration Data
  migration/393lts-394lts/07920_Index_on_Migration_Data.xml
Labels: (MNC) Minor Change, (MT) Migration Tools, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance, 14 Waiting for User Changes

#3525 Add chart support for PA Goal
  base/src/org/adempiere/apps/graph/GraphBuilder.java
  base/src/org/compiere/model/I_AD_Chart.java
  base/src/org/compiere/model/I_PA_Goal.java
  base/src/org/compiere/model/MGoal.java
  base/src/org/compiere/model/X_AD_Chart.java
  base/src/org/compiere/model/X_PA_Goal.java
  client/src/org/adempiere/apps/graph/PAPanel.java
  client/src/org/adempiere/apps/graph/ViewPI.java
  db/ddlutils/oracle/views/RV_C_SALESDASHBOARD.sql
  db/ddlutils/postgresql/views/RV_C_SALESDASHBOARD.sql
  migration/393lts-394lts/07940_Add_support_to_Chart_for_PA_Goal.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/graph/WPAPanel.java
Labels: (PA) Performance Analysis and General Ledger, 01 enhancement

#3517 [Feature Request] Slow moving inventory Report #3319
  db/ddlutils/oracle/views/RV_M_SlowMovingInventory.sql
  db/ddlutils/oracle/views/RV_M_SlowMovingWarehouseInventory.sql
  db/ddlutils/postgresql/views/RV_M_SlowMovingInventory.sql
  db/ddlutils/postgresql/views/RV_M_SlowMovingWarehouseInventory.sql
  migration/393lts-394lts/07280_3319_SlowMovingInventoryReport.xml
Labels: (MM) Material Management, 01 enhancement, 10 Reviewed by Peer

#3526 fixed error with create from on current payment
  base/src/org/spin/process/PaymentCreateFromInvoice.java
Labels: (AP) Account Payable, 02 bug, 09 Pending Peer Review

#3531 Add tree definition for Web Store Product Category
  migration/393lts-394lts/07960_Add_Tree_definition_for_Web_Store_Category.xml
Labels: (VSF) Web Store Front-Vue, 01 enhancement, 10 Reviewed by Peer

#3513 Adempiere #3512 reverse accrual uses original movementdate
  base/src/org/compiere/model/MInventory.java
Labels: (MM) Material Management, 02 bug, 09 Pending Peer Review

#3515 Adempiere #3514 MMovement reverse Accrual does nothing
  base/src/org/compiere/model/MMovement.java
Labels: (MM) Material Management, 02 bug, 09 Pending Peer Review

#3530 Fixed error with duplicated primary key
  migration/393lts-394lts/06570_Add_Web_Store_Integration_from_Spin_Contribution.xml
Labels: (MT) Migration Tools, (VSF) Web Store Front-Vue, 09 Pending Peer Review

#3460 Fixed error with multiplier for RV_C_InvoiceLine view
  db/ddlutils/oracle/views/RV_C_INVOICELINE.sql
  db/ddlutils/postgresql/views/RV_C_INVOICELINE.sql
  migration/393lts-394lts/07970_Fixed_error_with_multiplier_invoice_line.xml
Labels: (PF) Report Engine & Print Format, (SO) Sales Management, 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance

#3533 Remove Unnecessary step
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: (CI) Continuous Integration

#3418 Add Support to Accounting by Document Base Type
  base/src/org/compiere/acct/Doc.java
  base/src/org/compiere/acct/DocFactory.java
  base/src/org/compiere/model/CalloutDocType.java
  base/src/org/compiere/model/I_C_DocBaseType.java
  base/src/org/compiere/model/I_C_DocType.java
  base/src/org/compiere/model/MDocBaseType.java
  base/src/org/compiere/model/MDocType.java
  base/src/org/compiere/model/X_C_DocBaseType.java
  base/src/org/compiere/model/X_C_DocType.java
  migration/393lts-394lts/07970_Add_Document_Base_Type_Window.xml
  migration/393lts-394lts/07980_Add_Document_Base_Type_Field_On_Document_Type_Window.xml
  migration/393lts-394lts/07990_Add_Document_Base_Type_Data.xml
  migration/393lts-394lts/08000_Document_Base_Type_Not_Updatable.xml
  migration/393lts-394lts/08010_Definition_for_Asset_Accounting_Logic.xml
  migration/393lts-394lts/08020_Changes_in_Document_Type_Window.xml
  migration/393lts-394lts/08030_Add_Logic_for_Manufacturing_Planned_Order.xml
Labels: (AC) Accounting, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance

#3538 Add support to artifact for each building
  .github/workflows/main.yml
Labels: (CI) Continuous Integration

#3534 Remove autocomplete feature for migration data
  migration/393lts-394lts/08040_Remove_Autocomplete_feature_for_Migration_Data.xml
Labels: (MT) Migration Tools, 02 bug

#3544 Correct ANT library to version 1.10.10
  .classpath
Labels: 02 bug, 08 IDE

#3546 Fix for #3535 AcctProcessor throws an NPE when first initialized.
  serverRoot/src/main/server/org/compiere/server/AcctProcessor.java
  serverRoot/src/test/server/org/compiere/server/AcctProcessor_IT.java
Labels: 02 bug

#3543 Add support to converted attributes for payroll
  base/src/org/eevolution/model/I_HR_Attribute.java
  base/src/org/eevolution/model/X_HR_Attribute.java
  migration/393lts-394lts/08890_Add_support_to_converted_attributes.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRMovement.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement

#3536 Add Queue Manager support
  base/src/org/spin/queue/model/I_AD_Queue.java
  base/src/org/spin/queue/model/I_AD_QueueType.java
  base/src/org/spin/queue/model/MADQueue.java
  base/src/org/spin/queue/model/MADQueueType.java
  base/src/org/spin/queue/model/X_AD_Queue.java
  base/src/org/spin/queue/model/X_AD_QueueType.java
  base/src/org/spin/queue/notification/AttachmentStub.java
  base/src/org/spin/queue/notification/DefaultNotifier.java
  base/src/org/spin/queue/notification/model/I_AD_NotificationQueue.java
  base/src/org/spin/queue/notification/model/I_AD_NotificationRecipient.java
  base/src/org/spin/queue/notification/model/MADNotificationQueue.java
  base/src/org/spin/queue/notification/model/MADNotificationRecipient.java
  base/src/org/spin/queue/notification/model/X_AD_NotificationQueue.java
  base/src/org/spin/queue/notification/model/X_AD_NotificationRecipient.java
  base/src/org/spin/queue/notification/support/EMailSender.java
  base/src/org/spin/queue/notification/support/INotification.java
  base/src/org/spin/queue/notification/support/NoteSender.java
  base/src/org/spin/queue/process/FlushSystemQueue.java
  base/src/org/spin/queue/process/FlushSystemQueueAbstract.java
  base/src/org/spin/queue/setup/QueueSetup.java
  base/src/org/spin/queue/test/DefaultTest.java
  base/src/org/spin/queue/util/QueueLoader.java
  base/src/org/spin/queue/util/QueueManager.java
  migration/393lts-394lts/08250_Queue_Add_Queue_Functionality_Entity_Type.xml
  migration/393lts-394lts/08260_Queue_Add_System_Queue_Functionality.xml
  migration/393lts-394lts/08270_Queue_Change_Parameters_type_for_Flush_Queue_Process.xml
  migration/393lts-394lts/08280_Queue_Add_Delete_Record_Parameter.xml
  migration/393lts-394lts/08310_Queue_Add_Test_Queue_Manager.xml
  migration/393lts-394lts/08320_Queue_Add_Test_Queue_Manager_Implementation.xml
  migration/393lts-394lts/08330_Queue_Add_Queue_Type_as_Parameter.xml
  migration/393lts-394lts/08340_Queue_Add_Setup_Definition.xml
  migration/393lts-394lts/08770_Queue_Add_Notifier_Entity_Type.xml
  migration/393lts-394lts/08790_Queue_Add_Notification_Entities.xml
  migration/393lts-394lts/08800_Queue_Add_Notifier_Implementation.xml
  migration/393lts-394lts/08810_Queue_Add_Backward_Compatibility.xml
  migration/393lts-394lts/08820_Queue_Rename_class_for_Senders.xml
Labels: (AS) Application Server, (CI) Code Improvement or Optimization, (SS) Scheduler, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance, 14 Waiting for User Changes

#3550 Change element "Text" translation
  migration/393lts-394lts/09210_Change_name_for_Text_element.xml
Labels: (MNC) Minor Change

#3532 Add support to ASP by role
  base/src/org/compiere/model/MRole.java
  base/src/org/spin/util/ASPUtil.java
  migration/393lts-394lts/07970_Add_ASP_Access_by_Role.xml
Labels: 01 enhancement, 10 Reviewed by Peer, 12 Feature

#3552 Add support to flag for receive notification
  base/src/org/compiere/model/I_AD_User.java
  base/src/org/compiere/model/MUser.java
  base/src/org/compiere/model/X_AD_User.java
  base/src/org/spin/model/I_AD_AppRegistration.java
  base/src/org/spin/model/I_AD_AppSupport.java
  base/src/org/spin/model/I_AD_UserSocialMedia.java
  base/src/org/spin/model/MADUserSocialMedia.java
  base/src/org/spin/model/X_AD_AppRegistration.java
  base/src/org/spin/model/X_AD_AppSupport.java
  base/src/org/spin/model/X_AD_UserSocialMedia.java
  base/src/org/spin/queue/model/X_AD_QueueType.java
  base/src/org/spin/queue/notification/DefaultNotifier.java
  migration/393lts-394lts/09220_Add_Flag_for_receive_notification_on_Social_Media.xml
Labels: 01 enhancement

#3575 Reverse the Sales Transaction from POS does not include the Reverse Payment in Bank Statement
  org.adempiere.pos/src/main/java/base/org/adempiere/pos/process/ReverseTheSalesTransaction.java
Labels: (POS) Point Of Sales, 01 enhancement

#3579 Fix root source marked as test source in IntelliJ's adempiere.iml
  adempiere.iml
Labels: (SC) System Core, 01 enhancement

#3584 [Bug Report] Update library Commons Collections the last version
  .classpath
  adempiere.iml
  base/src/org/compiere/model/MTableScriptValidator.java
  base/src/org/compiere/process/RequisitionPOCreate.java
  db/ddlutils/lib/commons-collections-3.1.jar
  jboss/server/adempiere/lib/commons-collections.jar
  org.adempiere.asset/src/main/java/base/org/compiere/model/MAssetAcct.java
  org.adempiere.asset/src/main/java/base/org/compiere/model/MDepreciationWorkfile.java
  org.adempiere.webservice/WEB-INF/lib/commons-collections-2.1.jar
  org.compiere.mobile/WEB-INF/lib/commons-collections-3.1.jar
  serverApps/src/web/WEB-INF/lib/commons-collections-3.1.jar
  tools/build.xml
  tools/lib/commons-collections-3.2.2.jar
  tools/lib/commons-collections4-4.1.jar
  tools/lib/commons-collections4-4.4.jar
Labels: (SE) Security, 02 bug
