Repository adempiere/adempiere, pull requests merged in 2021-09, with the labels that each got.

#3548 Improve performance for payroll execution
  base/src/org/compiere/model/I_AD_Rule.java
  base/src/org/compiere/model/MRule.java
  base/src/org/compiere/model/X_AD_Rule.java
  base/src/org/spin/process/RuleGenerateClass.java
  base/src/org/spin/process/RuleGenerateClassAbstract.java
  base/src/org/spin/util/RuleClassGenerator.java
  base/src/org/spin/util/RuleEngineUtil.java
  migration/393lts-394lts/09200_Improve_performance_for_payroll_based_on_java_running.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRProcess.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/util/PayrollEngineHandler.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/util/RuleInterface.java
Labels: 01 enhancement, (HRM) Human Resource and Payroll Management, (CIO) Code Improvement or Optimization, 10 Reviewed by Peer

#3592 Improve modification indication UX in Swing editor
  client/src/org/compiere/grid/ed/VCellEditor.java
  client/src/org/compiere/grid/ed/VMemo.java
  client/src/org/compiere/grid/ed/VString.java
  client/src/org/compiere/grid/ed/VText.java
Labels: 01 enhancement, 10 Reviewed by Peer, 23 reproduced

#3609 Remove c3p0 connection leak workaround
  base/src/org/compiere/db/DB_MariaDB.java
  base/src/org/compiere/db/DB_MySQL.java
  base/src/org/compiere/db/DB_Oracle.java
  base/src/org/compiere/db/DB_PostgreSQL.java
Labels: 02 bug, (SC) System Core

#3610 Remove duplicated slf4j-api package
  .classpath
  tools/lib/slf4j-api-1.6.0.jar
Labels: 01 enhancement, (CIO) Code Improvement or Optimization

#3608 Retain selected row when sorting grid table
  base/src/org/compiere/model/GridTab.java
  base/src/org/compiere/model/GridTable.java
  client/src/org/compiere/grid/GridController.java
Labels: 02 bug, (UI) User Interface Improvement, 10 Reviewed by Peer

#3605 Fix TimeUtilTest in timezone with positive offset
  base/test/src/org/compiere/util/TimeUtilTest.java
Labels: 02 bug, 09 Pending Peer Review, 21 Testing

#3615 Improve consistence of two Swing icons
  client/src/org/compiere/images/End24.gif
  client/src/org/compiere/images/GetMail24.gif
Labels: 10 Reviewed by Peer, (SWI) Swing

#3617 Disable default keymaps for F6 and F8 in JSplitPane
  client/src/org/compiere/grid/GridController.java
Labels: 10 Reviewed by Peer, 23 reproduced, (SWI) Swing

#3618 Fix NPE when changing themes from Nimbus in Swing
  base/src/org/adempiere/plaf/PLAFEditorPanel.java
Labels: 23 reproduced, (SWI) Swing

#3619 Improve sidebar UI for Compiere theme in Swing
  base/src/org/compiere/plaf/CompiereButtonUI.java
Labels: 10 Reviewed by Peer, 23 reproduced, (SWI) Swing

#3620 fixed error with getLines(String, String) method
  org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
Labels: 02 bug, (WMS) Warehouse Management System, 10 Reviewed by Peer

#3614 Fix broken input method in single-row mode in Swing UI
  client/src/org/compiere/grid/ed/VMemo.java
  client/src/org/compiere/grid/ed/VText.java
Labels: 10 Reviewed by Peer, 23 reproduced, (SWI) Swing

#3616 [Bug Report] Error when ADempiere Server WebUI is shut down causing a possible memory leak
  base/src/org/compiere/util/Login.java
  tomcat/conf/context.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/AdempiereWebUI.java
  zkwebui/WEB-INF/src/org/adempiere/webui/IWebClient.java
  zkwebui/WEB-INF/src/org/adempiere/webui/ServerContextCallback.java
  zkwebui/WEB-INF/src/org/adempiere/webui/TimelineEventFeed.java
  zkwebui/WEB-INF/src/org/adempiere/webui/WLogin.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WGenForm.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/SimpleFavoriteTreeModel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DPFavourites.java
  zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DashboardRunnable.java
  zkwebui/WEB-INF/src/org/adempiere/webui/desktop/DefaultDesktop.java
  zkwebui/WEB-INF/src/org/adempiere/webui/desktop/NavBar2Desktop.java
  zkwebui/WEB-INF/src/org/adempiere/webui/desktop/NavBarDesktop.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADWindowPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/LoginPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/LogoutPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/RolePanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/UserPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/session/ServerContext.java
  zkwebui/WEB-INF/src/org/adempiere/webui/session/SessionContextListener.java
  zkwebui/WEB-INF/src/org/adempiere/webui/session/SessionManager.java
  zkwebui/WEB-INF/src/org/adempiere/webui/session/WebUIServlet.java
  zkwebui/WEB-INF/src/org/adempiere/webui/util/UserPreference.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/LoginWindow.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WContext.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WPreference.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/ZkReportViewerProvider.java
  zkwebui/WEB-INF/web.xml
Labels: 02 bug, (SC) System Core, (UI) User Interface Improvement, 09 Pending Peer Review

#3621 Reduce heap usage of Compiere theme
  base/src/org/compiere/plaf/CompiereUtils.java
Labels: 10 Reviewed by Peer, 23 reproduced, (SWI) Swing

#3632 #3631 [Bug Report] Migration XML 05920 For Oracle https://github.com…
  migration/393lts-394lts/05920_Fixed_Return_Quantity_for_Shipment_Details_report.xml
Labels: 02 bug, (MT) Migration Tools

#3630 Wrong cached context on EMailSender
  base/src/org/compiere/util/EMail.java
Labels: 02 bug, (NQS) Notification Queue Suport

#3408 Adempiere #3407 Taxdeclaration Consider DateAcct
  base/src/org/compiere/process/TaxDeclarationCreate.java
  base/src/org/compiere/process/TaxDeclarationCreateAbstract.java
  migration/393lts-394lts/07920_TaxDeclaration_Enhance.xml
Labels: 01 enhancement, 09 Pending Peer Review, (AC) Accounting, ZZ Motionless
