Repository adempiere/adempiere, pull requests merged in 2021-10, with the labels that each got.

#3642 Fixed error with receipt based on major quantity of purchase order
  org.eevolution.warehouse/src/main/java/base/org/eevolution/model/MWMInOutBound.java
Labels: (WMS) Warehouse Management System

#3628 Remove redundant empty rows in CSV export
  base/src/org/spin/util/AbstractExportFormat.java
Labels: 01 enhancement, 10 Reviewed by Peer, (MNC) Minor Change

#3607 Add Included and Excluded Payments for bank statement
  base/src/org/compiere/impexp/BankStatementMatcherInterface.java
  base/src/org/compiere/process/BankStatementMatcher.java
  base/src/org/spin/util/impexp/GenericBankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoLeftLike_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoLikeWithImport_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoLikeWithPayment_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoLike_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNoRightLike_BankMatcher.java
  base/src/org/spin/util/impexp/ReferenceNo_BankMatcher.java
  client/src/org/spin/apps/form/BankStatementMatchController.java
Labels: (SC) System Core, (FIM) Financial Management, 10 Reviewed by Peer

#3662 #3641 [Feature Request] Add es_CL language for Chilean location
  base/src/org/compiere/util/Language.java
Labels: 01 enhancement, (TRL) Translation

#3572 Refactory: Project Processor By Email based on new notification queue
  serverRoot/src/main/server/org/compiere/server/ProjectProcessor.java
Labels: (CIO) Code Improvement or Optimization, 10 Reviewed by Peer, (NQS) Notification Queue Suport
