Repository adempiere/adempiere, pull requests merged in 2021-03, with the labels that each got.

#3369 #3368 Throws an error when doing partial receipts from an outsourced …
  base/src/org/eevolution/model/MPPCostCollector.java
Labels: (PMM) Planning and Manufacturing Management, 02 bug

#3379 #3378 [Bug Report] PostgreSQL Database Procedure not work https://git…
  base/src/org/adempiere/util/ProcessUtil.java
Labels: (SC) System Core, 02 bug

#3391 Feature/#3390 rounding problem calculate tax
  base/src/org/compiere/model/MInvoiceTax.java
Labels: (AC) Accounting

#3367 Improve error message for concept beforeSave error
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/model/MHRConcept.java
Labels: (HRM) Human Resource and Payroll Management, 01 enhancement

#3398 Adempiere #3397 Error of qtyreserved and qtyordered in MProduction
  base/src/org/compiere/model/MProduction.java
  base/src/org/compiere/model/MProductionBatchLine.java
Labels: 02 bug

#3366 Ignore error when export role from packout
  base/src/org/adempiere/pipo/handler/RoleElementHandler.java
Labels: (PIO) Packin / Packout, 01 enhancement

#3400 Fixed error with wrong XML
  migration/393lts-394lts/07650_Add_Order_Line_Reference_for_Financial_Transaction.xml
Labels: (FIM) Financial Management, 02 bug

#3420 Allows inactive records for ASP packout handler
  base/src/org/adempiere/pipo/handler/ASPModuleElementHandler.java
Labels: (PIO) Packin / Packout, 02 bug
