Repository adempiere/adempiere, pull requests merged in 2021-05, with the labels that each got.

#3451 Fixed error with wrong validation for Sales Order
  base/src/org/compiere/model/MOrder.java
Labels: (SO) Sales Management, 02 bug

#3434 Feature/#ci add seed xml support
  .github/workflows/main.yml
  .github/workflows/release.yml
  build.xml
  utils/PostgreSQL/ExportReference.sh
  utils/RUN_ExportReference.sh
  utils/adempiereProperties_CI.properties
  utils/myEnvironment_CI.sh
Labels: (CI) Continuous Integration, 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance

#3466 #3465 [Bug Report] Error when try delete a material receipt created f…
  base/src/org/compiere/model/MInOut.java
Labels: (MM) Material Management, 01 enhancement

#3444 Fixed error with NPE for system reports
  base/src/org/compiere/print/MPrintFormatItem.java
Labels: (PF) Report Engine & Print Format, 02 bug, 10 Reviewed by Peer, 17 Waiting for Information, 19 Not reproducible

#3448 Fixed error with Import ARXML of Print format
  base/src/org/adempiere/pipo/handler/PrintFormatElementHandler.java
Labels: (PIO) Packin / Packout, 02 bug, 09 Pending Peer Review

#3455 Add Purchasing Tab to Business Partner
  migration/393lts-394lts/07780_Add_Purchasing_Tab_to_Business_Partner.xml
Labels: (SC) System Core, 01 enhancement

#3456 Fixed wrong search for concept acct
  org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
Labels: (AC) Accounting, (HRM) Human Resource and Payroll Management, (PA) Performance Analysis and General Ledger, 02 bug

#3457 Add some columns for RV_C_RFQResponse
  db/ddlutils/oracle/views/RV_C_RFQRESPONSE.sql
  db/ddlutils/postgresql/views/RV_C_RFQRESPONSE.sql
  migration/393lts-394lts/07710_Add_columns_to_RV_C_RFQResponse_View.xml
Labels: (PO) Purchase Management, 12 Feature

#3459 Fixed error with parent link for W_Category
  migration/393lts-394lts/07830_Fixed_error_with_link_reference_for_Web_category.xml
Labels: (VSF) Web Store Front-Vue, 02 bug

#3461 Add support to included role for ASP
  base/src/org/spin/util/ASPUtil.java
Labels: (SE) Security, 01 enhancement

#3377 Fix/#3309 fix garden world clean up
  .github/workflows/main.yml
  base/src/org/adempiere/process/MigrationLoader.java
  base/src/org/compiere/process/GardenWorldCleanUp.java
  base/src/org/compiere/process/GardenWorldCleanup.java
  base/src/org/compiere/process/GardenWorldCleanupAbstract.java
  base/src/org/compiere/util/Msg.java
  base/test/src/org/compiere/model/IT_Inventory.java
  base/test/src/org/compiere/process/GardenWorldCleanup_IT.java
  base/test/src/org/compiere/process/GardenWorldCleanup_Test.java
  base/test/src/org/compiere/util/TestMsg.java
  migration/393lts-394lts/07670_3309_RefactorAndFixGardenWorldCleanup.xml
  org.adempiere.test/src/test/java/org/adempiere/test/CommonGWData.java
  org.adempiere.test/src/test/java/org/adempiere/test/CommonIntegrationTestUtilities.java
Labels: 02 bug, 09 Pending Peer Review

#3453 Improve Standard Request Type
  base/src/org/compiere/model/I_R_StandardRequest.java
  base/src/org/compiere/model/X_R_StandardRequest.java
  base/src/org/compiere/util/TimeUtil.java
  migration/393lts-394lts/07690_Add_Subject_for_Standard_Request_Type.xml
  org.adempiere.request/src/main/java/org/compiere/model/MStandardRequestType.java
  org.adempiere.request/src/main/java/org/compiere/model/RequestModelValidator.java
Labels: (RM) Request Management, 10 Reviewed by Peer, 12 Feature
