Repository adempiere/adempiere, pull requests merged in 2021-08, with the labels that each got.

#3557 Enlarge length for Description on Order and Invoice
  migration/393lts-394lts/09240_Enlarge_length_for_Description_on_Order_and_Invoice.xml
Labels: (SC) System Core, 01 enhancement, 10 Reviewed by Peer

#3556 Fixed error after press ok on Bank Statement Matcher
  client/src/org/spin/apps/form/BankStatementMatchController.java
  client/src/org/spin/apps/form/VBankStatementMatch.java
  zkwebui/WEB-INF/src/org/spin/apps/form/WBankStatementMatch.java
Labels: (FIM) Financial Management, 02 bug

#3585 [Feature Request] Change Connection pool library c3p0 to HikariCP
  .classpath
  adempiere.iml
  base/src/org/compiere/db/DB_MariaDB.java
  base/src/org/compiere/db/DB_MySQL.java
  base/src/org/compiere/db/DB_Oracle.java
  base/src/org/compiere/db/DB_PostgreSQL.java
  tools/build.xml
  tools/lib/HikariCP-5.0.0.jar
  tools/lib/c3p0-0.9.1.2.jar
  tools/lib/c3p0-oracle-thin-extras-0.9.1.2.jar
  tools/lib/slf4j-api-1.7.32.jar
  tools/lib/slf4j-simple-1.7.32.jar
Labels: (SC) System Core, 01 enhancement, 10 Reviewed by Peer, 14 Waiting for User Changes

#3589 [Bug Report] Error when ADempiere Application Server Admin is shut down causing a possible memory lea
  base/src/org/compiere/model/AdempiereProcessor.java
  build.sbt
  install/Adempiere/AdempiereEnvTemplate.properties
  lib/server.xml
  project/build.properties
  project/plugins.sbt
  serverRoot/src/main/server/org/compiere/server/AcctProcessor.java
  serverRoot/src/main/server/org/compiere/server/AdempiereServer.java
  serverRoot/src/main/server/org/compiere/server/AdempiereServerMgr.java
  serverRoot/src/main/server/org/compiere/server/AlertProcessor.java
  serverRoot/src/main/server/org/compiere/server/RequestProcessor.java
  serverRoot/src/main/server/org/compiere/server/Scheduler.java
  serverRoot/src/main/server/org/compiere/server/WorkflowProcessor.java
  serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitor.java
  serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitorFilter.java
  serverRoot/src/main/servlet/org/compiere/web/StatusInfo.java
Labels: 02 bug, (SC) System Core, 09 Pending Peer Review, 10 Reviewed by Peer

#3371 Correct navigation issues with ZK.
  base/src/org/compiere/model/GridTab.java
  base/src/org/compiere/model/GridTable.java
  base/test/src/org/compiere/model/TestGridTab.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridTabRowRenderer.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/ADTabPanel.java
  zkwebui/WEB-INF/test/src/org/adempiere/webui/component/GridPanel_Test.java
  zkwebui/WEB-INF/test/src/org/adempiere/webui/component/GridTabRowRenderer_Test.java
Labels: 02 bug, (UI) User Interface Improvement, 09 Pending Peer Review, 10 Reviewed by Peer, 13 Pending Acceptance

#3593 Add new currency for Venezuela VED
  migration/393lts-394lts/09230_Add_new_Currency_for_Venezuela_Bolivar_Digital.xml
Labels: (SC) System Core, (FIM) Financial Management

#3595 Minor change for validation SO
  base/src/org/compiere/model/MOrderLine.java
Labels: 01 enhancement, (SO) Sales Management, (POS) Point Of Sales, 10 Reviewed by Peer, 23 reproduced

#3568 change wrong validation for user on notifier
  base/src/org/spin/queue/notification/DefaultNotifier.java
  migration/393lts-394lts/09260_Remove_Mandatory_Account_Name_of_Notification_Recipient.xml
Labels: 02 bug, (NQS) Notification Queue Suport

#3591 Fix: When the email address is malformed, not log this message
  base/src/org/spin/queue/notification/support/EMailSender.java
Labels: (NQS) Notification Queue Suport

#3596 Add payment method reference for payment
  migration/393lts-394lts/09250_Add_Payment_Method_on_Payment.xml
Labels: (SC) System Core, (FIM) Financial Management, 10 Reviewed by Peer, 23 reproduced

#3602 Add Waiting Time for Queue Type
  base/src/org/spin/queue/model/I_AD_QueueType.java
  base/src/org/spin/queue/model/X_AD_QueueType.java
  base/src/org/spin/queue/process/FlushSystemQueue.java
  base/src/org/spin/queue/util/QueueManager.java
  migration/393lts-394lts/09250_Add_duration_for_queue_type.xml
Labels: 01 enhancement, 09 Pending Peer Review, (NQS) Notification Queue Suport

#3603 Fixed process selection when summary row is the first row
  zkwebui/WEB-INF/src/org/eevolution/grid/WBrowserListItemRenderer.java
Labels: 02 bug, (UI) User Interface Improvement, 10 Reviewed by Peer, (SB) Smart Browser, 23 reproduced
