Repository adempiere/adempiere, pull requests merged in 2022-06, with the labels that each got.

#3874 adempiere #3873 Year End Closing
  base/src/org/adempiere/process/YearEndClosing.java
  base/src/org/adempiere/process/YearEndClosingAbstract.java
  migration/393lts-394lts/09400_YearEndClosing.xml
Labels: 09 Pending Peer Review, 12 Feature, (AC) Accounting

#3879 Rename Request Package
  client/src/org/compiere/apps/ARequest.java
  migration/393lts-394lts/09630_Rename_Request_Package.xml
  org.adempiere.request/build.gradle
  org.adempiere.request/build.xml
  org.adempiere.request/src/main/java/org/compiere/model/RequestModelValidator.java
  org.adempiere.request/src/main/java/org/compiere/request/apps/Request.java
  org.adempiere.request/src/main/java/org/compiere/request/controller/CalloutRequest.java
  org.adempiere.request/src/main/java/org/compiere/request/model/validator/RequestModelValidator.java
  org.adempiere.request/src/main/java/org/compiere/request/process/RequestEMailProcessor.java
  org.adempiere.request/src/main/java/org/compiere/request/process/RequestEMailProcessorAbstract.java
  org.adempiere.request/src/main/java/org/compiere/request/process/RequestInvoice.java
  org.adempiere.request/src/main/java/org/compiere/request/process/RequestInvoiceAbstract.java
  org.adempiere.request/src/main/java/org/compiere/request/process/RequestReOpen.java
  org.adempiere.request/src/main/java/org/compiere/request/process/RequestReOpenAbstract.java
  tools/lib/legacy/request-request-support-legacy-1.0.0.jar
  zkwebui/WEB-INF/src/org/adempiere/webui/WRequest.java
Labels: 10 Reviewed by Peer, 13 Pending Acceptance, 20 Refactoring

#3904 feat: Add selection columns in Conversion Rate.
  migration/393lts-394lts/09700_ConversionRate_Selection_Columns.xml
Labels: 01 enhancement, 09 Pending Peer Review, (AC) Accounting, (MNC) Minor Change

#3905 feat: Add selection columns in smart browse.
  migration/393lts-394lts/09710_Smart_Browse_Selection_Columns.xml
Labels: 01 enhancement, 09 Pending Peer Review, (SB) Smart Browser

#3886 Add support to CRM as class name of core
  base/src/org/compiere/model/MTable.java
Labels: (AD) Application Dictionary, 10 Reviewed by Peer, 13 Pending Acceptance, 20 Refactoring

#3880 Rename Cashflow Package
  migration/393lts-394lts/09640_Rename_Cashflow_Package.xml
  org.eevolution.cashflow/build.gradle
  org.eevolution.cashflow/build.xml
  org.eevolution.cashflow/src/main/java/org/eevolution/cashflow/controller/CalloutCashFlow.java
  org.eevolution.cashflow/src/main/java/org/eevolution/cashflow/model/MCashFlow.java
  org.eevolution.cashflow/src/main/java/org/eevolution/cashflow/process/CashFlow.java
  org.eevolution.cashflow/src/main/java/org/eevolution/cashflow/process/CashFlowAbstract.java
  org.eevolution.cashflow/src/main/java/org/eevolution/cashflow/process/CashFlowProcessing.java
  org.eevolution.cashflow/src/main/java/org/eevolution/cashflow/process/CashFlowProcessingAbstract.java
  tools/lib/legacy/cashflow-support-legacy-1.0.0.jar
Labels: 10 Reviewed by Peer, 13 Pending Acceptance, 20 Refactoring

#3859 Create LICENSE
  LICENSE
Labels: 01 enhancement, 10 Reviewed by Peer, 13 Pending Acceptance

#3889 Rename Freight Package
  base/src/org/compiere/model/MFreight.java
  migration/393lts-394lts/09680_Rename_base_package_of_Freight.xml
  org.eevolution.freight/build.gradle
  org.eevolution.freight/build.xml
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/engine/FreightEngine.java
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/engine/FreightEngineFactory.java
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/engine/FreightInfo.java
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/engine/FreightRule.java
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/engine/FreightRuleInterface.java
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/model/validator/Freight.java
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/service/FreightService.java
  org.eevolution.freight/src/main/java/base/org/eevolution/freight/service/FreightServiceInterface.java
  org.eevolution.freight/src/main/java/base/org/eevolution/service/FreightService.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/CreateFreightOrderFromPackage.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/CreateFreightOrderFromPackageAbstract.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/GenerateAPInvoiceFromFreightOrder.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/GenerateAPInvoiceFromFreightOrderAbstract.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/GenerateFreightOrderFromOutbound.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/GenerateFreightOrderFromOutboundAbstract.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/GenerateSalesInvoiceFromFreightOrder.java
  org.eevolution.freight/src/main/java/base/org/spin/freight/process/GenerateSalesInvoiceFromFreightOrderAbstract.java
  tools/lib/legacy/freight-support-legacy-1.0.0.jar
Labels: 09 Pending Peer Review, 13 Pending Acceptance, 20 Refactoring

#3907 #3744 [Feature Request] Login Remove the Result Set and Adding Integr…
  base/src/org/compiere/util/Login.java
Labels: 02 bug, (SC) System Core, 10 Reviewed by Peer

#3903 #3902 [Bug Report] ADempiere WebStore login.jsp [${initParam.#AD_Clie…
  webStore/src/web/assets.jsp
  webStore/src/web/emailVerify.jsp
  webStore/src/web/login.jsp
  webStore/src/web/update.jsp
Labels: 02 bug, (SC) System Core, 10 Reviewed by Peer, 17 Waiting for Information, (AS) Application Server

#3901 #3900 [Feature Request] Add SSL/HTTPS support for ADempiere deploymen…
  utils/RUN_Server2.bat
  utils/RUN_Server2.sh
Labels: 01 enhancement, 10 Reviewed by Peer

#3911 feat: Configure Centralized ID Management process.
  base/src/org/adempiere/process/ConfigureCentralizedIdManagement.java
  base/src/org/adempiere/process/ConfigureCentralizedIdManagementAbstract.java
  base/src/org/compiere/model/MSysConfig.java
  migration/393lts-394lts/09720_Update_System_Configurator_Dictionary_Centralized_ID.xml
  migration/393lts-394lts/09730_Configure_Centralized_ID_Management_Process.xml
Labels: 01 enhancement, (SA) System Administrator, 10 Reviewed by Peer, 13 Pending Acceptance

#3915 adempiere #3914Doc_HRProcess, wrong concept accounting for 2 Accounting Schemas
  org.eevolution.hr_and_payroll/src/main/java/base/org/compiere/acct/Doc_HRProcess.java
Labels: 02 bug, (HRM) Human Resource and Payroll Management, (AC) Accounting

#3906 Disable NotificationRecipient on error
  base/src/org/spin/queue/notification/support/EMailSender.java
Labels: 02 bug, (RM) Request Management

#3917 #3916 [Bug Report] Now it is not possible to deactivate the sending o…
  base/src/org/compiere/model/MScheduler.java
  serverRoot/src/main/server/org/compiere/server/Scheduler.java
Labels: 02 bug, (SS) Scheduler

#3926 #3925 [Feature Request] Adding Reconciled to Window Payment
  migration/393lts-394lts/09740_3925_Adding_Reconciled_To_Window_Payment.xml
Labels: 01 enhancement, (AR) Account Receivable, (AP) Account Payable, 10 Reviewed by Peer

#3929 fix: Preview JasperReports on swing client.
  JasperReports/src/org/compiere/report/ReportStarter.java
Labels: 02 bug, 10 Reviewed by Peer, (PF) Report Engine & Print Format, (SWI) Swing
