Repository adempiere/adempiere, pull requests merged in 2022-04, with the labels that each got.

#3783 adempiere 3782 MOrder voidIt terminated
  base/src/org/compiere/model/MOrder.java
Labels: 02 bug

#3780 fix: RUN_setup.bat on Windows.
  utils/functions.bat
Labels: 02 bug, (INS) Installation

#3785 Separation of Request Management
  base/src/org/compiere/model/MChangeRequest.java
  base/src/org/compiere/model/MContactInterest.java
  base/src/org/compiere/model/MGroup.java
  base/src/org/compiere/model/MInterestArea.java
  base/src/org/compiere/model/MIssueProject.java
  base/src/org/compiere/model/MIssueSystem.java
  base/src/org/compiere/model/MIssueUser.java
  base/src/org/compiere/model/MMailText.java
  base/src/org/compiere/model/MRequest.java
  base/src/org/compiere/model/MRequestAction.java
  base/src/org/compiere/model/MRequestCategory.java
  base/src/org/compiere/model/MRequestCategoryUpdates.java
  base/src/org/compiere/model/MRequestGroupUpdates.java
  base/src/org/compiere/model/MRequestIssueKnown.java
  base/src/org/compiere/model/MRequestIssueRecommendation.java
  base/src/org/compiere/model/MRequestIssueStatus.java
  base/src/org/compiere/model/MRequestProcessor.java
  base/src/org/compiere/model/MRequestProcessorLog.java
  base/src/org/compiere/model/MRequestProcessorRoute.java
  base/src/org/compiere/model/MRequestType.java
  base/src/org/compiere/model/MRequestTypeUpdates.java
  base/src/org/compiere/model/MRequestUpdate.java
  base/src/org/compiere/model/MRequestUpdates.java
  base/src/org/compiere/model/MResolution.java
  base/src/org/compiere/model/MStandardRequest.java
  base/src/org/compiere/model/MStandardRequestType.java
  base/src/org/compiere/model/MStandardResponse.java
  base/src/org/compiere/model/MStatus.java
  base/src/org/compiere/model/MStatusCategory.java
  base/src/org/spin/model/MRNoticeTemplate.java
  base/src/org/spin/model/MRNoticeTemplateEvent.java
Labels: (CIO) Code Improvement or Optimization, 10 Reviewed by Peer, 20 Refactoring

#3786 Separation of Project Management
  base/src/org/compiere/model/MProject.java
  base/src/org/compiere/model/MProjectIssue.java
  base/src/org/compiere/model/MProjectLine.java
  base/src/org/compiere/model/MProjectPhase.java
  base/src/org/compiere/model/MProjectProcessorChange.java
  base/src/org/compiere/model/MProjectProcessorQueued.java
  base/src/org/compiere/model/MProjectTask.java
  base/src/org/compiere/model/MProjectType.java
  base/src/org/compiere/model/MProjectTypePhase.java
  base/src/org/compiere/model/MProjectTypeTask.java
  base/src/org/eevolution/model/MProjectCategory.java
  base/src/org/eevolution/model/MProjectClass.java
  base/src/org/eevolution/model/MProjectGroup.java
  base/src/org/eevolution/model/MProjectMember.java
  base/src/org/eevolution/model/MProjectMemberTyoe.java
  base/src/org/eevolution/model/MProjectProcessor.java
  base/src/org/eevolution/model/MProjectProcessorLog.java
  base/src/org/eevolution/model/MProjectStatus.java
  base/src/org/eevolution/model/MProjectStatusCategory.java
  base/src/org/eevolution/model/MProjectTaskCategory.java
Labels: (CIO) Code Improvement or Optimization, 10 Reviewed by Peer, 20 Refactoring

#3799 This pull request just add support to gradle builder to fleet source folder
  org.eevolution.fleet/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3798 This pull request just add support to gradle builder to cashflow source folder
  org.eevolution.cashflow/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3796 This pull request just add support to gradle builder to production source folder
  org.adempiere.production/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3795 This pull request just add support to gradle builder to crm source folder
  org.adempiere.crm/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3794 This pull request just add support to gradle builder to asset source folder
  org.adempiere.asset/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3793 This pull request just add support to gradle builder to project source folder
  org.adempiere.project/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3790 This pull request just add support to gradle builder to extend source folder
  extend/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3789 This pull request just add support to gradle builder to tools source
  tools/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3788 This pull request just add support to gradle builder to base source
  base/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3797 This pull request just add support to gradle builder to migration source folder
  migration/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3791 This pull request just add support to gradle builder to request source
  org.adempiere.request/build.gradle
Labels: (CIO) Code Improvement or Optimization, 20 Refactoring

#3792 fix: The Boolean constructor is deprecated.
  base/src/org/adempiere/pipo/handler/DataElementHandler.java
  base/src/org/adempiere/util/rpl/EntityWrapper.java
  base/src/org/compiere/model/CalloutOrder.java
  base/src/org/compiere/model/CalloutPaySelection.java
  base/src/org/compiere/model/GridTable.java
  base/src/org/compiere/model/MProductPricing.java
  base/src/org/compiere/model/MRole.java
  base/src/org/compiere/model/PO.java
  base/src/org/compiere/model/Scriptlet.java
  base/src/org/compiere/process/ChangeLogProcess.java
  base/src/org/compiere/wf/MWFActivity.java
  base/src/org/compiere/wf/MWFNodeNext.java
  base/src/org/eevolution/model/MPPOrderNodeNext.java
  client/src/org/adempiere/controller/form/BOMDropController.java
  client/src/org/compiere/apps/OnlineHelp.java
  client/src/org/compiere/apps/form/Charge.java
  client/src/org/compiere/apps/form/CreateFromRMA.java
  client/src/org/compiere/apps/form/VTreeBOM.java
  client/src/org/compiere/apps/search/Info.java
  client/src/org/compiere/apps/search/InvoiceHistory.java
  client/src/org/compiere/grid/ed/VCheckBox.java
  client/src/org/compiere/grid/ed/VRadioButton.java
  client/src/org/compiere/grid/ed/VRowIDEditor.java
  client/src/org/compiere/minigrid/MiniTable.java
  client/src/org/compiere/report/core/RModelData.java
  client/src/org/compiere/swing/CCheckBox.java
  client/src/org/compiere/swing/CField.java
  client/src/org/compiere/swing/CRadioButton.java
  client/src/org/eevolution/grid/Browser.java
  install/src/org/compiere/install/ConfigurationPanel.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSTable.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ModelADServiceImpl.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VMRPDetailed.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VOrderPlanning.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VTreeBOM.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/RadioButtonTreeCellRenderer.java
  org.eevolution.manufacturing/src/main/java/ui/zk/org/eevolution/form/WTreeBOM.java
  org.eevolution.warehouse/src/main/java/base/org/spin/form/OutBoundOrder.java
  tools/src/org/apache/ecs/ECSDefaults.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WCreateFromPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/Checkbox.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/WListbox.java
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WRadioEditor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WYesNoEditor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InvoiceHistory.java
Labels: 09 Pending Peer Review, 20 Refactoring

#3818 This pull request just add support to gradle builder to org.adempiere.test source folder
  base/test/src/org/compiere/model/IT_Inventory.java
  base/test/src/org/compiere/model/InventoryUtil.java
  org.adempiere.test/build.gradle
  org.adempiere.test/src/test/java/org/adempiere/test/CSVFactory.java
  org.adempiere.test/src/test/java/org/adempiere/test/MMDocument.java
  org.adempiere.test/src/test/java/org/adempiere/test/MMScenario.java
Labels: 20 Refactoring

#3819 This pull request just add support to gradle builder to base/test source folder
  base/test/build.gradle
Labels: 20 Refactoring

#3820 Add Unit Test to Assets
  org.adempiere.asset/build.gradle
Labels: 20 Refactoring

#3823 This pull request just add support to gradle builder to org.spin.finance_management source folder
  org.spin.finance_management/build.gradle
Labels: 20 Refactoring

#3822 This pull request just add support to gradle builder to org.spin.hr_time_and_attendance source folder
  org.spin.hr_time_and_attendance/build.gradle
  org.spin.hr_time_and_attendance/src/main/java/base/org/spin/model/MHRShiftIncidence.java
Labels: 20 Refactoring

#3824 This pull request just add support to gradle builder to org.spin.loan_management source folder
  org.spin.loan_management/build.gradle
Labels: 20 Refactoring

#3827 This pull request just add support to gradle builder to org.spin.store source folder
  org.spin.store/build.gradle
Labels: 20 Refactoring

#3828 This pull request just add support to gradle builder to org.eevolution.freight source folder
  org.eevolution.freight/build.gradle
Labels: 20 Refactoring
