Repository adempiere/adempiere, pull requests merged in 2022-05, with the labels that each got.

#3809 #3806 [Feature Request] Adding new fields Latitude, Longitude and Alt…
  base/src/org/compiere/model/I_C_Location.java
  base/src/org/compiere/model/X_C_Location.java
  client/src/org/compiere/grid/ed/VLocationDialog.java
  migration/393lts-394lts/09390_3806_AddingNewFieldsLatitudeLongitudeAltitude.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WLocationDialog.java
Labels: 01 enhancement, (PO) Purchase Management, (SO) Sales Management, 10 Reviewed by Peer

#3833 Repeating record in the price list
  migration/393lts-394lts/07000_Add_ID_for_Product_Price.xml
Labels: 02 bug, (PL) Price Management

#3814 Fix bugs generated in closers
  base/src/org/adempiere/model/GenericZoomProvider.java
Labels: 02 bug, 09 Pending Peer Review, 17 Waiting for Information

#3835 Add P_ADEMPIERE_APPS_TYPE support to Ini loader
  base/src/org/compiere/db/DB_MariaDB.java
  base/src/org/compiere/db/DB_MySQL.java
  base/src/org/compiere/db/DB_Oracle.java
  base/src/org/compiere/db/DB_PostgreSQL.java
  base/src/org/compiere/util/Ini.java
Labels: (CI/CD) Continuous Integration/Continous Delivery

#3804 fix: Warning Enumeration is a raw type.
  base/src/org/compiere/model/MIndex.java
  base/src/org/compiere/model/MTemplate.java
  base/src/org/compiere/model/MTree.java
  base/src/org/compiere/model/MTreeNode.java
  base/src/org/compiere/report/MReportTree.java
  base/src/org/compiere/util/ConnectTest.java
  base/src/org/compiere/util/Ini.java
  base/src/org/compiere/util/WebEnv.java
  base/src/org/compiere/util/WebSessionCtx.java
  base/src/org/compiere/util/ZipUtil.java
  client/src/org/compiere/apps/OnlineHelp.java
  client/src/org/compiere/apps/form/VDeleteEntity.java
  client/src/org/compiere/minigrid/IMiniTable.java
  glassfishfacet/src/org/adempiere/as/glassfish/AdempiereRealm.java
  org.adempiere.request/src/main/java/org/compiere/process/RequestEMailProcessor.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADServiceImpl.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/ProcessInfoHandler.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VProductConfigurationBOM.java
  serverApps/src/main/servlet/org/compiere/wstore/BasketServlet.java
  serverApps/src/main/servlet/org/compiere/wstore/Click.java
  serverApps/src/main/servlet/org/compiere/www/WFilter.java
  serverApps/src/main/servlet/org/compiere/www/WMenu.java
  serverApps/src/main/servlet/org/compiere/www/WWindow.java
  serverRoot/src/main/servlet/org/compiere/web/StatusInfo.java
  sqlj/src/org/compiere/sqlj/Adempiere.java
  sqlj/src/org/compiere/sqlj/Compiere.java
  tools/src/org/apache/ecs/storage/Array.java
  tools/src/org/apache/ecs/storage/Hash.java
  tools/src/org/apache/ecs/xhtml/a.java
  tools/src/org/apache/ecs/xhtml/td.java
  tools/src/org/apache/ecs/xml/XML.java
  webCM/src/main/servlet/org/compiere/cm/cache/CO.java
  webCM/src/main/servlet/org/compiere/cm/xml/Generator.java
  webCM/src/main/servlet/org/compiere/cm/xml/XSLTProcessor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/SimpleTreeModel.java
Labels: 10 Reviewed by Peer, 20 Refactoring

#3805 fix: Run ADempiere-All launcher.
  base/ADempiere-all.launch
Labels: 01 enhancement

#3829 This pull request just add support to gradle builder to org.adempiere.pos source folder
  org.adempiere.pos/build.gradle
  org.adempiere.pos/src/main/java/base/org/adempiere/pos/util/POSTicketHandler.java
  org.adempiere.pos/src/main/java/ui/swing/org/adempiere/pos/util/POSGenericTicketHandler.java
Labels: 20 Refactoring

#3842 [Bug Report] Error when try post the Manufacturing Order
  base/src/org/compiere/process/DocumentEngine.java
  base/src/org/eevolution/model/MPPOrder.java
Labels: 02 bug, 10 Reviewed by Peer, (AC) Accounting

#3826 This pull request just add support to gradle builder to org.eevolution.warehouse source folder
  org.eevolution.warehouse/build.gradle
  org.eevolution.warehouse/src/main/java/base/org/eevolution/process/ReleaseInOutBound.java
Labels: 20 Refactoring

#3838 Validate Class Name for document tables
  base/src/org/adempiere/util/GenerateModel.java
  base/src/org/adempiere/util/GenerateModelJPA.java
  base/src/org/adempiere/util/ModelClassGenerator.java
  base/src/org/adempiere/util/ModelInterfaceGenerator.java
Labels: (CIO) Code Improvement or Optimization, 10 Reviewed by Peer

#3843 Catch query NPE when trying to print Component Check
  base/src/org/compiere/print/ReportEngine.java
Labels: 02 bug, (PF) Report Engine & Print Format

#3837 Allows extend Doc and Doc Line
  base/src/org/compiere/acct/Doc.java
  base/src/org/compiere/acct/DocLine.java
Labels: (PA) Performance Analysis and General Ledger

#3807 fix: Clean warning HashMap should be parameterized
  JasperReports/src/org/compiere/report/JasperViewer.java
  base/src/org/adempiere/pipo/handler/DataElementHandler.java
  base/src/org/compiere/model/MIssue.java
  base/src/org/compiere/model/MLookupCache.java
  client/src/org/compiere/grid/ed/VButton.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADServiceImpl.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/Process.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/CompiereDataSourceFactory.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/ReportViewDataSource.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportInfo.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportPool.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportProcessor.java
  org.adempiere.webservice/WEB-INF/src/net/sf/jasperreports/engine/util/JRQueryExecuter.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMMessenger.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMTreeCellRenderer.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMTreeFactory.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/bom/BOMTreeModel.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/tree/CachableTreeCellRenderer.java
Labels: 10 Reviewed by Peer, 20 Refactoring

#3848 Prevent NPE when openResult is called
  client/src/org/compiere/apps/ProcessController.java
Labels: 02 bug, 01 enhancement, (CIO) Code Improvement or Optimization, 09 Pending Peer Review

#3850 Just change rounding up to decimal 128
  base/src/org/compiere/model/CalloutEngine.java
Labels: 01 enhancement, (CIO) Code Improvement or Optimization, 10 Reviewed by Peer

#3845 Just resolve the problem for print a document
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VPrintDocument.java
  zkwebui/WEB-INF/src/org/eevolution/form/WPrintDocument.java
Labels: 10 Reviewed by Peer, (PF) Report Engine & Print Format

#3847 Add support to default PDF to Process Info
  base/src/org/compiere/process/ProcessInfo.java
Labels: 01 enhancement, 09 Pending Peer Review

#3846 Add a new method to set table selection Process Builder
  base/src/org/eevolution/service/dsl/ProcessBuilder.java
Labels: 01 enhancement, (CIO) Code Improvement or Optimization

#3855 Add support to update sequence on Pay Print/Export option
  base/src/org/compiere/model/MBankAccount.java
  base/src/org/compiere/model/MBankAccountDoc.java
  client/src/org/compiere/apps/form/PayPrint.java
  client/src/org/compiere/apps/form/VPayPrint.java
  zkwebui/WEB-INF/src/org/adempiere/webui/apps/form/WPayPrint.java
Labels: 02 bug, 09 Pending Peer Review, (MNC) Minor Change

#3857 Add support to get document base type with transaction name
  base/src/org/compiere/model/MDocBaseType.java
  base/src/org/compiere/model/MDocType.java
Labels: 01 enhancement, 09 Pending Peer Review, (MNC) Minor Change

#3844 This pull request just add support to gradle builder to manufacturing source folder
  base/src/org/compiere/print/ReportEngine.java
  migration/393lts-394lts/09410_Set_default_report_view_to_manufacturing_reports.xml
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/CompletePrintOrder.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/PrintBOM.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/PrintBOMAbstract.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/SimulatedPickList.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/process/SimulatedPickListAbstract.java
Labels: 20 Refactoring

#3856 Add Support to Cost Engine Dynamic Load
  base/src/org/adempiere/engine/CostingMethodFactory.java
  base/src/org/adempiere/engine/UserDefinedCostingMethodExample.java
  base/src/org/compiere/model/I_M_CostType.java
  base/src/org/compiere/model/X_M_CostType.java
  migration/393lts-394lts/09460_Add_ClassNameForCostType.xml
Labels: (CM) Costing Management

#3868 Add legacy support for Financial Management
  .classpath
  org.spin.finance_management/build.xml
  org.spin.finance_management/src/main/java/base/org/spin/investment/util/FinancialSetting.java
  tools/lib/legacy/financial-support-legacy-1.0.0.jar
Labels: 20 Refactoring

#3830 Close Order does not update Total Lines Amount and total amount
  base/src/org/compiere/model/MOrder.java
  migration/393lts-394lts/09470_3830_Close_Order_Does_Not_Update_Taxes.xml
Labels: 02 bug, (TM) Tax Management

#3871 Add dependences to classpath
  .classpath
Labels: 08 IDE

#3852 Allows define discount based on combinations
  base/src/org/compiere/model/MDiscountSchema.java
  base/src/org/compiere/model/MDiscountSchemaBreak.java
  migration/393lts-394lts/09470_Add_GardenWorld_Discount_Example.xml
  migration/393lts-394lts/09480_Add_default_value_to_Discount_Schema_Break.xml
Labels: 01 enhancement, (SO) Sales Management, 10 Reviewed by Peer

#3872 Revert "Add P_ADEMPIERE_APPS_TYPE support to Ini loader"
  base/src/org/compiere/db/DB_MariaDB.java
  base/src/org/compiere/db/DB_MySQL.java
  base/src/org/compiere/db/DB_Oracle.java
  base/src/org/compiere/db/DB_PostgreSQL.java
  base/src/org/compiere/util/Ini.java
Labels: 02 bug, (SC) System Core

#3839 [Bug Report] Concurrency problems and low performance when obtaining financial reports
  base/src/org/compiere/print/MPrintFormat.java
  base/src/org/compiere/print/MPrintFormatProcess.java
  base/src/org/compiere/report/FinReport.java
  base/src/org/compiere/report/FinReportPeriod.java
Labels: 02 bug, (FIM) Financial Management, 10 Reviewed by Peer, (PF) Report Engine & Print Format, 13 Pending Acceptance

#3877 #3806 [Feature Request] Adding new fields Latitude, Longitude, and Al…
  migration/393lts-394lts/09395_3806_AddingLatitudeLongitudeAltitudeToWindow.xml
Labels: 01 enhancement, 10 Reviewed by Peer, (LOC) Locations

#3883 #3806 [Feature Request] Adding new fields Latitude, Longitude, and A…
  migration/393lts-394lts/09390_3806_AddingNewFieldsLatitudeLongitudeAltitude.xml
Labels: (LOC) Locations

#3888 #3885 [Bug Report] POInfo does not load columns without element tran…
  base/src/org/compiere/model/POInfo.java
Labels: 02 bug, (AD) Application Dictionary, (SC) System Core

#3882 Change XML's version from 1.0 to 3.9.4
  migration/393lts-394lts/09500_Notification_Add_Message_Type.xml
  migration/393lts-394lts/09510_Notification_Add_Message_Type_for_WF.xml
  migration/393lts-394lts/09520_Notification_Add_Response_handler_for_Notification.xml
  migration/393lts-394lts/09530_Notification_Add_Account_ID_for_Updates.xml
  migration/393lts-394lts/09550_Telegram_Add_Implementation_for_Telegram.xml
  migration/393lts-394lts/09560_Telegram_Add_Setup_for_Telegram_Notifier.xml
  migration/393lts-394lts/09570_Telegram_Add_Chat_ID_as_Parameter_for_Registration.xml
Labels: (MT) Migration Tools

#3772 feat: Add frequency type Six-monthly and biweekly.
  base/src/org/compiere/model/MCommissionRun.java
  base/src/org/compiere/model/X_C_Commission.java
  migration/393lts-394lts/09660_Biweekly_and_six-monthly_frequency_type_on_Commission.xml
Labels: 01 enhancement, 10 Reviewed by Peer, (COM) Commission

#3887 fix: #3884 Generate report Null Pointer Exception.
  base/src/org/compiere/print/ReportEngine.java
Labels: (PF) Report Engine & Print Format, 14 Waiting for User Changes

#3891 #3890 [Bug Report] Processor Log with the transaction get not found w…
  base/src/org/compiere/model/MIMPProcessorLog.java
  serverRoot/src/main/server/org/adempiere/server/rpl/imp/TopicListener.java
  serverRoot/src/main/server/org/compiere/ldap/LdapProcessor.java
  serverRoot/src/main/server/org/compiere/server/AcctProcessor.java
  serverRoot/src/main/server/org/compiere/server/AlertProcessor.java
  serverRoot/src/main/server/org/compiere/server/RequestProcessor.java
  serverRoot/src/main/server/org/compiere/server/Scheduler.java
  serverRoot/src/main/server/org/compiere/server/WorkflowProcessor.java
Labels: 02 bug, (SC) System Core

#3817 #3811 [Feature Request] Add support to functionality Adjustment Perio…
  base/src/org/compiere/model/CalloutGLJournal.java
  base/src/org/compiere/model/MJournal.java
  base/src/org/compiere/model/MJournalBatch.java
Labels: 02 bug, 01 enhancement, (FIM) Financial Management, 10 Reviewed by Peer, (PF) Report Engine & Print Format

#3893 #3892 [Feature Request] Add support the BinaryData for ADempiere Web …
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ModelADServiceImpl.java
Labels: 01 enhancement, (WS) Web Service

#3851 Add conversion amount of payment to commission
  base/src/org/compiere/model/MCommissionRun.java
  migration/393lts-394lts/09480_Example_of_Commission_calculation_completelly_paid.xml
Labels: 10 Reviewed by Peer, (COM) Commission

#3881 Rename CRM Package
  base/build.xml
  base/src/org/compiere/model/I_C_Order.java
  base/src/org/compiere/model/X_C_Order.java
  migration/393lts-394lts/09650_Add_CRM_Entity_Type.xml
  migration/393lts-394lts/09660_Change_Entity_Type_for_CRM.xml
  org.adempiere.crm/build.gradle
  org.adempiere.crm/src/main/java/org/compiere/crm/model/I_C_ContactActivity.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/I_C_Opportunity.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/I_C_SalesStage.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/MLead.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/MOpportunity.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/MSalesStage.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/X_C_ContactActivity.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/X_C_Opportunity.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/X_C_SalesStage.java
  org.adempiere.crm/src/main/java/org/compiere/crm/model/validator/CustomerRelationshipManagement.java
  org.adempiere.crm/src/main/java/org/compiere/crm/process/ConvertLead.java
  org.adempiere.crm/src/main/java/org/compiere/crm/process/ConvertLeadAbstract.java
  org.adempiere.crm/src/main/java/org/compiere/model/SalesMgmtValidator.java
  org.adempiere.crm/src/main/java/org/eevolution/crm/process/CreateProjectFromOpportunity.java
  org.adempiere.crm/src/main/java/org/eevolution/crm/process/CreateProjectFromOpportunityAbstract.java
  tools/lib/legacy/crm-support-legacy-1.0.2.jar
Labels: 10 Reviewed by Peer, 13 Pending Acceptance, 20 Refactoring

#3853 This pull request just add support to gradle builder to org.eevolution.hr_and_payroll source folder
  base/src/org/compiere/minigrid/ColumnInfo.java
  base/src/org/compiere/minigrid/DeleteColumn.java
  base/src/org/compiere/minigrid/EmbedWinInfo.java
  base/src/org/compiere/minigrid/IDColumn.java
  base/src/org/compiere/minigrid/IMiniTable.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/HRGenerateInvoiceFromProcess.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/PayrollViaEMail.java
Labels: 09 Pending Peer Review, 20 Refactoring

#3898 Fixed [Bug Report] The Scheduler throw AdempiereException: Notification Recipient Mandatory
  base/src/org/spin/queue/notification/DefaultNotifier.java
Labels: 02 bug, (NQS) Notification Queue Suport

#3897 Fixed Class not found java.lang.NoClassDefFoundError when use adempiereMonitor #3896
  tools/src/org/adempiere/legacy/apache/ecs/ECSDefaults.java
Labels: 02 bug
