Repository adempiere/adempiere, pull requests merged in 2022-09, with the labels that each got.

#3960 #3959 [Bug Report] Tomcat does not exist in the Read Connection Pool …
  install/Adempiere/build.xml
  lib/context.xml
Labels: 02 bug, (SC) System Core, 10 Reviewed by Peer, 17 Waiting for Information

#3981 #3980 [Bug Report] Connection parameters setKeepaliveTime not is vali…
  base/src/org/compiere/db/DB_MariaDB.java
  base/src/org/compiere/db/DB_MySQL.java
  base/src/org/compiere/db/DB_Oracle.java
  base/src/org/compiere/db/DB_PostgreSQL.java
Labels: 02 bug, (SC) System Core, 10 Reviewed by Peer

#3979 #3978 [Bug Report] RUN_Server2Stop.sh not shutdown the Jetty Server h…
  utils/RUN_Server2.sh
Labels: 02 bug, 10 Reviewed by Peer

#3982 #3975 [Feature Request] Add new substitute values for financial repo…
  base/src/org/compiere/report/FinReport.java
Labels: 01 enhancement, (PA) Performance Analysis and General Ledger, 10 Reviewed by Peer, (PF) Report Engine & Print Format

#3984 #3983 [Bug Report] Is reconciled flag is not correctly set when a payment is in an account statement with draft document status
  base/src/org/compiere/model/MPayment.java
Labels: 02 bug, (AR) Account Receivable, (AP) Account Payable, 10 Reviewed by Peer, 14 Waiting for User Changes

#3986 #3985 [Feature Request] Adding URL Map to a location map to Business …
  base/src/org/adempiere/core/domains/models/I_C_BPartner_Location.java
  base/src/org/adempiere/core/domains/models/X_C_BPartner_Location.java
  base/src/org/compiere/model/MBPartnerLocation.java
  base/src/org/compiere/model/MLocation.java
  migration/393lts-394lts/09850_3985_Adding_URL_Map_To_A_Location_ Map.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WLocationEditor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WLocationDialog.java
Labels: 01 enhancement, 10 Reviewed by Peer

#3988 #3987 [Feature Request] Synchronize Entity Type https://github.com/ad…
  base/src/org/adempiere/core/domains/models/X_C_PaymentMethod.java
  base/src/org/adempiere/core/domains/models/X_C_PaymentMethodAllocation.java
  base/src/org/adempiere/core/domains/models/X_HR_ProcessReport.java
  base/src/org/adempiere/core/domains/models/X_HR_ProcessReportLine.java
  base/src/org/adempiere/core/domains/models/X_HR_ProcessReportPayroll.java
  base/src/org/adempiere/core/domains/models/X_HR_ProcessReportSource.java
  base/src/org/adempiere/core/domains/models/X_HR_ProcessReportTemplate.java
  base/src/org/adempiere/core/domains/models/X_RV_HR_ProcessDetail.java
  base/src/org/adempiere/core/domains/models/X_WM_Area.java
  base/src/org/adempiere/core/domains/models/X_WM_Area_Type.java
  base/src/org/adempiere/core/domains/models/X_WM_Definition.java
  base/src/org/adempiere/core/domains/models/X_WM_InOutBound.java
  base/src/org/adempiere/core/domains/models/X_WM_InOutBoundLine.java
  base/src/org/adempiere/core/domains/models/X_WM_InOutBoundLineMA.java
  base/src/org/adempiere/core/domains/models/X_WM_Rule.java
  base/src/org/adempiere/core/domains/models/X_WM_Section.java
  base/src/org/adempiere/core/domains/models/X_WM_Section_Detail.java
  base/src/org/adempiere/core/domains/models/X_WM_Section_Type.java
  base/src/org/adempiere/core/domains/models/X_WM_Strategy.java
  base/src/org/adempiere/core/domains/models/X_WM_Strategy_Detail.java
  base/src/org/adempiere/core/domains/models/X_W_Category.java
  base/src/org/adempiere/core/domains/models/X_W_CategoryAllocation.java
  base/src/org/adempiere/core/domains/models/X_W_DeliveryViaRuleAllocation.java
  base/src/org/adempiere/process/SynchronizeEntityType.java
  base/src/org/adempiere/process/SynchronizeEntityTypeAbstract.java
  migration/393lts-394lts/09870_Rename_Manufacturing_Package.xml
  migration/393lts-394lts/09880_3987_SynchronizeEntityType.xml
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/hr/util/AbstractPayrollReportExport.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/pr/model/MHRProcessReport.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/pr/model/MHRProcessReportLine.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/pr/model/MHRProcessReportPayroll.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/pr/model/MHRProcessReportSource.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/pr/model/MHRProcessReportTemplate.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/spin/pr/process/PayrollProcessReport.java
  org.eevolution.hr_and_payroll/src/main/java/ui/zk/org/spin/pr/process/WPayrollProcessReport.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMArea.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMAreaType.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMDefinition.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMInOutBound.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMInOutBoundLine.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMInOutBoundLineMA.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMRule.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMSection.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMSectionDetail.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMSectionType.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMStrategy.java
  org.eevolution.warehouse/src/main/java/base/org/eevolution/wms/model/MWMStrategyDetail.java
  org.spin.store/src/main/java/org/spin/store/model/MCPaymentMethod.java
  org.spin.store/src/main/java/org/spin/store/model/MWCategory.java
  org.spin.store/src/main/java/org/spin/store/model/MWCategoryAllocation.java
  org.spin.store/src/main/java/org/spin/store/model/MWDeliveryViaRuleAllocation.java
  org.spin.store/src/main/java/org/spin/store/model/MWPaymentMethodAllocation.java
Labels: 01 enhancement, (AD) Application Dictionary, 10 Reviewed by Peer, 14 Waiting for User Changes, 17 Waiting for Information

#3972 Restore Database Only When XML Files Involved (take # 2)
  .github/actions/adempiere-build/action.yml
  .github/workflows/main.yml
  build.xml
Labels: 09 Pending Peer Review, 12 Feature, (CI/CD) Continuous Integration/Continous Delivery
