Repository adempiere/adempiere, pull requests merged in 2022-12, with the labels that each got.

#4024 Fixed multiples errors for ZK User Interface Improvement
  base/src/org/compiere/model/GridTab.java
  tools/build.xml
  tools/lib/byte-buddy-1.12.19.jar
  zkwebui/WEB-INF/src/org/adempiere/webui/ServerContextCallback.java
  zkwebui/WEB-INF/src/org/adempiere/webui/ZkContextProvider.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/GridTabRowRenderer.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/WListItemRenderer.java
Labels: 02 bug, (UI) User Interface Improvement, 10 Reviewed by Peer

#4027 Fixed error with backup for asset
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: (CI/CD) Continuous Integration/Continous Delivery

#4028 Update ubuntu version for postgresql 15 version support
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: (CI/CD) Continuous Integration/Continous Delivery

#4026 Remove JDK8 compatibility gradle
  JasperReports/build.gradle
  JasperReports/build.xml
  JasperReports/src/org/compiere/jr/report/ReportStarter.java
  base/build.gradle
  build.gradle
  client/build.xml
  client/src/org/compiere/jr/report/JasperReportViewer.java
  client/src/org/compiere/jr/report/JasperViewer.java
  client/src/org/compiere/jr/report/SwingJRViewerProvider.java
  extend/build.gradle
  install/build.gradle
  migration/build.gradle
  org.adempiere.asset/build.gradle
  org.adempiere.crm/build.gradle
  org.adempiere.pos/build.gradle
  org.adempiere.production/build.gradle
  org.adempiere.project/build.gradle
  org.adempiere.request/build.gradle
  org.adempiere.test/build.gradle
  org.eevolution.cashflow/build.gradle
  org.eevolution.distribution/build.gradle
  org.eevolution.freight/build.gradle
  org.eevolution.hr_and_payroll/build.gradle
  org.eevolution.manufacturing/build.gradle
  org.eevolution.warehouse/build.gradle
  org.spin.authentication/build.gradle
  org.spin.finance_management/build.gradle
  org.spin.hr_time_and_attendance/build.gradle
  org.spin.loan_management/build.gradle
  org.spin.notifier.discord/build.gradle
  org.spin.notifier.telegram/build.gradle
  org.spin.store/build.gradle
  serverRoot/build.gradle
  settings.gradle
  tools/build.gradle
  utils_dev/build.xml
Labels: 01 enhancement, 10 Reviewed by Peer, (CI/CD) Continuous Integration/Continous Delivery, 17 Waiting for Information
