Repository adempiere/adempiere, pull requests merged in 2022-07, with the labels that each got.

#3909 Feature/#3776 send email notification with org email
  base/src/org/compiere/model/I_AD_OrgInfo.java
  base/src/org/compiere/model/MClient.java
  base/src/org/compiere/model/MRequest.java
  base/src/org/compiere/model/MRfQResponse.java
  base/src/org/compiere/model/X_AD_OrgInfo.java
  base/src/org/compiere/process/DunningPrint.java
  base/src/org/compiere/process/EMailTest.java
  base/src/org/compiere/process/InvoicePrint.java
  base/src/org/compiere/process/OrgEMailTest.java
  base/src/org/compiere/process/OrgEMailTestAbstract.java
  base/src/org/compiere/util/EMail.java
  base/src/org/compiere/wf/MWFActivity.java
  base/src/org/spin/process/PaySelectionSendRemittance.java
  base/src/org/spin/queue/notification/support/EMailSender.java
  base/src/org/spin/queue/util/QueueManager.java
  migration/393lts-394lts/09770_3776_Add_config_email_in_org.xml
  org.adempiere.asset/src/main/java/base/org/compiere/process/AssetDelivery.java
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/process/SendPayrollReceiptByEmail.java
  org.spin.notifier.discord/src/main/java/base/org/spin/queue/notification/discord/support/Discord.java
  org.spin.notifier.telegram/src/main/java/base/org/spin/queue/notification/telegram/support/Telegram.java
  serverRoot/src/main/server/org/compiere/server/ProjectProcessor.java
  serverRoot/src/main/server/org/compiere/server/Scheduler.java
  serverRoot/src/main/server/org/compiere/server/WorkflowProcessor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/process/InvoicePrint.java
Labels: 01 enhancement, (SC) System Core

#3958 #3957 [Bug Report] Update build ant files with last library javax.ser…
  base/build.xml
  org.compiere.mobile/build.xml
  serverRoot/build.xml
  tools/build.xml
  zkwebui/build.xml
Labels: 02 bug, (SC) System Core

#3937 Correction of Favorites(User) Drag&Drop
  zkwebui/WEB-INF/src/org/adempiere/webui/dashboard/DPFavourites.java
Labels: 02 bug, (UI) User Interface Improvement, 09 Pending Peer Review
