Repository adempiere/adempiere, pull requests merged in 2022-03, with the labels that each got.

#3762 Fixed #3760
  base/src/org/adempiere/process/MigrationLoader.java
Labels: 02 bug, (MT) Migration Tools

#3761 Scheduler By Email based on new notification queue
  serverRoot/src/main/server/org/compiere/server/Scheduler.java
Labels: 20 Refactoring, (NQS) Notification Queue Suport

#3763 Fixed error with classpath for vavr
  .classpath
Labels: 08 IDE

#3764 Change PaymentFormController from ResultSet to new way for get data
  base/src/org/adempiere/controller/PaymentFormController.java
  base/test/src/org/compiere/util/IT_PaymentFormController.java
Labels: 01 enhancement, 20 Refactoring

#3752 Increase the maximum connection pool parameter in swing mode so that simultaneous processing is possible
  base/src/org/compiere/db/DB_MariaDB.java
  base/src/org/compiere/db/DB_MySQL.java
  base/src/org/compiere/db/DB_Oracle.java
  base/src/org/compiere/db/DB_PostgreSQL.java
Labels: 01 enhancement, (SC) System Core, 10 Reviewed by Peer, 14 Waiting for User Changes

#3728 fix: Build Warning Could not find file.
  sqlj/build.xml
Labels: 10 Reviewed by Peer, (INS) Installation, 14 Waiting for User Changes, 23 reproduced

#3754 Adding Support the Read Connection Using Tomcat, Wildfly , Jetty
  install/Adempiere/build.xml
  lib/jetty-ds.xml
  lib/mariadb-ds.xml
  lib/mysql-ds.xml
  lib/oracle-ds.xml
  lib/postgresql-ds.xml
Labels: 01 enhancement, (SC) System Core, 10 Reviewed by Peer

#3698 Update C_REGION.xml
  db/ddlutils/data/C_REGION.xml
Labels: 10 Reviewed by Peer, (MNC) Minor Change

#3755 Add tax functionality to the requisition
  base/src/org/compiere/acct/Doc_Requisition.java
  base/src/org/compiere/model/I_M_Requisition.java
  base/src/org/compiere/model/I_M_RequisitionLine.java
  base/src/org/compiere/model/I_M_RequisitionTax.java
  base/src/org/compiere/model/MRequisition.java
  base/src/org/compiere/model/MRequisitionLine.java
  base/src/org/compiere/model/MRequisitionTax.java
  base/src/org/compiere/model/X_M_Requisition.java
  base/src/org/compiere/model/X_M_RequisitionLine.java
  base/src/org/compiere/model/X_M_RequisitionTax.java
  migration/393lts-394lts/09370_3737_Add_Tax_functionality_To_The_Requisition.xml
Labels: 01 enhancement, (PO) Purchase Management, 10 Reviewed by Peer

#3773 #3768 [Feature Request] Adding the files in ZK to WebUI non fail http…
  zkwebui/theme/default/css/thememoz.css.dsp
  zkwebui/theme/default/login-buttom.zul
  zkwebui/theme/default/login-right.zul
  zkwebui/theme/default/login-top.zul
Labels: 01 enhancement

#3743 #3742 [Feature Request] Add support the Import Order in Parallel and …
  base/src/org/compiere/process/ImportOrder.java
  project/build.properties
  project/project/build.properties
Labels: 01 enhancement, (PO) Purchase Management, (SO) Sales Management, 10 Reviewed by Peer

#3766 #3765 [Feature Request] MDocumentStatus Implementing new approach to …
  base/src/org/adempiere/model/MDocumentStatus.java
  base/test/src/org/compiere/model/IT_MDocumentStatus.java
Labels: 01 enhancement, 10 Reviewed by Peer, 20 Refactoring

#3555 Refactory: Workflow Activity based on new notification queue
  base/src/org/compiere/wf/MWFActivity.java
Labels: 02 bug, (CIO) Code Improvement or Optimization, (NQS) Notification Queue Suport

#3770 #3769 [Bug Report] The Distribution Line flag isInvertAccountSign not…
  base/src/org/compiere/acct/Fact.java
Labels: 02 bug, (AC) Accounting

#3778 adempiere #3777 FR: Copy C_Tax_ID for valid distribution Lines
  base/src/org/compiere/acct/Fact.java
Labels: 12 Feature
