Repository adempiere/adempiere, pull requests merged in 2022-02, with the labels that each got.

#3714 Fixed error with ConcurrentModificationException
  base/src/org/compiere/model/MTable.java
Labels: 02 bug, 10 Reviewed by Peer

#3693 #3692 [Bug Report] Remove JVM parameter no compatible with JDK 17 htt…
  install/Adempiere/AdempiereEnvTemplate.properties
Labels: 02 bug, (SC) System Core, 10 Reviewed by Peer

#3700 #3699 [Bug Report] Fixed problem with Log4j https://github.com/adempi…
  .classpath
  adempiere.iml
  org.adempiere.webservice/WEB-INF/lib/log4j-1.2.12.jar
  tools/build.xml
  tools/lib/log4j-1.2-api-2.17.1.jar
  tools/lib/log4j-api-2.17.1.jar
  tools/lib/log4j-core-2.17.1.jar
  tools/lib/log4j.jar
  tools/lib/storefront/log4j-api-2.11.1.jar
Labels: 02 bug, (SE) Security, 10 Reviewed by Peer

#3705 [Bug Report] Possible leak resource into the process Import Order
  base/src/org/compiere/process/ImportOrder.java
Labels: 02 bug, (PO) Purchase Management, (SO) Sales Management, 10 Reviewed by Peer, 14 Waiting for User Changes

#3708 #3707 [Bug Report] Improper transaction closing in Doc class https://…
  base/src/org/compiere/acct/Doc.java
Labels: 02 bug

#3713 #3712 [Bug Report] Incorrect handling of DB transactions in the order
  base/src/org/compiere/process/ImportOrder.java
Labels: 02 bug, (PO) Purchase Management, (SO) Sales Management

#3720 #3719 [Bug Report] Leak transaction caused by incorrect transaction MRole and MClientInfo
  base/src/org/adempiere/process/ASPGenerateLevel.java
  base/src/org/adempiere/process/CreateCustomizationFromASP.java
  base/src/org/compiere/model/MAcctSchema.java
  base/src/org/compiere/model/MClient.java
  base/src/org/compiere/model/MClientInfo.java
  base/src/org/compiere/model/MPeriod.java
  base/src/org/compiere/model/MRole.java
Labels: 02 bug, (SC) System Core

#3726 Fixed compilation errors
  .classpath
  .settings/org.eclipse.jdt.core.prefs
Labels: 02 bug, 10 Reviewed by Peer, 14 Waiting for User Changes

#3729 fix: Build warning 'includeantruntime' was not set.
  JasperReports/build.xml
  JasperReportsWebApp/build.xml
  client/build.xml
  com.kkalice.adempiere.migrate/build.xml
  extend/build.xml
  install/build.xml
  org.adempiere.asset/build.xml
  org.adempiere.production/build.xml
  org.adempiere.webservice/build.xml
  org.compiere.mobile/build.xml
  org.eevolution.cashflow/build.xml
  org.eevolution.fleet/build.xml
  org.eevolution.freight/build.xml
  org.eevolution.hr_and_payroll/build.xml
  org.eevolution.manufacturing/build.xml
  org.eevolution.warehouse/build.xml
  org.spin.finance_management/build.xml
  org.spin.hr_time_and_attendance/build.xml
  org.spin.loan_management/build.xml
  org.spin.store/build.xml
  serverApps/build.xml
  serverRoot/build.xml
  sqlj/build.xml
  tools/build.xml
  webCM/build.xml
  zkwebui/build.xml
Labels: 10 Reviewed by Peer, (CI/CD) Continuous Integration/Continous Delivery

#3741 Add ResultSetIterable for get the result rows the Iterable way
  base/src/org/compiere/util/DB.java
  base/src/org/compiere/util/ResultSetIterable.java
  base/test/src/org/compiere/util/IT_DB.java
Labels: 01 enhancement, (SC) System Core

#3571 Refactory: Request Processor By Email based on new notification queue
  serverRoot/src/main/server/org/compiere/server/RequestProcessor.java
Labels: (CIO) Code Improvement or Optimization, (NQS) Notification Queue Suport

#3554 Refactory: EMail Dialog based on new notification queue
  client/src/org/compiere/apps/EMailDialog.java
  migration/393lts-394lts/09230_Add_refactory_for_WEMailDialog.xml
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WEMailDialog.java
Labels: (CIO) Code Improvement or Optimization, 14 Waiting for User Changes, (NQS) Notification Queue Suport

#3562 Refactory: Web Enviroment based on new notification queue
  base/src/org/compiere/util/WebEnv.java
  migration/393lts-394lts/09250_Add_message_for_server_start.xml
Labels: (CIO) Code Improvement or Optimization, 17 Waiting for Information, (NQS) Notification Queue Suport, ZZ Motionless

#3565 Refactory: Payment Servlet By Email based on new notification queue
  serverApps/src/main/servlet/org/compiere/wstore/PaymentServlet.java
Labels: (CIO) Code Improvement or Optimization, 09 Pending Peer Review, (NQS) Notification Queue Suport, ZZ Motionless

#3569 Refactory: Workflow Processor By Email based on new notification queue
  serverRoot/src/main/server/org/compiere/server/WorkflowProcessor.java
Labels: (NQS) Notification Queue Suport, ZZ Motionless

#3574 Deprecate old methods for send EMail from MClient class
  base/src/org/compiere/model/MClient.java
Labels: (CIO) Code Improvement or Optimization, (NQS) Notification Queue Suport

#3646 Add support to Is Include Not Available flag for generate invoice
  migration/393lts-394lts/09300_Add_IsIncludeNotAvailable_parameter_for_generate_Invoice.xml
  org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBound.java
  org.eevolution.warehouse/src/main/java/base/org/spin/process/GenerateInvoiceInOutBoundAbstract.java
Labels: 01 enhancement, (WMS) Warehouse Management System

#3746 Login Remove the Result Set and Adding Integration Test
  base/src/org/compiere/util/CLogger.java
  base/src/org/compiere/util/Login.java
  base/test/src/org/compiere/util/IT_Login.java
Labels: 01 enhancement, (SC) System Core, 10 Reviewed by Peer, 20 Refactoring

#3747 Add cache to MRefList #3745
  base/src/org/compiere/model/MRefList.java
Labels: 01 enhancement, (SC) System Core, 09 Pending Peer Review
