Repository adempiere/adempiere, pull requests merged in 2022-10, with the labels that each got.

#3992 #3991/bug/jasper starter class
  base/src/org/adempiere/util/ProcessUtil.java
Labels: 02 bug, (PF) Report Engine & Print Format

#3996 Revert "Fixed error with dependences when a column is changed"
  db/ddlutils/postgresql/functions/altercolumn.sql
  db/ddlutils/postgresql/functions/get_all_views.sql
  migration/393lts-394lts/06420_Fixed_Error_with_Dependences_Alter_Column.xml
Labels: 02 bug, (AD) Application Dictionary

#3993 Adding URL Map to a location map to Business Partner Location
  base/src/org/compiere/model/MBPartnerLocation.java
  zkwebui/WEB-INF/src/org/adempiere/webui/editor/WLocationEditor.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WLocationDialog.java
Labels: 01 enhancement, 10 Reviewed by Peer, (BP) Business Partner

#3999 #3998 [Bug Report] NPE when trying close a Manufacturing Order with a…
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/manufacturing/model/MPPOrderWorkflow.java
Labels: 02 bug, (PMM) Planning and Manufacturing Management, (MRP) Manufacturing Resource Planning

#3995 #3994 [Bug Report] Lookup for the lot shows deactivated records and o…
  base/src/org/compiere/model/MLot.java
  client/src/org/compiere/apps/search/InfoPAttribute.java
  client/src/org/compiere/grid/ed/VPAttributeDialog.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoPAttributePanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WPAttributeDialog.java
Labels: 02 bug, (MM) Material Management, 10 Reviewed by Peer

#4001 #3990 Rules do not work in Adempiere 394 https://github.com/adempier…
  install/Adempiere/build.xml
  tools/build.xml
Labels: 02 bug, (SC) System Core, 09 Pending Peer Review

#3997 #3989 [Bug Report] Error when re-creating a view by altering a table
  db/ddlutils/postgresql/functions/altercolumn.sql
  db/ddlutils/postgresql/functions/viewsDependencies.sql
  migration/393lts-394lts/06415_Resize_MigrationStep_SQL_Statement.xml
  migration/393lts-394lts/06420_Fixed_Error_with_Dependences_Alter_Column.xml
Labels: 02 bug, (AD) Application Dictionary
