Repository adempiere/adempiere, pull requests merged in 2022-08, with the labels that each got.

#3961 Fix #3956
  base/src/org/spin/queue/util/QueueManager.java
Labels: 09 Pending Peer Review, 13 Pending Acceptance

#3951 Rename Production Package (Replace #3944)
  migration/393lts-394lts/09810_Add_Production_Entity_Type.xml
  migration/393lts-394lts/09820_Rename_package_name_of_Production.xml
  org.adempiere.production/build.gradle
  org.adempiere.production/build.xml
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/CalculateReplenishPlan.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/CalculateReplenishPlanAbstract.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/GenerateReplenishPlanProductionReport.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/GenerateReplenishPlanProductionReportAbstract.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/GenerateReplenishPlanReport.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/GenerateReplenishPlanReportAbstract.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/GenerateReplenishPlanRequisitionReport.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/GenerateReplenishPlanRequisitionReportAbstract.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/ReplenishPlanInitialSetup.java
  org.adempiere.production/src/main/java/base/org/adempiere/production/process/ReplenishPlanInitialSetupAbstract.java
  org.adempiere.production/src/main/java/base/org/compiere/production/model/I_M_ReplenishPlan.java
  org.adempiere.production/src/main/java/base/org/compiere/production/model/I_M_ReplenishPlanLine.java
  org.adempiere.production/src/main/java/base/org/compiere/production/model/MReplenishPlan.java
  org.adempiere.production/src/main/java/base/org/compiere/production/model/X_M_ReplenishPlan.java
  org.adempiere.production/src/main/java/base/org/compiere/production/model/X_M_ReplenishPlanLine.java
  org.adempiere.production/src/main/java/base/org/compiere/production/process/OrderLineCreateProduction.java
  org.adempiere.production/src/main/java/base/org/compiere/production/process/ReplenishReportProduction.java
  tools/lib/legacy/production-support-legacy-1.0.0.jar
Labels: (PLH) Production Light, 10 Reviewed by Peer, 20 Refactoring

#3912 Organization Tax Exempt
  base/src/org/compiere/model/Tax.java
  migration/393lts-394lts/09740_3894_Organization_Tax_Exempt.xml
Labels: 01 enhancement, (TM) Tax Management, 09 Pending Peer Review

#3935 Skip executing RUN_DBRestore to avoid importing seed twice
  build.xml
Labels: 02 bug, 09 Pending Peer Review, (CI/CD) Continuous Integration/Continous Delivery

#3936 Solve "BUILD FAILED" Error running Github Action "ADempiere Build"
  .github/workflows/main.yml
Labels: 02 bug, 09 Pending Peer Review, (CI/CD) Continuous Integration/Continous Delivery

#3928 New Notification Window per user
  migration/393lts-394lts/09850_3927_New_Notification_Window_per_user.xml
  migration/393lts-394lts/09860_3927_New_Notification_Window_per_user.xml
Labels: 01 enhancement, (UI) User Interface Improvement, 09 Pending Peer Review

#3969 Fix #3968 - POInfo cached sql sintax error
  base/src/org/compiere/model/POInfo.java
Labels: 02 bug, 10 Reviewed by Peer, 13 Pending Acceptance, 17 Waiting for Information, 23 reproduced
