Repository adempiere/adempiere, pull requests merged in 2023-11, with the labels that each got.

#4075 RFQ Create PO Fixed error with unused parameter
  base/src/org/compiere/process/RfQCreatePO.java
  base/src/org/compiere/process/RfQCreatePOAbstract.java
Labels: 02 bug, (MM) Material Management, 13 Pending Acceptance, 02 bugfix -> 3.9.4.001, 25 Waiting for Weekly Meeting

#4079 Fixed error with validate payment amount
  base/src/org/compiere/model/MPaySelection.java
Labels: 02 bug, (FIM) Financial Management, 02 bugfix -> 3.9.4.001, 25 Waiting for Weekly Meeting

#4088 [Bug Report] Error the compiled project after the generate model for all tables.
  base/src/org/adempiere/util/GenerateModel.java
  base/src/org/adempiere/util/ModelClassGenerator.java
  base/src/org/adempiere/util/ModelInterfaceGenerator.java
Labels: 02 bug, (SC) System Core, 02 bugfix -> 3.9.4.001

#4109 Cash payment does not remove check from "Assigned" when unassigned
  base/src/org/compiere/model/MAllocationLine.java
Labels: 02 bug, (AP) Account Payable, 09 Pending Peer Review, 17 Waiting for Information

#4178 Fixed error with laucher for ADempiere Swing UI
  .idea/workspace.xml
  base/ADempiere-all.launch
  base/ADempiere.launch
  client/build.xml
  extend/CostingEngine/adempiereLiberoCE.launch
  extend/SmartBrowser/adempiereLiberoSB.launch
  install/ADempiere-Setup.launch
  install/Adempiere/build.xml
  launch/Adempiere.xml
  org.adempiere.pos/.idea/workspace.xml
  org.adempiere.pos/ADempierePOS.launch
  org.adempiere.production/build.xml
  org.adempiere.test/src/test/scala/org/eevolution/test/AdempiereStartup.scala
  org.adempiere.webservice/deploy/build.xml
  org.eevolution.cashflow/build.xml
  org.eevolution.hr_and_payroll/adempiereLiberoHR.launch
  org.eevolution.manufacturing/adempiereLiberoMFG.launch
  org.eevolution.warehouse/adempiereLiberoWM.launch
  serverRoot/src/web/adempiere.jnlp
  tools/launchers/Adempiere Setup GUI.launch
  tools/launchers/Adempiere.launch
  tools/launchers/GenerateModel-general.launch
  tools/launchers/Load XML Migrations.launch
  tools/launchers/ModelClassGenerator.launch
  tools/launchers/ModelInterfaceGenerator.launch
  tools/launchers/adempiere-GenerateModel-prompt.launch
  utils/adempiereDirectTemplate.jnlp
Labels: (MNC) Minor Change, 25 Waiting for Weekly Meeting

#4085 Fixed error with missing property file for apache ecs packages
  tools/build.gradle
Labels: 02 bug, 09 Pending Peer Review, (INS) Installation, 17 Waiting for Information, (MNC) Minor Change, 02 bugfix -> 3.9.4.001, 25 Waiting for Weekly Meeting

#4180 #4179 [Feature Request] Adding C_BPartner_Location_ID to Requisition …
  base/src/org/adempiere/core/domains/models/I_M_RequisitionLine.java
  base/src/org/adempiere/core/domains/models/X_M_RequisitionLine.java
  base/src/org/compiere/model/CalloutRequisition.java
  base/src/org/compiere/model/MRequisitionLine.java
  migration/394lts-395lts/09930_4179_AddingBusinessPartnerLocationRequisitionLine.xml
Labels: 01 enhancement, (PO) Purchase Management

#4159 fix: Remove deprecated warning with `BigDecimal.ROUND`.
  base/src/org/compiere/model/CalloutGLJournal.java
Labels: (MNC) Minor Change

#4182 Fixed error with wrong sequence for Purchase Order
  base/src/org/compiere/process/RequisitionPOCreate.java
  base/src/org/compiere/process/RequisitionPOCreateAbstract.java
  base/src/org/eevolution/process/CreatePOFromRequisitionLines.java
  migration/394lts-395lts/10320_Add_Document_Type_for_Requisition_PO_Create.xml
Labels: 02 bug, (PO) Purchase Management

#4175 fix: #4174 NPE with preview Jasper Report on `Swing` UI.
  JasperReports/src/org/compiere/jr/report/ReportStarter.java
  base/src/org/adempiere/util/ProcessUtil.java
  base/src/org/compiere/print/ReportViewerProvider.java
  client/src/org/adempiere/Adempiere.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportProcessor.java
Labels: 25 Waiting for Weekly Meeting

#4074 Add Import Requisition functionality
  base/src/org/adempiere/core/domains/models/I_I_Requisition.java
  base/src/org/adempiere/core/domains/models/X_I_Requisition.java
  base/src/org/compiere/process/ImportRequisition.java
  base/src/org/compiere/process/ImportRequisitionAbstract.java
  data/import/Example_Requisition_Format.xlsx
  data/import/Example_Requisitions.tsv
  data/import/Example_Requisitions_And_Products.tsv
  migration/394lts-395lts/09970_Add_Import_Requisition.xml
  migration/394lts-395lts/09980_Import_Requisitions_Add_Import_Formats.xml
Labels: (MM) Material Management, 12 Feature, 25 Waiting for Weekly Meeting

#4137 Fixed error with package names for payroll
  migration/394lts-395lts/09910_Rename_payroll_packages.xml
Labels: 02 bug, (AD) Application Dictionary, (MNC) Minor Change, 25 Waiting for Weekly Meeting

#4170 #4168 [Bug Report] the process Import GL Journal not work, fail try i…
  base/src/org/compiere/process/ImportGLJournal.java
Labels: 02 bug, (PA) Performance Analysis and General Ledger, (AC) Accounting, 02 bugfix -> 3.9.4.001, 25 Waiting for Weekly Meeting

#4154 fix: Remove deprecated warning with `new Double` constructor.
  base/src/org/compiere/model/MQuery.java
  client/src/org/compiere/apps/search/Info.java
  client/src/org/compiere/apps/search/InvoiceHistory.java
  client/src/org/compiere/minigrid/MiniTable.java
  client/src/org/compiere/report/core/RModelData.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSTable.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/manufacturing/engine/forecast/MovingAverage.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VMRPDetailed.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VOrderPlanning.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/WListbox.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoPanel.java
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/InvoiceHistory.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.3.001

#4155 fix: Remove deprecated warning with `new Integer` constructor.
  org.compiere.mobile/WEB-INF/src/org/compiere/mobile/MobileSessionCtx.java
  org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WReport.java
  org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WWindow.java
  org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WWorkflow.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4157 fix: Remove deprecated warning with `new Float` constructor.
  base/src/org/compiere/print/layout/TableElement.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4158 fix: Remove deprecated warning with `new Character` constructor.
  client/src/org/compiere/apps/AppsAction.java
  zkwebui/WEB-INF/src/org/adempiere/webui/component/WAppsAction.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4156 fix: Remove deprecated warning with `new Long` constructor.
  base/src/org/spin/model/MADContextInfo.java
  org.adempiere.pos/src/main/java/ui/zk/org/adempiere/pos/WPOSActionPanel.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/data/DBDataSource.java
  org.eevolution.manufacturing/src/main/java/base/org/eevolution/manufacturing/process/CRPSummary.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/CRP.java
  serverRoot/src/main/servlet/org/compiere/web/AdempiereMonitorFilter.java
  webCM/src/main/servlet/org/compiere/cm/cache/CO.java
  zkwebui/WEB-INF/src/org/adempiere/webui/window/WMediaDialog.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4128 fix: #4000 Deletion of records from another `Client`.
  base/src/org/compiere/model/PO.java
  migration/394lts-395lts/09940_Fixed_Deletion_of_records_form_another_client.xml
Labels: (SC) System Core, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.001

#4129 fix: Currency Rate change `C_Currency_ID_To` value.
  base/src/org/compiere/model/GridField.java
  base/src/org/compiere/model/GridTable.java
  base/src/org/compiere/util/DisplayType.java
Labels: 02 bug, (SC) System Core, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.001, 25 Waiting for Weekly Meeting

#4161 fix: Remove warning `The constructor Viewer(ReportEngine) is deprecated`.
  client/src/org/compiere/print/SwingViewerProvider.java
  client/src/org/compiere/print/Viewer.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VOrderDistributionReceipt.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VPrintDocument.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4160 fix: Remove warning `The constructor AWindow() is deprecated`.
  client/src/de/schaeffer/compiere/tools/DocumentSearch.java
  client/src/org/compiere/apps/AEnv.java
  client/src/org/compiere/apps/AWindow.java
  client/src/org/compiere/apps/AZoomAcross.java
  client/src/org/compiere/apps/form/VTrxMaterial.java
  client/src/org/compiere/apps/search/Info.java
  client/src/org/compiere/apps/wf/WFActivity.java
  client/src/org/compiere/apps/wf/WFPanel.java
  client/src/org/compiere/grid/ed/VLocator.java
  client/src/org/compiere/grid/ed/VPAttributeDialog.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/VMRPDetailed.java
  org.eevolution.manufacturing/src/main/java/ui/swing/org/eevolution/form/action/ZoomMenuAction.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4164 fix: Remove deprecated warning with `DB.prepareStatement` method.
  base/src/org/compiere/util/DB.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/ADLookup.java
  org.adempiere.webservice/WEB-INF/src/com/_3e/ADInterface/Process.java
  org.adempiere.webservice/WEB-INF/src/net/sf/compilo/report/ReportInfo.java
  org.compiere.mobile/WEB-INF/src/org/compiere/mobile/WWorkflow.java
  serverApps/src/main/servlet/org/compiere/www/WWorkflow.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4189 Bugfix #4114
  base/src/org/compiere/model/MDunningRunLine.java
Labels: 02 bug, (AR) Account Receivable, 09 Pending Peer Review

#4107 Default charge on bank statement
  client/src/org/spin/apps/form/BankStatementMatchController.java
Labels: 11 Waiting for Closing

#3963 #3920 GL Distribution doesn't work for any account https://github.co…
  base/src/org/compiere/acct/Fact.java
  base/src/org/compiere/model/MDistribution.java
Labels: 02 bug, 11 Waiting for Closing, 10 Reviewed by Peer, 14 Waiting for User Changes, (AC) Accounting

#4076 Add Columns to Import Payment
  base/src/org/compiere/process/ImportPayment.java
  data/import/Example_Payment.tsv
  data/import/Example_Payment.xlsx
  migration/394lts-395lts/10310_Add_Description_And_Conversion_Type_to_Import_Payment.xml
  migration/394lts-395lts/10320_Add_Payment_Import_Format.xml
Labels: (AR) Account Receivable, (AP) Account Payable, 12 Feature, 25 Waiting for Weekly Meeting

#4082 Fixed error with element value insert for tree
  base/src/org/compiere/model/PO.java
Labels: 02 bug, 09 Pending Peer Review, (AC) Accounting, 02 bugfix -> 3.9.4.001

#4166 fix: Gradle Publish to Maven Local.
  .github/workflows/build_with_gradle.yml
  JasperReports/build.gradle
  base/build.gradle
  base/src/org/compiere/dbPort/JdbcTest.java
  base/src/org/compiere/dbPort/JdbcTestPG.java
  base/test/build.gradle
  build.gradle
  client/build.gradle
  extend/build.gradle
  gradle.properties
  install/build.gradle
  migration/build.gradle
  org.adempiere.asset/build.gradle
  org.adempiere.crm/build.gradle
  org.adempiere.pos/build.gradle
  org.adempiere.production/build.gradle
  org.adempiere.project/build.gradle
  org.adempiere.request/build.gradle
  org.adempiere.test/build.gradle
  org.eevolution.cashflow/build.gradle
  org.eevolution.distribution/build.gradle
  org.eevolution.freight/build.gradle
  org.eevolution.hr_and_payroll/build.gradle
  org.eevolution.manufacturing/build.gradle
  org.eevolution.warehouse/build.gradle
  org.spin.authentication/build.gradle
  org.spin.finance_management/build.gradle
  org.spin.hr_time_and_attendance/build.gradle
  org.spin.loan_management/build.gradle
  org.spin.notifier.discord/build.gradle
  org.spin.notifier.telegram/build.gradle
  org.spin.store/build.gradle
  serverRoot/build.gradle
  settings.gradle
  tools/build.gradle
Labels: 10 Reviewed by Peer, (CI/CD) Continuous Integration/Continous Delivery, 02 bugfix -> 3.9.4.001

#4162 fix: Remove warning `The constructor FormFrame() is deprecated`.
  client/src/org/compiere/apps/AArchive.java
  client/src/org/compiere/apps/AMenuStartItem.java
  client/src/org/compiere/apps/form/FormFrame.java
  client/src/org/compiere/apps/form/VAttributeGrid.java
  client/src/org/compiere/apps/form/VPaySelect.java
  client/src/org/compiere/apps/wf/WFActivity.java
  org.adempiere.pos/src/main/java/ui/swing/org/adempiere/pos/POSApplication.java
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4142 fix: Postgres `LIMIT` clause and omit `"limit"` column name.
  base/src/org/compiere/dbPort/Convert_PostgreSQL.java
Labels: 02 bug, (SC) System Core, 09 Pending Peer Review, 02 bugfix -> 3.9.4.001

#4194 Update README.md
  README.md
Labels: 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4081 Fix Error On Production Light
  base/src/org/compiere/model/MProduction.java
Labels: 02 bug, (PLH) Production Light, 09 Pending Peer Review, 02 bugfix -> 3.9.4.001

#4197 #3920 GL Distribution doesn't work for any account https://github.co…
  base/src/org/compiere/acct/Fact.java
  base/src/org/compiere/model/MDistribution.java
Labels: 02 bug, 09 Pending Peer Review, (AC) Accounting, 02 bugfix -> 3.9.4.001

#4198 Bugfix/3924 notification created in scheduler run
  base/src/org/compiere/model/MScheduler.java
Labels: 02 bug, 14 Waiting for User Changes, (SS) Scheduler, (NQS) Notification Queue Suport, 02 bugfix -> 3.9.4.001

#4139 Use AD_Client_ID constant for 10.000x speedup.
  base/src/org/compiere/process/ImportProduct.java
  migration/394lts-395lts/09910_Add_Application_Support_to_Login_With_Microsoft_Azure.xml
  migration/394lts-395lts/09920_Refactory_Package_Authentication.xml
  org.spin.authentication/src/main/java/base/org/spin/authentication/services/provider/GoogleAuthentication.java
  org.spin.authentication/src/main/java/base/org/spin/authentication/services/provider/MicrosoftAuthentication.java
Labels: 02 bug, 09 Pending Peer Review, (IO) Input/Output

#4218 Fixed error with bad constraint for `M_ProductionLine.ReversalLine_ID`
  migration/394lts-3.9.4.001/09970_Fix_Production_Line_constraint.xml
Labels: 02 bug, (MM) Material Management, (PLH) Production Light, 02 bugfix -> 3.9.4.001

#4217 Feature/3.9.4.001 correct xml sequences
  migration/394lts-3.9.4.001/09910_Rename_payroll_packages.xml
  migration/394lts-3.9.4.001/09920_Refactory_Package_Authentication.xml
  migration/394lts-3.9.4.001/09930_Fix_Read_Only_Logic_in_AD_ClientInfo_table_columns.xml
  migration/394lts-3.9.4.001/09940_Fixed_Deletion_of_records_form_another_client.xml
  migration/394lts-3.9.4.001/09950_Add_Application_Support_to_Login_With_Microsoft_Azure.xml
  migration/394lts-3.9.4.001/09960_Add_Document_Type_for_Requisition_PO_Create.xml
Labels: 09 Pending Peer Review, (RLS) Release, 02 bugfix -> 3.9.4.001

#4177 fix: #4176 File Handler on `System` client.
  base/src/org/compiere/model/MAttachment.java
  base/src/org/spin/util/AttachmentUtil.java
  migration/394lts-3.9.4.001/09980_4176_File_Handler_not_supported_on_System_client.xml
Labels: 02 bug, 09 Pending Peer Review, (IO) Input/Output, 02 bugfix -> 3.9.4.001

#4186 Fixed error with size of `HR_Employee.Code`
  migration/394lts-395lts/09990_Fix_Lenght_for_Employee_Validation_Code.xml
Labels: 02 bug, (HRM) Human Resource and Payroll Management, 14 Waiting for User Changes, (MNC) Minor Change, 02 bugfix -> 3.9.4.001

#4222 fix: CI with `MPPProductBOMLine` import, and `com.amazonaws` package ant build.
  base/build.xml
  base/src/org/compiere/model/MProduction.java
Labels: 02 bug, 02 bugfix -> 3.9.3.001

#4230 Just change sequence to XML and remove 394lts-395lts folder
  migration/394lts-3.9.4.001/09990_Fix_Lenght_for_Employee_Validation_Code.xml
  migration/394lts-3.9.4.001/10000_4086_Add_Garden_World_Test_Data.xml
  migration/394lts-3.9.4.001/10010_4086_Add_Attendance_Import_Format.xml
  migration/394lts-3.9.4.001/10020_TNA_Add_Standard_Button_to_Import.xml
Labels: 02 bug, 02 bugfix -> 3.9.3.001

#4184 fix: #4183 Chartdatasource and table without keys.
  base/src/org/compiere/model/MChartDatasource.java
Labels: 02 bug, (SC) System Core, 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.001
