Repository adempiere/adempiere, pull requests merged in 2023-01, with the labels that each got.

#4041 #4038 [Bug Report] Error when creating the Client
  base/src/org/adempiere/process/ASPGenerateLevel.java
  base/src/org/adempiere/process/CreateCustomizationFromASP.java
  base/src/org/compiere/acct/Doc_Invoice.java
  base/src/org/compiere/model/MAcctSchema.java
  base/src/org/compiere/model/MClient.java
  base/src/org/compiere/model/MClientInfo.java
  base/src/org/compiere/model/MPeriod.java
  base/src/org/compiere/report/FinReport.java
  base/src/org/spin/process/SetupFileStorageSystem.java
  base/src/org/spin/util/AttachmentUtil.java
Labels: 02 bug, (SC) System Core

#4044 #4043 [Feature Request] Fix 09890_4035_Add_Foreign_Keys_3_9_4.xml Du…
  migration/393lts-394lts/09890_4035_Add_Foreign_Keys_3_9_4.xml
Labels: 02 bug, 01 enhancement

#4047 #4046 [Bug Report] Error to try load the PropertyFile in Server Mode,…
  base/src/org/compiere/db/CConnection.java
  install/src/org/compiere/install/ConfigurationData.java
  migration/393lts-394lts/09240_Enlarge_length_for_Description_on_Order_and_Invoice.xml
  migration/393lts-394lts/09890_4035_Add_Foreign_Keys_3_9_4.xml
  utils/myEnvironmentTemplate.bat
  utils/myEnvironmentTemplate.sh
Labels: 02 bug, (AD) Application Dictionary, (SC) System Core

#4049 #4048 [Bug Report] Lock transaction when try complete a payment using…
  base/src/org/compiere/model/MFactAcct.java
  base/src/org/compiere/process/DocumentEngine.java
  base/src/org/compiere/wf/MWorkflow.java
Labels: 02 bug, (AR) Account Receivable, (AP) Account Payable

#4053 Database Restore Backward Compatibility and Github Actions
  .github/actions/adempiere-build/action.yml
  .github/workflows/main.yml
  build.xml
  utils/PostgreSQL/DBRestore.sh
  utils/RUN_DBRestore.sh
Labels: 02 bug, 09 Pending Peer Review, (CI/CD) Continuous Integration/Continous Delivery
