Repository adempiere/adempiere, pull requests merged in 2023-12, with the labels that each got.

#4261 Update main.yml
  .github/workflows/main.yml
Labels: 02 bug, (CI/CD) Continuous Integration/Continous Delivery, 02 bugfix -> 3.9.4.002

#4260 Update build_with_gradle.yml
  .github/workflows/build_with_gradle.yml
Labels: 02 bug, (CI/CD) Continuous Integration/Continous Delivery, 02 bugfix -> 3.9.4.002

#4263 fix: #4183 Chartdatasource and table without keys.
  base/src/org/compiere/model/MChartDatasource.java
Labels: 02 bug, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.002

#4237 Fixed NPE for Import Product BOM
  base/src/org/compiere/model/MTable.java
Labels: 02 bug, (AD) Application Dictionary, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.002

#4239 Validate product for receipt inside
  org.adempiere.asset/src/main/java/base/org/compiere/asset/model/validator/FixedAsset.java
Labels: 02 bug, (FAM) Fixed Asset Management, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.002

#4242 Extend scope of payment processor variable for implementation
  base/src/org/compiere/model/PaymentProcessor.java
Labels: 02 bug, 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.002, (SRC) Source Code Maintenance

#4244 Fixed error with bad transaction for Setup File Storage
  base/src/org/spin/process/SetupFileStorageSystem.java
Labels: 02 bug, 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.002

#4246 Fixed error with many executions for report flagged as `IsForm` inside
  base/src/org/compiere/print/ReportEngine.java
Labels: 02 bug, 10 Reviewed by Peer, (PF) Report Engine & Print Format, 02 bugfix -> 3.9.4.002

#4254 Fixed error with duplicated session
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: 02 bug, (SE) Security, 10 Reviewed by Peer, 17 Waiting for Information, 19 Not reproducible, 02 bugfix -> 3.9.4.002

#4276 fix: CI With gradle.
  .github/workflows/build_with_gradle.yml
  .github/workflows/main.yml
Labels: 02 bug, (CI/CD) Continuous Integration/Continous Delivery

#4250 Fixed error with Printing report from Payroll Process
  zkwebui/WEB-INF/src/org/adempiere/webui/panel/AbstractADWindowPanel.java
Labels: 02 bug, 10 Reviewed by Peer, (PF) Report Engine & Print Format, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4256 Fixed error with price calculation for RMA
  base/src/org/compiere/model/MOrderLine.java
Labels: 02 bug, (SO) Sales Management, (POS) Point Of Sales, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4265 Fixed error with commission run detail report
  db/ddlutils/oracle/views/RV_COMMISSIONRUNDETAIL.sql
  db/ddlutils/postgresql/views/RV_COMMISSIONRUNDETAIL.sql
  migration/394lts-3.9.4.002/10330_Fixed_Commission_Run_Detail_View.xml
Labels: 02 bug, 10 Reviewed by Peer, (COM) Commission, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4267 Bug Fix Missing trx in workflow query outdated PO data
  base/src/org/compiere/wf/MWFProcess.java
Labels: 02 bug, (BPM) Workflow Engine, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4270 [Bug Report] Generate Invoice from Commission Run Error #4269
  base/src/org/compiere/process/CommissionAPInvoice.java
  base/src/org/compiere/process/CommissionAPInvoiceAbstract.java
  migration/394lts-3.9.4.002/10340_4269_Generate_Invoice_from_Commission_Run_Error.xml
Labels: 02 bug, 10 Reviewed by Peer, (COM) Commission, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4273 Fixed error with NPE for missing rule
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/hr/model/MHRProcess.java
Labels: 02 bug, (HRM) Human Resource and Payroll Management, 10 Reviewed by Peer, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4277 Improve Payroll Process `Env` variables
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/hr/model/MHRProcess.java
Labels: (HRM) Human Resource and Payroll Management, 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4280 Fix: When filtering the warehouse in the Requisition
  migration/394lts-3.9.4.0002/10330_requisition_with_all_warehouse.xml
Labels: 02 bug, (PO) Purchase Management, 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4272 Hotfix/3.9.4.002 local/#gradle generate asset v1
  .classpath
  .vscode/settings.json
  adempiere.iml
  base/build.gradle
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/CheckboxTree.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/CheckboxTreeCellRenderer.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/DefaultCheckboxTreeCellRenderer.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/DefaultTreeCheckingModel.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/PropagatePreservingCheckTreeCheckingMode.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/PropagatePreservingUncheckTreeCheckingMode.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/PropagateTreeCheckingMode.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/PropagateUpWhiteTreeCheckingMode.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/QuadristateButtonModel.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/QuadristateCheckbox.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/SimpleTreeCheckingMode.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/TreeCheckingEvent.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/TreeCheckingListener.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/TreeCheckingMode.java
  base/src/it/cnr/imaa/essi/lablib/gui/checkboxtree/TreeCheckingModel.java
  build.gradle
  client/build.gradle
  install/build.gradle
  tools/build.xml
  tools/lib/harness.jar
Labels: 02 bug, 10 Reviewed by Peer, (CI/CD) Continuous Integration/Continous Delivery, 02 bugfix -> 3.9.4.002, 26 Waiting for Merge

#4275 Improve In-Memory performance to get `lastConcept` method
  org.eevolution.hr_and_payroll/src/main/java/base/org/eevolution/hr/model/MHRProcess.java
Labels: 01 enhancement, (HRM) Human Resource and Payroll Management, 10 Reviewed by Peer, (MNC) Minor Change, 02 bugfix -> 3.9.4.002

#4278 Fixed error with Import Product definition for `Volume` column
  base/src/org/adempiere/core/domains/models/I_I_Product.java
  base/src/org/adempiere/core/domains/models/I_M_Product.java
  base/src/org/adempiere/core/domains/models/X_I_Product.java
  base/src/org/adempiere/core/domains/models/X_M_Product.java
  migration/394lts-3.9.4.002/10350_Fixed_error_with_Wrong_Definition_Import_Column_for_Product.xml
Labels: 02 bug, (MM) Material Management, 02 bugfix -> 3.9.4.002
