Repository adempiere/adempiere, pull requests merged in 2023-09, with the labels that each got.

#3490 fix: NULL line counter in ContextInfo.
  base/src/org/spin/model/MADContextInfo.java
Labels: 17 Waiting for Information, ZZ Motionless

#4147 #4145 [Bug Report] Remove the incorrect exception for Dashboard https…
  base/src/org/adempiere/apps/graph/GraphBuilder.java
Labels: 02 bug, 02 bugfix -> 3.9.4.001

#4070 Change modifier to public to TimeUtil methods
  base/src/org/compiere/util/TimeUtil.java
Labels: (SC) System Core, 12 Feature

#4124 fix: Read Only Logic in `AD_ClientInfo` table columns.
  migration/394lts-395lts/09930_Fix_Read_Only_Logic_in_AD_ClientInfo_table_columns.xml
Labels: 02 bug, (AD) Application Dictionary, 10 Reviewed by Peer

#4125 fix: `ImpFormat` load by identifier.
  base/src/org/compiere/impexp/ImpFormat.java
  base/test/src/org/compiere/impexp/UT_ImFormat.java
Labels: 02 bug, 09 Pending Peer Review, (IO) Input/Output
